/*
 Highcharts Gantt JS v8.0.4 (2020-03-19)

 Gantt series

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(l){"object"===typeof module&&module.exports?(l["default"]=l,module.exports=l):"function"===typeof define&&define.amd?define("highcharts/modules/gantt",["highcharts"],function(F){l(F);l.Highcharts=F;return l}):l("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(l){function F(u,a,w,g){u.hasOwnProperty(a)||(u[a]=g.apply(null,w))}l=l?l._modules:{};F(l,"parts-gantt/CurrentDateIndicator.js",[l["parts/Globals.js"],l["parts/Utilities.js"],l["parts/PlotLineOrBand.js"]],function(u,a,w){var g=
a.addEvent,r=a.merge;a=a.wrap;var l={currentDateIndicator:!0,color:"#ccd6eb",width:2,label:{format:"%a, %b %d %Y, %H:%M",formatter:function(g,a){return u.dateFormat(a,g)},rotation:0,style:{fontSize:"10px"}}};g(u.Axis,"afterSetOptions",function(){var g=this.options,a=g.currentDateIndicator;a&&(a="object"===typeof a?r(l,a):r(l),a.value=new Date,g.plotLines||(g.plotLines=[]),g.plotLines.push(a))});g(w,"render",function(){this.label&&this.label.attr({text:this.getLabelText(this.options.label)})});a(w.prototype,
"getLabelText",function(g,a){var x=this.options;return x.currentDateIndicator&&x.label&&"function"===typeof x.label.formatter?(x.value=new Date,x.label.formatter.call(this,x.value,x.label.format)):g.call(this,a)})});F(l,"parts-gantt/GridAxis.js",[l["parts/Globals.js"],l["parts/Tick.js"],l["parts/Utilities.js"]],function(u,a,w){var g=w.addEvent,r=w.defined,l=w.erase,D=w.find,B=w.isArray,x=w.isNumber,f=w.merge,p=w.pick,n=w.timeUnits,z=w.wrap,E=u.dateFormat,C=function(c){return w.isObject(c,!0)},t=u.Chart,
e=u.Axis,k=function(c){var b=c.options;b.labels||(b.labels={});b.labels.align=p(b.labels.align,"center");c.categories||(b.showLastLabel=!1);c.labelRotation=0;b.labels.rotation=0},A={top:0,right:1,bottom:2,left:3,0:"top",1:"right",2:"bottom",3:"left"};e.prototype.isOuterAxis=function(){var c=this,b=c.columnIndex,m=c.linkedParent&&c.linkedParent.columns||c.columns,d=b?c.linkedParent:c,k=-1,e=0;c.chart[c.coll].forEach(function(b,h){b.side!==c.side||b.options.isInternal||(e=h,b===d&&(k=h))});return e===
k&&(x(b)?m.length===b:!0)};e.prototype.getMaxLabelDimensions=function(c,b){var m={width:0,height:0};b.forEach(function(b){b=c[b];if(C(b)){var d=C(b.label)?b.label:{};b=d.getBBox?d.getBBox().height:0;d.textStr&&!x(d.textPxLength)&&(d.textPxLength=d.getBBox().width);d=x(d.textPxLength)?Math.round(d.textPxLength):0;m.height=Math.max(b,m.height);m.width=Math.max(d,m.width)}});return m};u.dateFormats.W=function(c){c=new this.Date(c);var b=(this.get("Day",c)+6)%7,m=new this.Date(c.valueOf());this.set("Date",
m,this.get("Date",c)-b+3);b=new this.Date(this.get("FullYear",m),0,1);4!==this.get("Day",b)&&(this.set("Month",c,0),this.set("Date",c,1+(11-this.get("Day",b))%7));return(1+Math.floor((m.valueOf()-b.valueOf())/6048E5)).toString()};u.dateFormats.E=function(c){return E("%a",c,!0).charAt(0)};g(a,"afterGetLabelPosition",function(c){var b=this.label,m=this.axis,d=m.reversed,k=m.chart,e=m.options,v=e&&C(e.grid)?e.grid:{};e=m.options.labels;var h=e.align,q=A[m.side],y=c.tickmarkOffset,G=m.tickPositions,K=
this.pos-y;G=x(G[c.index+1])?G[c.index+1]-y:m.max+y;var H=m.tickSize("tick",!0);y=B(H)?H[0]:0;H=H&&H[1]/2;if(!0===v.enabled){if("top"===q){v=m.top+m.offset;var n=v-y}else"bottom"===q?(n=k.chartHeight-m.bottom+m.offset,v=n+y):(v=m.top+m.len-m.translate(d?G:K),n=m.top+m.len-m.translate(d?K:G));"right"===q?(q=k.chartWidth-m.right+m.offset,d=q+y):"left"===q?(d=m.left+m.offset,q=d-y):(q=Math.round(m.left+m.translate(d?G:K))-H,d=Math.round(m.left+m.translate(d?K:G))-H);this.slotWidth=d-q;c.pos.x="left"===
h?q:"right"===h?d:q+(d-q)/2;c.pos.y=n+(v-n)/2;k=k.renderer.fontMetrics(e.style.fontSize,b.element);b=b.getBBox().height;e.useHTML?c.pos.y+=k.b+-(b/2):(b=Math.round(b/k.h),c.pos.y+=(k.b-(k.h-k.f))/2+-((b-1)*k.h/2));c.pos.x+=m.horiz&&e.x||0}});g(e,"afterTickSize",function(c){var b=e.defaultLeftAxisOptions,m=this.horiz,d=this.options.grid;d=void 0===d?{}:d;var k=this.maxLabelDimensions;d.enabled&&(b=2*Math.abs(b.labels.x),m=m?d.cellHeight||b+k.height:b+k.width,B(c.tickSize)?c.tickSize[0]=m:c.tickSize=
[m])});g(e,"afterGetTitlePosition",function(c){var b=this.options;if(!0===(b&&C(b.grid)?b.grid:{}).enabled){var m=this.axisTitle,d=m&&m.getBBox().width,k=this.horiz,e=this.left,v=this.top,h=this.width,q=this.height,y=b.title;b=this.opposite;var G=this.offset,K=this.tickSize()||[0],H=y.x||0,n=y.y||0,J=p(y.margin,k?5:10);m=this.chart.renderer.fontMetrics(y.style&&y.style.fontSize,m).f;K=(k?v+q:e)+K[0]/2*(b?-1:1)*(k?1:-1)+(this.side===A.bottom?m:0);c.titlePosition.x=k?e-d/2-J+H:K+(b?h:0)+G+H;c.titlePosition.y=
k?K-(b?q:0)+(b?m:-m)/2+G+n:v-J+n}});z(e.prototype,"unsquish",function(c){var b=this.options;return!0===(b&&C(b.grid)?b.grid:{}).enabled&&this.categories?this.tickInterval:c.apply(this,Array.prototype.slice.call(arguments,1))});g(e,"afterSetOptions",function(c){var b=this.options;c=c.userOptions;var m=b&&C(b.grid)?b.grid:{};if(!0===m.enabled){var d=f(!0,{className:"highcharts-grid-axis "+(c.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},
week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},c);"xAxis"===this.coll&&(r(c.linkedTo)&&!r(c.tickPixelInterval)&&(d.tickPixelInterval=350),r(c.tickPixelInterval)||!r(c.linkedTo)||r(c.tickPositioner)||r(c.tickInterval)||(d.tickPositioner=
function(b,c){var m=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(m){var h,q=d.units;for(h=0;h<q.length;h++)if(q[h][0]===m.unitName){var y=h;break}if(q[y+1]){var G=q[y+1][0];var k=(q[y+1][1]||[1])[0]}else"year"===m.unitName&&(G="year",k=10*m.count);m=n[G];this.tickInterval=m*k;return this.getTimeTicks({unitRange:m,count:k,unitName:G},b,c,this.options.startOfWeek)}}));f(!0,this.options,d);this.horiz&&(b.minPadding=p(c.minPadding,0),b.maxPadding=p(c.maxPadding,
0));x(b.grid.borderWidth)&&(b.tickWidth=b.lineWidth=m.borderWidth)}});g(e,"afterSetAxisTranslation",function(){var c=this.options,b=c&&C(c.grid)?c.grid:{},m=this.tickPositions&&this.tickPositions.info,d=this.userOptions.labels||{};this.horiz&&(!0===b.enabled&&this.series.forEach(function(b){b.options.pointRange=0}),m&&(!1===c.dateTimeLabelFormats[m.unitName].range||1<m.count)&&!r(d.align)&&(c.labels.align="left",r(d.x)||(c.labels.x=3)))});g(e,"trimTicks",function(){var c=this.options,b=c&&C(c.grid)?
c.grid:{},m=this.categories,d=this.tickPositions,k=d[0],e=d[d.length-1],v=this.linkedParent&&this.linkedParent.min||this.min,h=this.linkedParent&&this.linkedParent.max||this.max,q=this.tickInterval;!0!==b.enabled||m||!this.horiz&&!this.isLinked||(k<v&&k+q>v&&!c.startOnTick&&(d[0]=v),e>h&&e-q<h&&!c.endOnTick&&(d[d.length-1]=h))});g(e,"afterRender",function(){var c=this.options,b=c&&C(c.grid)?c.grid:{},d=this.chart.renderer;if(!0===b.enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,
this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.isOuterAxis()&&this.axisLine){var k=c.lineWidth;if(k){var e=this.getLinePath(k);var n=e.indexOf("M")+1;var v=e.indexOf("L")+1;b=e.indexOf("M")+2;var h=e.indexOf("L")+2;var q=(this.tickSize("tick")[0]-1)*(this.side===A.top||this.side===A.left?-1:1);this.horiz?(e[b]+=q,e[h]+=q):(e[n]+=q,e[v]+=q);this.axisLineExtra?this.axisLineExtra.animate({d:e}):(this.axisLineExtra=d.path(e).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),
d.styledMode||this.axisLineExtra.attr({stroke:c.lineColor,"stroke-width":k}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(this.columns||[]).forEach(function(h){h.render()})}});var d={afterGetOffset:function(){(this.columns||[]).forEach(function(c){c.getOffset()})},afterInit:function(){var c=this.chart,b=this.userOptions,d=this.options;d=d&&C(d.grid)?d.grid:{};d.enabled&&(k(this),z(this,"labelFormatter",function(b){var h=this.axis,c=h.tickPositions,d=this.value,m=(h.isLinked?h.linkedParent:h).series[0],
v=d===c[0];c=d===c[c.length-1];m=m&&D(m.options.data,function(b){return b[h.isXAxis?"x":"y"]===d});this.isFirst=v;this.isLast=c;this.point=m;return b.call(this)}));if(d.columns)for(var n=this.columns=[],A=this.columnIndex=0;++A<d.columns.length;){var p=f(b,d.columns[d.columns.length-A-1],{linkedTo:0,type:"category"});delete p.grid.columns;p=new e(this.chart,p,!0);p.isColumn=!0;p.columnIndex=A;l(c.axes,p);l(c[this.coll],p);n.push(p)}},afterSetOptions:function(c){c=(c=c.userOptions)&&C(c.grid)?c.grid:
{};var b=c.columns;c.enabled&&b&&f(!0,this.options,b[b.length-1])},afterSetScale:function(){(this.columns||[]).forEach(function(c){c.setScale()})},destroy:function(c){(this.columns||[]).forEach(function(b){b.destroy(c.keepEvents)})},init:function(c){var b=(c=c.userOptions)&&C(c.grid)?c.grid:{};b.enabled&&r(b.borderColor)&&(c.tickColor=c.lineColor=b.borderColor)}};Object.keys(d).forEach(function(c){g(e,c,d[c])});g(t,"afterSetChartSize",function(){this.axes.forEach(function(c){(c.columns||[]).forEach(function(b){b.setAxisSize();
b.setAxisTranslation()})})})});F(l,"modules/static-scale.src.js",[l["parts/Globals.js"],l["parts/Utilities.js"]],function(u,a){var w=a.addEvent,g=a.defined,r=a.isNumber,l=a.pick;a=u.Chart;w(u.Axis,"afterSetOptions",function(){var g=this.chart.options&&this.chart.options.chart;!this.horiz&&r(this.options.staticScale)&&(!g.height||g.scrollablePlotArea&&g.scrollablePlotArea.minHeight)&&(this.staticScale=this.options.staticScale)});a.prototype.adjustHeight=function(){"adjustHeight"!==this.redrawTrigger&&
((this.axes||[]).forEach(function(a){var r=a.chart,x=!!r.initiatedScale&&r.options.animation,f=a.options.staticScale;if(a.staticScale&&g(a.min)){var p=l(a.unitLength,a.max+a.tickInterval-a.min)*f;p=Math.max(p,f);f=p-r.plotHeight;1<=Math.abs(f)&&(r.plotHeight=p,r.redrawTrigger="adjustHeight",r.setSize(void 0,r.chartHeight+f,x));a.series.forEach(function(n){(n=n.sharedClipKey&&r[n.sharedClipKey])&&n.attr({height:r.plotHeight})})}}),this.initiatedScale=!0);this.redrawTrigger=null};w(a,"render",a.prototype.adjustHeight)});
F(l,"mixins/tree-series.js",[l["parts/Color.js"],l["parts/Utilities.js"]],function(u,a){var w=a.extend,g=a.isArray,r=a.isNumber,l=a.isObject,D=a.merge,B=a.pick;return{getColor:function(a,f){var p=f.index,n=f.mapOptionsToLevel,z=f.parentColor,g=f.parentColorIndex,x=f.series,t=f.colors,e=f.siblings,k=x.points,A=x.chart.options.chart,d;if(a){k=k[a.i];a=n[a.level]||{};if(n=k&&a.colorByPoint){var c=k.index%(t?t.length:A.colorCount);var b=t&&t[c]}if(!x.chart.styledMode){t=k&&k.options.color;A=a&&a.color;
if(d=z)d=(d=a&&a.colorVariation)&&"brightness"===d.key?u.parse(z).brighten(p/e*d.to).get():z;d=B(t,A,b,d,x.color)}var m=B(k&&k.options.colorIndex,a&&a.colorIndex,c,g,f.colorIndex)}return{color:d,colorIndex:m}},getLevelOptions:function(a){var f=null;if(l(a)){f={};var p=r(a.from)?a.from:1;var n=a.levels;var z={};var x=l(a.defaults)?a.defaults:{};g(n)&&(z=n.reduce(function(n,f){if(l(f)&&r(f.level)){var e=D({},f);var k="boolean"===typeof e.levelIsConstant?e.levelIsConstant:x.levelIsConstant;delete e.levelIsConstant;
delete e.level;f=f.level+(k?0:p-1);l(n[f])?w(n[f],e):n[f]=e}return n},{}));n=r(a.to)?a.to:1;for(a=0;a<=n;a++)f[a]=D({},x,l(z[a])?z[a]:{})}return f},setTreeValues:function n(f,a){var z=a.before,p=a.idRoot,g=a.mapIdToNode[p],t=a.points[f.i],e=t&&t.options||{},k=0,A=[];w(f,{levelDynamic:f.level-(("boolean"===typeof a.levelIsConstant?a.levelIsConstant:1)?0:g.level),name:B(t&&t.name,""),visible:p===f.id||("boolean"===typeof a.visible?a.visible:!1)});"function"===typeof z&&(f=z(f,a));f.children.forEach(function(d,
c){var b=w({},a);w(b,{index:c,siblings:f.children.length,visible:f.visible});d=n(d,b);A.push(d);d.visible&&(k+=d.val)});f.visible=0<k||f.visible;z=B(e.value,k);w(f,{children:A,childrenTotal:k,isLeaf:f.visible&&!k,val:z});return f},updateRootId:function(f){if(l(f)){var a=l(f.options)?f.options:{};a=B(f.rootNode,a.rootId,"");l(f.userOptions)&&(f.userOptions.rootId=a);f.rootNode=a}return a}}});F(l,"parts-gantt/Tree.js",[l["parts/Utilities.js"]],function(u){var a=u.extend,l=u.isNumber,g=u.pick,r=function(a,
r){var x=a.reduce(function(a,p){var n=g(p.parent,"");"undefined"===typeof a[n]&&(a[n]=[]);a[n].push(p);return a},{});Object.keys(x).forEach(function(a,p){var n=x[a];""!==a&&-1===r.indexOf(a)&&(n.forEach(function(n){p[""].push(n)}),delete p[a])});return x},I=function(r,u,x,f,p,n){var z=0,E=0,C=n&&n.after,t=n&&n.before;u={data:f,depth:x-1,id:r,level:x,parent:u};var e,k;"function"===typeof t&&t(u,n);t=(p[r]||[]).map(function(a){var d=I(a.id,r,x+1,a,p,n),c=a.start;a=!0===a.milestone?c:a.end;e=!l(e)||
c<e?c:e;k=!l(k)||a>k?a:k;z=z+1+d.descendants;E=Math.max(d.height+1,E);return d});f&&(f.start=g(f.start,e),f.end=g(f.end,k));a(u,{children:t,descendants:z,height:E});"function"===typeof C&&C(u,n);return u};return{getListOfParents:r,getNode:I,getTree:function(a,g){var x=a.map(function(a){return a.id});a=r(a,x);return I("",null,1,null,a,g)}}});F(l,"modules/broken-axis.src.js",[l["parts/Globals.js"],l["parts/Utilities.js"],l["parts/Stacking.js"]],function(u,a,l){var g=a.addEvent,r=a.extend,w=a.find,D=
a.fireEvent,B=a.isArray,x=a.pick,f=u.Axis;a=u.Series;var p=function(a,f){return w(f,function(n){return n.from<a&&a<n.to})};r(f.prototype,{isInBreak:function(a,f){var n=a.repeat||Infinity,p=a.from,z=a.to-a.from;f=f>=p?(f-p)%n:n-(p-f)%n;return a.inclusive?f<=z:f<z&&0!==f},isInAnyBreak:function(a,f){var n=this.options.breaks,p=n&&n.length,z;if(p){for(;p--;)if(this.isInBreak(n[p],a)){var e=!0;z||(z=x(n[p].showPoints,!this.isXAxis))}var k=e&&f?e&&!z:e}return k}});g(f,"afterInit",function(){"function"===
typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});g(f,"afterSetTickPositions",function(){if(this.isBroken){var a=this.tickPositions,f=this.tickPositions.info,p=[],g;for(g=0;g<a.length;g++)this.isInAnyBreak(a[g])||p.push(a[g]);this.tickPositions=p;this.tickPositions.info=f}});g(f,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});f.prototype.setBreaks=function(a,z){function n(k){var e=k,d;for(d=0;d<t.breakArray.length;d++){var c=t.breakArray[d];if(c.to<=k)e-=c.len;
else if(c.from>=k)break;else if(t.isInBreak(c,k)){e-=k-c.from;break}}return e}function g(k){var e;for(e=0;e<t.breakArray.length;e++){var d=t.breakArray[e];if(d.from>=k)break;else d.to<k?k+=d.len:t.isInBreak(d,k)&&(k+=d.len)}return k}var t=this,e=B(a)&&!!a.length;t.isDirty=t.isBroken!==e;t.isBroken=e;t.options.breaks=t.userOptions.breaks=a;t.forceRedraw=!0;t.series.forEach(function(e){e.isDirty=!0});e||t.val2lin!==n||(delete t.val2lin,delete t.lin2val);e&&(t.userOptions.ordinal=!1,t.val2lin=n,t.lin2val=
g,t.setExtremes=function(e,a,d,c,b){if(this.isBroken){for(var m,k=this.options.breaks;m=p(e,k);)e=m.to;for(;m=p(a,k);)a=m.from;a<e&&(a=e)}f.prototype.setExtremes.call(this,e,a,d,c,b)},t.setAxisTranslation=function(e){f.prototype.setAxisTranslation.call(this,e);this.unitLength=null;if(this.isBroken){e=t.options.breaks;var k=[],d=[],c=0,b,m=t.userMin||t.min,a=t.userMax||t.max,n=x(t.pointRangePadding,0),p;e.forEach(function(h){b=h.repeat||Infinity;t.isInBreak(h,m)&&(m+=h.to%b-m%b);t.isInBreak(h,a)&&
(a-=a%b-h.from%b)});e.forEach(function(c){h=c.from;for(b=c.repeat||Infinity;h-b>m;)h-=b;for(;h<m;)h+=b;for(p=h;p<a;p+=b)k.push({value:p,move:"in"}),k.push({value:p+(c.to-c.from),move:"out",size:c.breakSize})});k.sort(function(h,c){return h.value===c.value?("in"===h.move?0:1)-("in"===c.move?0:1):h.value-c.value});var v=0;var h=m;k.forEach(function(b){v+="in"===b.move?1:-1;1===v&&"in"===b.move&&(h=b.value);0===v&&(d.push({from:h,to:b.value,len:b.value-h-(b.size||0)}),c+=b.value-h-(b.size||0))});t.breakArray=
d;t.unitLength=a-m-c+n;D(t,"afterBreaks");t.staticScale?t.transA=t.staticScale:t.unitLength&&(t.transA*=(a-t.min+n)/t.unitLength);n&&(t.minPixelPadding=t.transA*t.minPointOffset);t.min=m;t.max=a}});x(z,!0)&&this.chart.redraw()};g(a,"afterGeneratePoints",function(){var a=this.options.connectNulls,f=this.points,p=this.xAxis,g=this.yAxis;if(this.isDirty)for(var t=f.length;t--;){var e=f[t],k=!(null===e.y&&!1===a)&&(p&&p.isInAnyBreak(e.x,!0)||g&&g.isInAnyBreak(e.y,!0));e.visible=k?!1:!1!==e.options.visible}});
g(a,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,x(this.pointArrayMap,["y"]))});u.Series.prototype.drawBreaks=function(a,f){var n=this,p=n.points,g,e,k,A;a&&f.forEach(function(d){g=a.breakArray||[];e=a.isXAxis?a.min:x(n.options.threshold,a.min);p.forEach(function(c){A=x(c["stack"+d.toUpperCase()],c[d]);g.forEach(function(b){k=!1;if(e<b.from&&A>b.to||e>b.from&&A<b.from)k="pointBreak";else if(e<b.from&&A>b.from&&A<b.to||e>b.from&&A>b.to&&A<b.from)k="pointInBreak";
k&&D(a,k,{point:c,brk:b})})})})};u.Series.prototype.gappedPath=function(){var a=this.currentDataGrouping,f=a&&a.gapSize;a=this.options.gapSize;var p=this.points.slice(),g=p.length-1,t=this.yAxis,e;if(a&&0<g)for("value"!==this.options.gapUnit&&(a*=this.basePointRange),f&&f>a&&f>=this.basePointRange&&(a=f),e=void 0;g--;)e&&!1!==e.visible||(e=p[g+1]),f=p[g],!1!==e.visible&&!1!==f.visible&&(e.x-f.x>a&&(e=(f.x+e.x)/2,p.splice(g+1,0,{isNull:!0,x:e}),this.options.stacking&&(e=t.stacks[this.stackKey][e]=
new l(t,t.options.stackLabels,!1,e,this.stack),e.total=0)),e=f);return this.getGraphPath(p)}});F(l,"parts-gantt/TreeGrid.js",[l["parts/Globals.js"],l["mixins/tree-series.js"],l["parts/Tick.js"],l["parts-gantt/Tree.js"],l["parts/Utilities.js"]],function(u,a,l,g,r){var w=r.addEvent,D=r.defined,B=r.fireEvent,x=r.extend,f=r.isNumber,p=r.isString,n=r.merge,z=r.pick,E=r.wrap,C=function(b){return Array.prototype.slice.call(b,1)},t=r.find,e=a.getLevelOptions,k=function(b){return r.isObject(b,!0)};u=u.Axis;
a=function(b,h){var c;for(c in h)if(Object.hasOwnProperty.call(h,c)){var d=h[c];E(b,c,d)}};var A=function(b,h){var c=b.collapseStart;b=b.collapseEnd;b>=h&&(c-=.5);return{from:c,to:b,showPoints:!1}},d=function(b){return Object.keys(b.mapOfPosToGridNode).reduce(function(h,c){c=+c;b.min<=c&&b.max>=c&&!b.isInAnyBreak(c)&&h.push(c);return h},[])},c=function(b,h){var c=b.options.breaks||[],d=A(h,b.max);return c.some(function(h){return h.from===d.from&&h.to===d.to})},b=function(b,h){var c=b.options.breaks||
[];b=A(h,b.max);c.push(b);return c},m=function(b,h){var c=b.options.breaks||[],d=A(h,b.max);return c.reduce(function(h,b){b.to===d.to&&b.from===d.from||h.push(b);return h},[])},P=function(b,h){var c=b.labelIcon,d=!c,m=h.renderer,e=h.xy,a=h.options,k=a.width,v=a.height,n=e.x-k/2-a.padding;e=e.y-v/2;var p=h.collapsed?90:180,P=h.show&&f(e);d&&(b.labelIcon=c=m.path(m.symbols[a.type](a.x,a.y,k,v)).addClass("highcharts-label-icon").add(h.group));P||c.attr({y:-9999});m.styledMode||c.attr({"stroke-width":1,
fill:z(h.color,"#666666")}).css({cursor:"pointer",stroke:a.lineColor,strokeWidth:a.lineWidth});c[d?"attr":"animate"]({translateX:n,translateY:e,rotation:p})},R=function(b,h,c){var d=[],q=[],m={},a={},e=-1,v="boolean"===typeof h?h:!1;b=g.getTree(b,{after:function(b){b=a[b.pos];var h=0,c=0;b.children.forEach(function(b){c+=b.descendants+1;h=Math.max(b.height+1,h)});b.descendants=c;b.height=h;b.collapsed&&q.push(b)},before:function(b){var h=k(b.data)?b.data:{},c=p(h.name)?h.name:"",q=m[b.parent];q=k(q)?
a[q.pos]:null;var y=function(b){return b.name===c},G;v&&k(q)&&(G=t(q.children,y))?(y=G.pos,G.nodes.push(b)):y=e++;a[y]||(a[y]=G={depth:q?q.depth+1:0,name:c,nodes:[b],children:[],pos:y},-1!==y&&d.push(c),k(q)&&q.children.push(G));p(b.id)&&(m[b.id]=b);!0===h.collapsed&&(G.collapsed=!0);b.pos=y}});a=function(b,h){var c=function(b,d,q){var m=d+(-1===d?0:h-1),y=(m-d)/2,a=d+y;b.nodes.forEach(function(b){var h=b.data;k(h)&&(h.y=d+h.seriesIndex,delete h.seriesIndex);b.pos=a});q[a]=b;b.pos=a;b.tickmarkOffset=
y+.5;b.collapseStart=m+.5;b.children.forEach(function(b){c(b,m+1,q);m=b.collapseEnd-.5});b.collapseEnd=m+.5;return q};return c(b["-1"],-1,{})}(a,c);return{categories:d,mapOfIdToNode:m,mapOfPosToGridNode:a,collapsedNodes:q,tree:b}},M=function(c){c.target.axes.filter(function(b){return"treegrid"===b.options.type}).forEach(function(h){var d=h.options||{},m=d.labels,a,v=d.uniqueNames,H=0;if(!h.mapOfPosToGridNode||h.series.some(function(b){return!b.hasRendered||b.isDirtyData||b.isDirty})){d=h.series.reduce(function(b,
h){h.visible&&(h.options.data.forEach(function(h){k(h)&&(h.seriesIndex=H,b.push(h))}),!0===v&&H++);return b},[]);var f=R(d,v,!0===v?H:1);h.categories=f.categories;h.mapOfPosToGridNode=f.mapOfPosToGridNode;h.hasNames=!0;h.tree=f.tree;h.series.forEach(function(b){var h=b.options.data.map(function(b){return k(b)?n(b):b});b.visible&&b.setData(h,!1)});h.mapOptionsToLevel=e({defaults:m,from:1,levels:m.levels,to:h.tree.height});"beforeRender"===c.type&&(a=w(h,"foundExtremes",function(){f.collapsedNodes.forEach(function(c){c=
b(h,c);h.setBreaks(c,!1)});a()}))}})};a(u.prototype,{init:function(b,h,c){var d="treegrid"===c.type;d&&(w(h,"beforeRender",M),w(h,"beforeRedraw",M),c=n({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},c,{reversed:!0,grid:{columns:void 0}}));b.apply(this,[h,c]);d&&(this.hasNames=!0,this.options.showLastLabel=!0)},getMaxLabelDimensions:function(b){var h=this.options,c=
h&&h.labels;h=c&&f(c.indentation)?h.labels.indentation:0;c=b.apply(this,C(arguments));if("treegrid"===this.options.type&&this.mapOfPosToGridNode){var d=this.mapOfPosToGridNode[-1].height;c.width+=h*(d-1)}return c},generateTick:function(b,h){var c=k(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},d=this.ticks,m=d[h],a;if("treegrid"===this.options.type){var e=this.mapOfPosToGridNode[h];(c=c[e.depth])&&(a={labels:c});m?(m.parameters.category=e.name,m.options=a,m.addLabel()):d[h]=new l(this,h,null,
void 0,{category:e.name,tickmarkOffset:e.tickmarkOffset,options:a})}else b.apply(this,C(arguments))},setTickInterval:function(b){var h=this.options;"treegrid"===h.type?(this.min=z(this.userMin,h.min,this.dataMin),this.max=z(this.userMax,h.max,this.dataMax),B(this,"foundExtremes"),this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?d(this):[]):b.apply(this,C(arguments))}});a(l.prototype,{getLabelPosition:function(b,h,c,d,m,a,e,n,p){var q=
z(this.options&&this.options.labels,a);a=this.pos;var y=this.axis,G="treegrid"===y.options.type;b=b.apply(this,[h,c,d,m,q,e,n,p]);G&&(h=q&&k(q.symbol)?q.symbol:{},q=q&&f(q.indentation)?q.indentation:0,a=(a=(y=y.mapOfPosToGridNode)&&y[a])&&a.depth||1,b.x+=h.width+2*h.padding+(a-1)*q);return b},renderLabel:function(b){var h=this,d=h.pos,m=h.axis,a=h.label,e=m.mapOfPosToGridNode,v=m.options,f=z(h.options&&h.options.labels,v&&v.labels),n=f&&k(f.symbol)?f.symbol:{},p=(e=e&&e[d])&&e.depth;v="treegrid"===
v.type;var g=!(!a||!a.element),A=-1<m.tickPositions.indexOf(d);d=m.chart.styledMode;v&&e&&g&&a.addClass("highcharts-treegrid-node-level-"+p);b.apply(h,C(arguments));v&&e&&g&&0<e.descendants&&(m=c(m,e),P(h,{color:!d&&a.styles.color,collapsed:m,group:a.parentGroup,options:n,renderer:a.renderer,show:A,xy:a.xy}),n="highcharts-treegrid-node-"+(m?"expanded":"collapsed"),a.addClass("highcharts-treegrid-node-"+(m?"collapsed":"expanded")).removeClass(n),d||a.css({cursor:"pointer"}),[a,h.labelIcon].forEach(function(b){b.attachedTreeGridEvents||
(w(b.element,"mouseover",function(){a.addClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:"underline"})}),w(b.element,"mouseout",function(){var b=D(f.style)?f.style:{};a.removeClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:b.textDecoration})}),w(b.element,"click",function(){h.toggleCollapse()}),b.attachedTreeGridEvents=!0)}))}});x(l.prototype,{collapse:function(c){var h=this.axis,d=b(h,h.mapOfPosToGridNode[this.pos]);h.setBreaks(d,
z(c,!0))},expand:function(b){var c=this.axis,d=m(c,c.mapOfPosToGridNode[this.pos]);c.setBreaks(d,z(b,!0))},toggleCollapse:function(d){var h=this.axis;var q=h.mapOfPosToGridNode[this.pos];q=c(h,q)?m(h,q):b(h,q);h.setBreaks(q,z(d,!0))}});u.prototype.utils={getNode:g.getNode}});F(l,"parts-gantt/PathfinderAlgorithms.js",[l["parts/Utilities.js"]],function(l){function a(a,f,g){g=g||0;var n=a.length-1;f-=1e-7;for(var p,t;g<=n;)if(p=n+g>>1,t=f-a[p].xMin,0<t)g=p+1;else if(0>t)n=p-1;else return p;return 0<
g?g-1:0}function u(f,n){for(var p=a(f,n.x+1)+1;p--;){var g;if(g=f[p].xMax>=n.x)g=f[p],g=n.x<=g.xMax&&n.x>=g.xMin&&n.y<=g.yMax&&n.y>=g.yMin;if(g)return p}return-1}function g(a){var f=[];if(a.length){f.push("M",a[0].start.x,a[0].start.y);for(var p=0;p<a.length;++p)f.push("L",a[p].end.x,a[p].end.y)}return f}function r(a,f){a.yMin=x(a.yMin,f.yMin);a.yMax=B(a.yMax,f.yMax);a.xMin=x(a.xMin,f.xMin);a.xMax=B(a.xMax,f.xMax)}var I=l.extend,D=l.pick,B=Math.min,x=Math.max,f=Math.abs;return{straight:function(a,
f){return{path:["M",a.x,a.y,"L",f.x,f.y],obstacles:[{start:a,end:f}]}},simpleConnect:I(function(a,n,r){function p(b,c,d,a,e){b={x:b.x,y:b.y};b[c]=d[a||c]+(e||0);return b}function x(b,c,d){var a=f(c[d]-b[d+"Min"])>f(c[d]-b[d+"Max"]);return p(c,d,b,d+(a?"Max":"Min"),a?1:-1)}var t=[],e=D(r.startDirectionX,f(n.x-a.x)>f(n.y-a.y))?"x":"y",k=r.chartObstacles,A=u(k,a);r=u(k,n);if(-1<r){var d=k[r];r=x(d,n,e);d={start:r,end:n};var c=r}else c=n;-1<A&&(k=k[A],r=x(k,a,e),t.push({start:a,end:r}),r[e]>=a[e]===r[e]>=
c[e]&&(e="y"===e?"x":"y",n=a[e]<n[e],t.push({start:r,end:p(r,e,k,e+(n?"Max":"Min"),n?1:-1)}),e="y"===e?"x":"y"));a=t.length?t[t.length-1].end:a;r=p(a,e,c);t.push({start:a,end:r});e=p(r,"y"===e?"x":"y",c);t.push({start:r,end:e});t.push(d);return{path:g(t),obstacles:t}},{requiresObstacles:!0}),fastAvoid:I(function(p,n,l){function z(b,c,h){var d,m=b.x<c.x?1:-1;if(b.x<c.x){var q=b;var e=c}else q=c,e=b;if(b.y<c.y){var y=b;var k=c}else y=c,k=b;for(d=0>m?B(a(v,e.x),v.length-1):0;v[d]&&(0<m&&v[d].xMin<=e.x||
0>m&&v[d].xMax>=q.x);){if(v[d].xMin<=e.x&&v[d].xMax>=q.x&&v[d].yMin<=k.y&&v[d].yMax>=y.y)return h?{y:b.y,x:b.x<c.x?v[d].xMin-1:v[d].xMax+1,obstacle:v[d]}:{x:b.x,y:b.y<c.y?v[d].yMin-1:v[d].yMax+1,obstacle:v[d]};d+=m}return c}function w(b,c,h,d,a){var m=a.soft,q=a.hard,e=d?"x":"y",k={x:c.x,y:c.y},y={x:c.x,y:c.y};a=b[e+"Max"]>=m[e+"Max"];m=b[e+"Min"]<=m[e+"Min"];var v=b[e+"Max"]>=q[e+"Max"];q=b[e+"Min"]<=q[e+"Min"];var G=f(b[e+"Min"]-c[e]),g=f(b[e+"Max"]-c[e]);h=10>f(G-g)?c[e]<h[e]:g<G;y[e]=b[e+"Min"];
k[e]=b[e+"Max"];b=z(c,y,d)[e]!==y[e];c=z(c,k,d)[e]!==k[e];h=b?c?h:!0:c?!1:h;h=m?a?h:!0:a?!1:h;return q?v?h:!0:v?!1:h}function t(b,h,d){if(b.x===h.x&&b.y===h.y)return[];var a=d?"x":"y",q=l.obstacleOptions.margin;var e={soft:{xMin:m,xMax:P,yMin:R,yMax:M},hard:l.hardBounds};var k=u(v,b);if(-1<k){k=v[k];e=w(k,b,h,d,e);r(k,l.hardBounds);var y=d?{y:b.y,x:k[e?"xMax":"xMin"]+(e?1:-1)}:{x:b.x,y:k[e?"yMax":"yMin"]+(e?1:-1)};var f=u(v,y);-1<f&&(f=v[f],r(f,l.hardBounds),y[a]=e?x(k[a+"Max"]-q+1,(f[a+"Min"]+k[a+
"Max"])/2):B(k[a+"Min"]+q-1,(f[a+"Max"]+k[a+"Min"])/2),b.x===y.x&&b.y===y.y?(c&&(y[a]=e?x(k[a+"Max"],f[a+"Max"])+1:B(k[a+"Min"],f[a+"Min"])-1),c=!c):c=!1);b=[{start:b,end:y}]}else a=z(b,{x:d?h.x:b.x,y:d?b.y:h.y},d),b=[{start:b,end:{x:a.x,y:a.y}}],a[d?"x":"y"]!==h[d?"x":"y"]&&(e=w(a.obstacle,a,h,!d,e),r(a.obstacle,l.hardBounds),e={x:d?a.x:a.obstacle[e?"xMax":"xMin"]+(e?1:-1),y:d?a.obstacle[e?"yMax":"yMin"]+(e?1:-1):a.y},d=!d,b=b.concat(t({x:a.x,y:a.y},e,d)));return b=b.concat(t(b[b.length-1].end,h,
!d))}function e(b,c,h){var d=B(b.xMax-c.x,c.x-b.xMin)<B(b.yMax-c.y,c.y-b.yMin);h=w(b,c,h,d,{soft:l.hardBounds,hard:l.hardBounds});return d?{y:c.y,x:b[h?"xMax":"xMin"]+(h?1:-1)}:{x:c.x,y:b[h?"yMax":"yMin"]+(h?1:-1)}}var k=D(l.startDirectionX,f(n.x-p.x)>f(n.y-p.y)),A=k?"x":"y",d=[],c=!1,b=l.obstacleMetrics,m=B(p.x,n.x)-b.maxWidth-10,P=x(p.x,n.x)+b.maxWidth+10,R=B(p.y,n.y)-b.maxHeight-10,M=x(p.y,n.y)+b.maxHeight+10,v=l.chartObstacles;var h=a(v,m);b=a(v,P);v=v.slice(h,b+1);if(-1<(b=u(v,n))){var q=e(v[b],
n,p);d.push({end:n,start:q});n=q}for(;-1<(b=u(v,n));)h=0>n[A]-p[A],q={x:n.x,y:n.y},q[A]=v[b][h?A+"Max":A+"Min"]+(h?1:-1),d.push({end:n,start:q}),n=q;p=t(p,n,k);p=p.concat(d.reverse());return{path:g(p),obstacles:p}},{requiresObstacles:!0})}});F(l,"parts-gantt/ArrowSymbols.js",[l["parts/Globals.js"]],function(l){l.SVGRenderer.prototype.symbols.arrow=function(a,l,g,r){return["M",a,l+r/2,"L",a+g,l,"L",a,l+r/2,"L",a+g,l+r]};l.SVGRenderer.prototype.symbols["arrow-half"]=function(a,u,g,r){return l.SVGRenderer.prototype.symbols.arrow(a,
u,g/2,r)};l.SVGRenderer.prototype.symbols["triangle-left"]=function(a,l,g,r){return["M",a+g,l,"L",a,l+r/2,"L",a+g,l+r,"Z"]};l.SVGRenderer.prototype.symbols["arrow-filled"]=l.SVGRenderer.prototype.symbols["triangle-left"];l.SVGRenderer.prototype.symbols["triangle-left-half"]=function(a,u,g,r){return l.SVGRenderer.prototype.symbols["triangle-left"](a,u,g/2,r)};l.SVGRenderer.prototype.symbols["arrow-filled-half"]=l.SVGRenderer.prototype.symbols["triangle-left-half"]});F(l,"parts-gantt/Pathfinder.js",
[l["parts/Globals.js"],l["parts/Point.js"],l["parts/Utilities.js"],l["parts-gantt/PathfinderAlgorithms.js"]],function(l,a,w,g){function r(c){var b=c.shapeArgs;return b?{xMin:b.x,xMax:b.x+b.width,yMin:b.y,yMax:b.y+b.height}:(b=c.graphic&&c.graphic.getBBox())?{xMin:c.plotX-b.width/2,xMax:c.plotX+b.width/2,yMin:c.plotY-b.height/2,yMax:c.plotY+b.height/2}:null}function u(c){for(var b=c.length,a=0,e,k,f=[],v=function(b,c,a){a=t(a,10);var h=b.yMax+a>c.yMin-a&&b.yMin-a<c.yMax+a,m=b.xMax+a>c.xMin-a&&b.xMin-
a<c.xMax+a,e=h?b.xMin>c.xMax?b.xMin-c.xMax:c.xMin-b.xMax:Infinity,q=m?b.yMin>c.yMax?b.yMin-c.yMax:c.yMin-b.yMax:Infinity;return m&&h?a?v(b,c,Math.floor(a/2)):Infinity:d(e,q)};a<b;++a)for(e=a+1;e<b;++e)k=v(c[a],c[e]),80>k&&f.push(k);f.push(80);return A(Math.floor(f.sort(function(b,c){return b-c})[Math.floor(f.length/10)]/2-1),1)}function D(c,b,d){this.init(c,b,d)}function B(c){this.init(c)}function x(c){if(c.options.pathfinder||c.series.reduce(function(b,c){c.options&&E(!0,c.options.connectors=c.options.connectors||
{},c.options.pathfinder);return b||c.options&&c.options.pathfinder},!1))E(!0,c.options.connectors=c.options.connectors||{},c.options.pathfinder),n('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}"";var f=w.addEvent,p=w.defined,n=w.error,z=w.extend,E=w.merge,C=w.objectEach,t=w.pick,e=w.splat,k=l.deg2rad,A=Math.max,d=Math.min;z(l.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,
lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});D.prototype={init:function(c,b,d){this.fromPoint=c;this.toPoint=b;this.options=d;this.chart=c.series.chart;this.pathfinder=this.chart.pathfinder},renderPath:function(c,b,d){var a=this.chart,e=a.styledMode,m=a.pathfinder,k=!a.options.chart.forExport&&!1!==d,h=this.graphics&&this.graphics.path;m.group||(m.group=a.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(a.seriesGroup));m.group.translate(a.plotLeft,
a.plotTop);h&&h.renderer||(h=a.renderer.path().add(m.group),e||h.attr({opacity:0}));h.attr(b);c={d:c};e||(c.opacity=1);h[k?"animate":"attr"](c,d);this.graphics=this.graphics||{};this.graphics.path=h},addMarker:function(c,b,d){var a=this.fromPoint.series.chart,e=a.pathfinder;a=a.renderer;var m="start"===c?this.fromPoint:this.toPoint,f=m.getPathfinderAnchorPoint(b);if(b.enabled){d="start"===c?{x:d[4],y:d[5]}:{x:d[d.length-5],y:d[d.length-4]};d=m.getRadiansToVector(d,f);f=m.getMarkerVector(d,b.radius,
f);d=-d/k;if(b.width&&b.height){var h=b.width;var q=b.height}else h=q=2*b.radius;this.graphics=this.graphics||{};f={x:f.x-h/2,y:f.y-q/2,width:h,height:q,rotation:d,rotationOriginX:f.x,rotationOriginY:f.y};this.graphics[c]?this.graphics[c].animate(f):(this.graphics[c]=a.symbol(b.symbol).addClass("highcharts-point-connecting-path-"+c+"-marker").attr(f).add(e.group),a.styledMode||this.graphics[c].attr({fill:b.color||this.fromPoint.color,stroke:b.lineColor,"stroke-width":b.lineWidth,opacity:0}).animate({opacity:1},
m.series.options.animation))}},getPath:function(c){var b=this.pathfinder,d=this.chart,a=b.algorithms[c.type],e=b.chartObstacles;if("function"!==typeof a)n('"'+c.type+'" is not a Pathfinder algorithm.');else return a.requiresObstacles&&!e&&(e=b.chartObstacles=b.getChartObstacles(c),d.options.connectors.algorithmMargin=c.algorithmMargin,b.chartObstacleMetrics=b.getObstacleMetrics(e)),a(this.fromPoint.getPathfinderAnchorPoint(c.startMarker),this.toPoint.getPathfinderAnchorPoint(c.endMarker),E({chartObstacles:e,
lineObstacles:b.lineObstacles||[],obstacleMetrics:b.chartObstacleMetrics,hardBounds:{xMin:0,xMax:d.plotWidth,yMin:0,yMax:d.plotHeight},obstacleOptions:{margin:c.algorithmMargin},startDirectionX:b.getAlgorithmStartDirection(c.startMarker)},c))},render:function(){var c=this.fromPoint,b=c.series,a=b.chart,e=a.pathfinder,k=E(a.options.connectors,b.options.connectors,c.options.connectors,this.options),f={};a.styledMode||(f.stroke=k.lineColor||c.color,f["stroke-width"]=k.lineWidth,k.dashStyle&&(f.dashstyle=
k.dashStyle));f["class"]="highcharts-point-connecting-path highcharts-color-"+c.colorIndex;k=E(f,k);p(k.marker.radius)||(k.marker.radius=d(A(Math.ceil((k.algorithmMargin||8)/2)-1,1),5));c=this.getPath(k);a=c.path;c.obstacles&&(e.lineObstacles=e.lineObstacles||[],e.lineObstacles=e.lineObstacles.concat(c.obstacles));this.renderPath(a,f,b.options.animation);this.addMarker("start",E(k.marker,k.startMarker),a);this.addMarker("end",E(k.marker,k.endMarker),a)},destroy:function(){this.graphics&&(C(this.graphics,
function(c){c.destroy()}),delete this.graphics)}};B.prototype={algorithms:g,init:function(c){this.chart=c;this.connections=[];f(c,"redraw",function(){this.pathfinder.update()})},update:function(c){var b=this.chart,d=this,k=d.connections;d.connections=[];b.series.forEach(function(c){c.visible&&!c.options.isInternal&&c.points.forEach(function(c){var h,q=c.options&&c.options.connect&&e(c.options.connect);c.visible&&!1!==c.isInside&&q&&q.forEach(function(e){h=b.get("string"===typeof e?e:e.to);h instanceof
a&&h.series.visible&&h.visible&&!1!==h.isInside&&d.connections.push(new D(c,h,"string"===typeof e?{}:e))})})});for(var f=0,g,v,h=k.length,q=d.connections.length;f<h;++f){v=!1;for(g=0;g<q;++g)if(k[f].fromPoint===d.connections[g].fromPoint&&k[f].toPoint===d.connections[g].toPoint){d.connections[g].graphics=k[f].graphics;v=!0;break}v||k[f].destroy()}delete this.chartObstacles;delete this.lineObstacles;d.renderConnections(c)},renderConnections:function(c){c?this.chart.series.forEach(function(b){var c=
function(){var c=b.chart.pathfinder;(c&&c.connections||[]).forEach(function(c){c.fromPoint&&c.fromPoint.series===b&&c.render()});b.pathfinderRemoveRenderEvent&&(b.pathfinderRemoveRenderEvent(),delete b.pathfinderRemoveRenderEvent)};!1===b.options.animation?c():b.pathfinderRemoveRenderEvent=f(b,"afterAnimate",c)}):this.connections.forEach(function(b){b.render()})},getChartObstacles:function(c){for(var b=[],d=this.chart.series,a=t(c.algorithmMargin,0),e,k=0,f=d.length;k<f;++k)if(d[k].visible&&!d[k].options.isInternal)for(var h=
0,q=d[k].points.length,y;h<q;++h)y=d[k].points[h],y.visible&&(y=r(y))&&b.push({xMin:y.xMin-a,xMax:y.xMax+a,yMin:y.yMin-a,yMax:y.yMax+a});b=b.sort(function(b,c){return b.xMin-c.xMin});p(c.algorithmMargin)||(e=c.algorithmMargin=u(b),b.forEach(function(b){b.xMin-=e;b.xMax+=e;b.yMin-=e;b.yMax+=e}));return b},getObstacleMetrics:function(c){for(var b=0,d=0,a,e,k=c.length;k--;)a=c[k].xMax-c[k].xMin,e=c[k].yMax-c[k].yMin,b<a&&(b=a),d<e&&(d=e);return{maxHeight:d,maxWidth:b}},getAlgorithmStartDirection:function(c){var b=
"top"!==c.verticalAlign&&"bottom"!==c.verticalAlign;return"left"!==c.align&&"right"!==c.align?b?void 0:!1:b?!0:void 0}};l.Connection=D;l.Pathfinder=B;z(a.prototype,{getPathfinderAnchorPoint:function(c){var b=r(this);switch(c.align){case "right":var d="xMax";break;case "left":d="xMin"}switch(c.verticalAlign){case "top":var a="yMin";break;case "bottom":a="yMax"}return{x:d?b[d]:(b.xMin+b.xMax)/2,y:a?b[a]:(b.yMin+b.yMax)/2}},getRadiansToVector:function(c,b){p(b)||(b=r(this),b={x:(b.xMin+b.xMax)/2,y:(b.yMin+
b.yMax)/2});return Math.atan2(b.y-c.y,c.x-b.x)},getMarkerVector:function(c,b,d){var a=2*Math.PI,e=r(this),k=e.xMax-e.xMin,m=e.yMax-e.yMin,h=Math.atan2(m,k),q=!1;k/=2;var f=m/2,g=e.xMin+k;e=e.yMin+f;for(var n=g,p=e,A={},l=1,t=1;c<-Math.PI;)c+=a;for(;c>Math.PI;)c-=a;a=Math.tan(c);c>-h&&c<=h?(t=-1,q=!0):c>h&&c<=Math.PI-h?t=-1:c>Math.PI-h||c<=-(Math.PI-h)?(l=-1,q=!0):l=-1;q?(n+=l*k,p+=t*k*a):(n+=m/(2*a)*l,p+=t*f);d.x!==g&&(n=d.x);d.y!==e&&(p=d.y);A.x=n+b*Math.cos(c);A.y=p-b*Math.sin(c);return A}});l.Chart.prototype.callbacks.push(function(c){!1!==
c.options.connectors.enabled&&(x(c),this.pathfinder=new B(this),this.pathfinder.update(!0))})});F(l,"modules/xrange.src.js",[l["parts/Globals.js"],l["parts/Color.js"],l["parts/Point.js"],l["parts/Utilities.js"]],function(l,a,w,g){var r=a.parse;a=g.addEvent;var u=g.clamp,D=g.correctFloat,B=g.defined,x=g.find,f=g.isNumber,p=g.isObject,n=g.merge,z=g.pick;g=g.seriesType;var E=l.seriesTypes.column,C=l.Axis,t=l.Series;g("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var a=this.point.partialFill;
p(a)&&(a=a.amount);if(f(a)&&0<a)return D(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,animate:l.seriesTypes.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:l.noop,buildKDTree:l.noop,getColumnMetrics:function(){function a(){k.series.forEach(function(d){var c=
d.xAxis;d.xAxis=d.yAxis;d.yAxis=c})}var k=this.chart;a();var f=E.prototype.getColumnMetrics.call(this);a();return f},cropData:function(a,k,f,d){k=t.prototype.cropData.call(this,this.x2Data,k,f,d);k.xData=a.slice(k.start,k.end);return k},findPointIndex:function(a){var e=this.cropped,g=this.cropStart,d=this.points,c=a.id;if(c)var b=(b=x(d,function(b){return b.id===c}))?b.index:void 0;"undefined"===typeof b&&(b=(b=x(d,function(b){return b.x===a.x&&b.x2===a.x2&&!b.touched}))?b.index:void 0);e&&f(b)&&
f(g)&&b>=g&&(b-=g);return b},translatePoint:function(a){var e=this.xAxis,g=this.yAxis,d=this.columnMetrics,c=this.options,b=c.minPointLength||0,m=a.plotX,l=z(a.x2,a.x+(a.len||0)),t=e.translate(l,0,0,0,1);l=Math.abs(t-m);var r=this.chart.inverted,v=z(c.borderWidth,1)%2/2,h=d.offset,q=Math.round(d.width);b&&(b-=l,0>b&&(b=0),m-=b/2,t+=b/2);m=Math.max(m,-10);t=u(t,-10,e.len+10);B(a.options.pointWidth)&&(h-=(Math.ceil(a.options.pointWidth)-q)/2,q=Math.ceil(a.options.pointWidth));c.pointPlacement&&f(a.plotY)&&
g.categories&&(a.plotY=g.translate(a.y,0,1,0,1,c.pointPlacement));a.shapeArgs={x:Math.floor(Math.min(m,t))+v,y:Math.floor(a.plotY+h)+v,width:Math.round(Math.abs(t-m)),height:q,r:this.options.borderRadius};c=a.shapeArgs.x;b=c+a.shapeArgs.width;0>c||b>e.len?(c=u(c,0,e.len),b=u(b,0,e.len),t=b-c,a.dlBox=n(a.shapeArgs,{x:c,width:b-c,centerX:t?t/2:null})):a.dlBox=null;c=a.tooltipPos;b=r?1:0;t=r?0:1;d=this.columnMetrics?this.columnMetrics.offset:-d.width/2;c[b]=u(c[b]+l/2*(e.reversed?-1:1)*(r?-1:1),0,e.len-
1);c[t]=u(c[t]+(r?-1:1)*d,0,g.len-1);if(d=a.partialFill)p(d)&&(d=d.amount),f(d)||(d=0),g=a.shapeArgs,a.partShapeArgs={x:g.x,y:g.y,width:g.width,height:g.height,r:this.options.borderRadius},m=Math.max(Math.round(l*d+a.plotX-m),0),a.clipRectArgs={x:e.reversed?g.x+l-m:g.x,y:g.y,width:m,height:g.height}},translate:function(){E.prototype.translate.apply(this,arguments);this.points.forEach(function(a){this.translatePoint(a)},this)},drawPoint:function(a,k){var e=this.options,d=this.chart.renderer,c=a.graphic,
b=a.shapeType,m=a.shapeArgs,f=a.partShapeArgs,g=a.clipRectArgs,l=a.partialFill,v=e.stacking&&!e.borderRadius,h=a.state,q=e.states[h||"normal"]||{},y="undefined"===typeof h?"attr":k;h=this.pointAttribs(a,h);q=z(this.chart.options.chart.animation,q.animation);if(a.isNull||!1===a.visible)c&&(a.graphic=c.destroy());else{if(c)c.rect[k](m);else a.graphic=c=d.g("point").addClass(a.getClassName()).add(a.group||this.group),c.rect=d[b](n(m)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(c);
f&&(c.partRect?(c.partRect[k](n(f)),c.partialClipRect[k](n(g))):(c.partialClipRect=d.clipRect(g.x,g.y,g.width,g.height),c.partRect=d[b](f).addClass("highcharts-partfill-overlay").add(c).clip(c.partialClipRect)));this.chart.styledMode||(c.rect[k](h,q).shadow(e.shadow,null,v),f&&(p(l)||(l={}),p(e.partialFill)&&(l=n(l,e.partialFill)),a=l.fill||r(h.fill).brighten(-.3).get()||r(a.color||this.color).brighten(-.3).get(),h.fill=a,c.partRect[y](h,q).shadow(e.shadow,null,v)))}},drawPoints:function(){var a=
this,k=a.getAnimationVerb();a.points.forEach(function(e){a.drawPoint(e,k)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var a=this.series;if(a.options.colorByPoint&&!this.options.color){var k=a.options.colors||a.chart.options.colors;var f=this.y%(k?k.length:a.chart.options.chart.colorCount);k=k&&k[f];a.chart.styledMode||(this.color=k);this.options.colorIndex||(this.colorIndex=f)}else this.color||(this.color=
a.color)},init:function(){w.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){w.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},getLabelConfig:function(){var a=w.prototype.getLabelConfig.call(this),k=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=k&&k[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});a(C,"afterGetSeriesExtremes",
function(){var a=this.series,k;if(this.isXAxis){var f=z(this.dataMax,-Number.MAX_VALUE);a.forEach(function(a){a.x2Data&&a.x2Data.forEach(function(c){c>f&&(f=c,k=!0)})});k&&(this.dataMax=f)}});""});F(l,"parts-gantt/GanttSeries.js",[l["parts/Globals.js"],l["parts/Utilities.js"]],function(l,a){var u=a.isNumber,g=a.merge,r=a.pick,I=a.seriesType,D=a.splat,B=l.dateFormat,x=l.seriesTypes.xrange;I("gantt","xrange",{grouping:!1,dataLabels:{enabled:!0},tooltip:{headerFormat:'<span style="font-size: 10px">{series.name}</span><br/>',
pointFormat:null,pointFormatter:function(){var a=this.series,g=a.chart.tooltip,n=a.xAxis,l=a.tooltipOptions.dateTimeLabelFormats,r=n.options.startOfWeek,x=a.tooltipOptions,t=x.xDateFormat;a=this.options.milestone;var e="<b>"+(this.name||this.yCategory)+"</b>";if(x.pointFormat)return this.tooltipFormatter(x.pointFormat);t||(t=D(g.getDateFormat(n.closestPointRange,this.start,r,l))[0]);g=B(t,this.start);n=B(t,this.end);e+="<br/>";return a?e+(g+"<br/>"):e+("Start: "+g+"<br/>End: ")+(n+"<br/>")}},connectors:{type:"simpleConnect",
animation:{reversed:!0},startMarker:{enabled:!0,symbol:"arrow-filled",radius:4,fill:"#fa0",align:"left"},endMarker:{enabled:!1,align:"right"}}},{pointArrayMap:["start","end","y"],keyboardMoveVertical:!1,translatePoint:function(a){x.prototype.translatePoint.call(this,a);if(a.options.milestone){var f=a.shapeArgs;var g=f.height;a.shapeArgs={x:f.x-g/2,y:f.y,width:g,height:g}}},drawPoint:function(a,g){var f=this.options,l=this.chart.renderer,p=a.shapeArgs,r=a.plotY,t=a.graphic,e=a.selected&&"select",k=
f.stacking&&!f.borderRadius;if(a.options.milestone)if(u(r)&&null!==a.y&&!1!==a.visible){p=l.symbols.diamond(p.x,p.y,p.width,p.height);if(t)t[g]({d:p});else a.graphic=l.path(p).addClass(a.getClassName(),!0).add(a.group||this.group);this.chart.styledMode||a.graphic.attr(this.pointAttribs(a,e)).shadow(f.shadow,null,k)}else t&&(a.graphic=t.destroy());else x.prototype.drawPoint.call(this,a,g)},setData:l.Series.prototype.setData,setGanttPointAliases:function(a){function f(f,g){"undefined"!==typeof g&&(a[f]=
g)}f("x",r(a.start,a.x));f("x2",r(a.end,a.x2));f("partialFill",r(a.completed,a.partialFill));f("connect",r(a.dependency,a.connect))}},g(x.prototype.pointClass.prototype,{applyOptions:function(a,p){a=g(a);l.seriesTypes.gantt.prototype.setGanttPointAliases(a);return a=x.prototype.pointClass.prototype.applyOptions.call(this,a,p)},isValid:function(){return("number"===typeof this.start||"number"===typeof this.x)&&("number"===typeof this.end||"number"===typeof this.x2||this.milestone)}}));""});F(l,"parts-gantt/GanttChart.js",
[l["parts/Globals.js"],l["parts/Utilities.js"]],function(l,a){var u=a.isArray,g=a.merge,r=a.splat,I=l.Chart;l.ganttChart=function(a,w,x){var f="string"===typeof a||a.nodeName,p=w.series,n=l.getOptions(),z,B=w;w=arguments[f?1:0];u(w.xAxis)||(w.xAxis=[w.xAxis||{},{}]);w.xAxis=w.xAxis.map(function(a,f){1===f&&(z=0);return g(n.xAxis,{grid:{enabled:!0},opposite:!0,linkedTo:z},a,{type:"datetime"})});w.yAxis=r(w.yAxis||{}).map(function(a){return g(n.yAxis,{grid:{enabled:!0},staticScale:50,reversed:!0,type:a.categories?
a.type:"treegrid"},a)});w.series=null;w=g(!0,{chart:{type:"gantt"},title:{text:null},legend:{enabled:!1}},w,{isGantt:!0});w.series=B.series=p;w.series.forEach(function(a){a.data.forEach(function(a){l.seriesTypes.gantt.prototype.setGanttPointAliases(a)})});return f?new I(a,w,x):new I(w,w)}});F(l,"parts/ScrollbarAxis.js",[l["parts/Globals.js"],l["parts/Utilities.js"]],function(l,a){var w=a.addEvent,g=a.defined,r=a.pick;return function(){function a(){}a.init=function(a,u){w(a,"afterInit",function(){var a=
this;a.options&&a.options.scrollbar&&a.options.scrollbar.enabled&&(a.options.scrollbar.vertical=!a.horiz,a.options.startOnTick=a.options.endOnTick=!1,a.scrollbar=new u(a.chart.renderer,a.options.scrollbar,a.chart),w(a.scrollbar,"changed",function(f){var p=Math.min(r(a.options.min,a.min),a.min,a.dataMin),n=Math.max(r(a.options.max,a.max),a.max,a.dataMax)-p;if(a.horiz&&!a.reversed||!a.horiz&&a.reversed){var x=p+n*this.to;p+=n*this.from}else x=p+n*(1-this.from),p+=n*(1-this.to);r(this.options.liveRedraw,
l.svg&&!l.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===f.DOMType||!g(f.DOMType)?a.setExtremes(p,x,!0,"mousemove"!==f.DOMType,f):this.setRange(this.from,this.to)}))});w(a,"afterRender",function(){var a=Math.min(r(this.options.min,this.min),this.min,r(this.dataMin,this.min)),f=Math.max(r(this.options.max,this.max),this.max,r(this.dataMax,this.max)),l=this.scrollbar,n=this.axisTitleMargin+(this.titleOffset||0),u=this.chart.scrollbarsOffsets,w=this.options.margin||0;l&&(this.horiz?(this.opposite||
(u[1]+=n),l.position(this.left,this.top+this.height+2+u[1]-(this.opposite?w:0),this.width,this.height),this.opposite||(u[1]+=w),n=1):(this.opposite&&(u[0]+=n),l.position(this.left+this.width+2+u[0]-(this.opposite?0:w),this.top,this.width,this.height),this.opposite&&(u[0]+=w),n=0),u[n]+=l.size+l.options.margin,isNaN(a)||isNaN(f)||!g(this.min)||!g(this.max)||this.min===this.max?l.setRange(0,1):(u=(this.min-a)/(f-a),a=(this.max-a)/(f-a),this.horiz&&!this.reversed||!this.horiz&&this.reversed?l.setRange(u,
a):l.setRange(1-a,1-u)))});w(a,"afterGetOffset",function(){var a=this.horiz?2:1,f=this.scrollbar;f&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[a]+=f.size+f.options.margin)})};return a}()});F(l,"parts/Scrollbar.js",[l["parts/Axis.js"],l["parts/Globals.js"],l["parts/ScrollbarAxis.js"],l["parts/Utilities.js"]],function(l,a,w,g){var r=g.addEvent,u=g.correctFloat,D=g.defined,B=g.destroyObjectProperties,x=g.fireEvent,f=g.merge,p=g.pick,n=g.removeEvent;g=a.defaultOptions;var z=a.hasTouch,
E=a.isTouchDevice,C=a.swapXY=function(a,k){var e=a.length;if(k)for(k=0;k<e;k+=3){var d=a[k+1];a[k+1]=a[k+2];a[k+2]=d}return a},t=function(){function a(a,e,d){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=d;
this.options=e;this.renderer=d.renderer;this.init(a,e,d)}a.prototype.addEvents=function(){var a=this.options.inverted?[1,0]:[0,1],e=this.scrollbarButtons,d=this.scrollbarGroup.element,c=this.track.element,b=this.mouseDownHandler.bind(this),m=this.mouseMoveHandler.bind(this),f=this.mouseUpHandler.bind(this);a=[[e[a[0]].element,"click",this.buttonToMinClick.bind(this)],[e[a[1]].element,"click",this.buttonToMaxClick.bind(this)],[c,"click",this.trackClick.bind(this)],[d,"mousedown",b],[d.ownerDocument,
"mousemove",m],[d.ownerDocument,"mouseup",f]];z&&a.push([d,"touchstart",b],[d.ownerDocument,"touchmove",m],[d.ownerDocument,"touchend",f]);a.forEach(function(a){r.apply(null,a)});this._events=a};a.prototype.buttonToMaxClick=function(a){var e=(this.to-this.from)*p(this.options.step,.2);this.updatePosition(this.from+e,this.to+e);x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.buttonToMinClick=function(a){var e=u(this.to-this.from)*p(this.options.step,.2);this.updatePosition(u(this.from-
e),u(this.to-e));x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.cursorToScrollbarPosition=function(a){var e=this.options;e=e.minWidth>this.calculatedWidth?e.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-e),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-e)}};a.prototype.destroy=function(){var a=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(a){this[a]&&
this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,B(a.scrollbarButtons))};a.prototype.drawScrollbarButton=function(a){var e=this.renderer,d=this.scrollbarButtons,c=this.options,b=this.size;var m=e.g().add(this.group);d.push(m);m=e.rect().addClass("highcharts-scrollbar-button").add(m);this.chart.styledMode||m.attr({stroke:c.buttonBorderColor,"stroke-width":c.buttonBorderWidth,fill:c.buttonBackgroundColor});m.attr(m.crisp({x:-.5,y:-.5,width:b+1,height:b+1,
r:c.buttonBorderRadius},m.strokeWidth()));m=e.path(C(["M",b/2+(a?-1:1),b/2-3,"L",b/2+(a?-1:1),b/2+3,"L",b/2+(a?2:-2),b/2],c.vertical)).addClass("highcharts-scrollbar-arrow").add(d[a]);this.chart.styledMode||m.attr({fill:c.buttonArrowColor})};a.prototype.init=function(e,g,d){this.scrollbarButtons=[];this.renderer=e;this.userOptions=g;this.options=f(a.defaultOptions,g);this.chart=d;this.size=p(this.options.size,this.options.height);g.enabled&&(this.render(),this.addEvents())};a.prototype.mouseDownHandler=
function(a){a=this.chart.pointer.normalize(a);a=this.cursorToScrollbarPosition(a);this.chartX=a.chartX;this.chartY=a.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};a.prototype.mouseMoveHandler=function(a){var e=this.chart.pointer.normalize(a),d=this.options.vertical?"chartY":"chartX",c=this.initPositions||[];!this.grabbedCenter||a.touches&&0===a.touches[0][d]||(e=this.cursorToScrollbarPosition(e)[d],d=this[d],d=e-d,this.hasDragged=!0,this.updatePosition(c[0]+d,c[1]+d),this.hasDragged&&
x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a}))};a.prototype.mouseUpHandler=function(a){this.hasDragged&&x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};a.prototype.position=function(a,e,d,c){var b=this.options.vertical,m=0,f=this.rendered?"animate":"attr";this.x=a;this.y=e+this.trackBorderWidth;this.width=d;this.xOffset=this.height=c;this.yOffset=
m;b?(this.width=this.yOffset=d=m=this.size,this.xOffset=e=0,this.barWidth=c-2*d,this.x=a+=this.options.margin):(this.height=this.xOffset=c=e=this.size,this.barWidth=d-2*c,this.y+=this.options.margin);this.group[f]({translateX:a,translateY:this.y});this.track[f]({width:d,height:c});this.scrollbarButtons[1][f]({translateX:b?0:d-e,translateY:b?c-m:0})};a.prototype.removeEvents=function(){this._events.forEach(function(a){n.apply(null,a)});this._events.length=0};a.prototype.render=function(){var a=this.renderer,
e=this.options,d=this.size,c=this.chart.styledMode,b;this.group=b=a.g("scrollbar").attr({zIndex:e.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:e.trackBorderRadius||0,height:d,width:d}).add(b);c||this.track.attr({fill:e.trackBackgroundColor,stroke:e.trackBorderColor,"stroke-width":e.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(b);this.scrollbar=
a.rect().addClass("highcharts-scrollbar-thumb").attr({height:d,width:d,r:e.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(C(["M",-3,d/4,"L",-3,2*d/3,"M",0,d/4,"L",0,2*d/3,"M",3,d/4,"L",3,2*d/3],e.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);c||(this.scrollbar.attr({fill:e.barBackgroundColor,stroke:e.barBorderColor,"stroke-width":e.barBorderWidth}),this.scrollbarRifles.attr({stroke:e.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=
this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};a.prototype.setRange=function(a,e){var d=this.options,c=d.vertical,b=d.minWidth,m=this.barWidth,f,k=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(D(m)){a=Math.max(a,0);var g=Math.ceil(m*a);this.calculatedWidth=f=u(m*Math.min(e,1)-g);f<b&&(g=(m-b+f)*a,f=b);b=Math.floor(g+
this.xOffset+this.yOffset);m=f/2-.5;this.from=a;this.to=e;c?(this.scrollbarGroup[k]({translateY:b}),this.scrollbar[k]({height:f}),this.scrollbarRifles[k]({translateY:m}),this.scrollbarTop=b,this.scrollbarLeft=0):(this.scrollbarGroup[k]({translateX:b}),this.scrollbar[k]({width:f}),this.scrollbarRifles[k]({translateX:m}),this.scrollbarLeft=b,this.scrollbarTop=0);12>=f?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===d.showFull&&(0>=a&&1<=e?this.group.hide():this.group.show());this.rendered=
!0}};a.prototype.trackClick=function(a){var e=this.chart.pointer.normalize(a),d=this.to-this.from,c=this.y+this.scrollbarTop,b=this.x+this.scrollbarLeft;this.options.vertical&&e.chartY>c||!this.options.vertical&&e.chartX>b?this.updatePosition(this.from+d,this.to+d):this.updatePosition(this.from-d,this.to-d);x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.update=function(a){this.destroy();this.init(this.chart.renderer,f(!0,this.options,a),this.chart)};a.prototype.updatePosition=
function(a,e){1<e&&(a=u(1-u(e-a)),e=1);0>a&&(e=u(e-a),a=0);this.from=a;this.to=e};a.defaultOptions={height:E?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};return a}();a.Scrollbar||
(g.scrollbar=f(!0,t.defaultOptions,g.scrollbar),a.Scrollbar=t,w.init(l,t));return a.Scrollbar});F(l,"parts/RangeSelector.js",[l["parts/Globals.js"],l["parts/Utilities.js"]],function(l,a){function u(a){this.init(a)}var g=a.addEvent,r=a.createElement,F=a.css,D=a.defined,B=a.destroyObjectProperties,x=a.discardElement,f=a.extend,p=a.fireEvent,n=a.isNumber,z=a.merge,E=a.objectEach,C=a.pick,t=a.pInt,e=a.splat,k=l.Axis;a=l.Chart;var A=l.defaultOptions;f(A,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,
height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});A.lang=z(A.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});u.prototype={clickButton:function(a,c){var b=this.chart,d=this.buttonOptions[a],f=b.xAxis[0],l=b.scroller&&b.scroller.getUnionExtremes()||f||{},p=l.dataMin,v=l.dataMax,h=f&&Math.round(Math.min(f.max,C(v,f.max))),q=d.type;l=d._range;var y,t=
d.dataGrouping;if(null!==p&&null!==v){b.fixedRange=l;t&&(this.forcedDataGrouping=!0,k.prototype.setDataGrouping.call(f||{chart:this.chart},t,!1),this.frozenStates=d.preserveDataGrouping);if("month"===q||"year"===q)if(f){q={range:d,max:h,chart:b,dataMin:p,dataMax:v};var r=f.minFromRange.call(q);n(q.newMax)&&(h=q.newMax)}else l=d;else if(l)r=Math.max(h-l,p),h=Math.min(r+l,v);else if("ytd"===q)if(f)"undefined"===typeof v&&(p=Number.MAX_VALUE,v=Number.MIN_VALUE,b.series.forEach(function(a){a=a.xData;
p=Math.min(a[0],p);v=Math.max(a[a.length-1],v)}),c=!1),h=this.getYTDExtremes(v,p,b.time.useUTC),r=y=h.min,h=h.max;else{this.deferredYTDClick=a;return}else"all"===q&&f&&(r=p,h=v);r+=d._offsetMin;h+=d._offsetMax;this.setSelected(a);if(f)f.setExtremes(r,h,C(c,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:d});else{var H=e(b.options.xAxis)[0];var u=H.range;H.range=l;var J=H.min;H.min=y;g(b,"load",function(){H.range=u;H.min=J})}}},setSelected:function(a){this.selected=this.options.selected=
a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var c=this,b=a.options.rangeSelector,d=b.buttons||[].concat(c.defaultButtons),e=b.selected,f=function(){var a=c.minInput,b=c.maxInput;a&&a.blur&&p(a,"blur");b&&b.blur&&p(b,"blur")};c.chart=a;c.options=b;c.buttons=[];c.buttonOptions=d;this.unMouseDown=g(a.container,"mousedown",f);this.unResize=
g(a,"resize",f);d.forEach(c.computeButtonRange);"undefined"!==typeof e&&d[e]&&this.clickButton(e,!1);g(a,"load",function(){a.xAxis&&a.xAxis[0]&&g(a.xAxis[0],"setExtremes",function(b){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==b.trigger&&"updatedData"!==b.trigger&&c.forcedDataGrouping&&!c.frozenStates&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this,c=this.chart,b=c.xAxis[0],e=Math.round(b.max-b.min),f=!b.hasVisibleSeries,g=c.scroller&&c.scroller.getUnionExtremes()||
b,k=g.dataMin,l=g.dataMax;c=a.getYTDExtremes(l,k,c.time.useUTC);var h=c.min,q=c.max,y=a.selected,p=n(y),r=a.options.allButtonsEnabled,t=a.buttons;a.buttonOptions.forEach(function(c,d){var m=c._range,g=c.type,v=c.count||1,n=t[d],G=0,H=c._offsetMax-c._offsetMin;c=d===y;var u=m>l-k,J=m<b.minRange,K=!1,w=!1;m=m===e;("month"===g||"year"===g)&&e+36E5>=864E5*{month:28,year:365}[g]*v-H&&e-36E5<=864E5*{month:31,year:366}[g]*v+H?m=!0:"ytd"===g?(m=q-h+H===e,K=!c):"all"===g&&(m=b.max-b.min>=l-k,w=!c&&p&&m);g=
!r&&(u||J||w||f);v=c&&m||m&&!p&&!K||c&&a.frozenStates;g?G=3:v&&(p=!0,G=2);n.state!==G&&(n.setState(G),0===G&&y===d&&a.setSelected(null))})},computeButtonRange:function(a){var c=a.type,b=a.count||1,d={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(d[c])a._range=d[c]*b;else if("month"===c||"year"===c)a._range=864E5*{month:30,year:365}[c]*b;a._offsetMin=C(a.offsetMin,0);a._offsetMax=C(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,c){var b=this.chart.options.rangeSelector,
d=this.chart.time,e=this[a+"Input"];D(c)&&(e.previousValue=e.HCTime,e.HCTime=c);e.value=d.dateFormat(b.inputEditDateFormat||"%Y-%m-%d",e.HCTime);this[a+"DateBox"].attr({text:d.dateFormat(b.inputDateFormat||"%b %e, %Y",e.HCTime)})},showInput:function(a){var c=this.inputGroup,b=this[a+"DateBox"];F(this[a+"Input"],{left:c.translateX+b.x+"px",top:c.translateY+"px",width:b.width-2+"px",height:b.height-2+"px",border:"2px solid silver"})},hideInput:function(a){F(this[a+"Input"],{border:0,width:"1px",height:"1px"});
this.setInputValue(a)},drawInput:function(a){function c(){var a=q.value,c=(k.inputDateParser||Date.parse)(a),e=d.xAxis[0],f=d.scroller&&d.scroller.xAxis?d.scroller.xAxis:e,m=f.dataMin;f=f.dataMax;c!==q.previousValue&&(q.previousValue=c,n(c)||(c=a.split("-"),c=Date.UTC(t(c[0]),t(c[1])-1,t(c[2]))),n(c)&&(d.time.useUTC||(c+=6E4*(new Date).getTimezoneOffset()),h?c>b.maxInput.HCTime?c=void 0:c<m&&(c=m):c<b.minInput.HCTime?c=void 0:c>f&&(c=f),"undefined"!==typeof c&&e.setExtremes(h?c:e.min,h?e.max:c,void 0,
void 0,{trigger:"rangeSelectorInput"})))}var b=this,d=b.chart,e=d.renderer.style||{},g=d.renderer,k=d.options.rangeSelector,v=b.div,h="min"===a,q,y,p=this.inputGroup;this[a+"Label"]=y=g.label(A.lang[h?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(p);p.offset+=y.width+5;this[a+"DateBox"]=g=g.label("",p.offset).addClass("highcharts-range-input").attr({padding:2,width:k.inputBoxWidth||90,height:k.inputBoxHeight||17,"text-align":"center"}).on("click",
function(){b.showInput(a);b[a+"Input"].focus()});d.styledMode||g.attr({stroke:k.inputBoxBorderColor||"#cccccc","stroke-width":1});g.add(p);p.offset+=g.width+(h?10:0);this[a+"Input"]=q=r("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:d.plotTop+"px"},v);d.styledMode||(y.css(z(e,k.labelStyle)),g.css(z({color:"#333333"},e,k.inputStyle)),F(q,f({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:e.fontSize,fontFamily:e.fontFamily,top:"-9999em"},
k.inputStyle)));q.onfocus=function(){b.showInput(a)};q.onblur=function(){q===l.doc.activeElement&&c();b.hideInput(a);q.blur()};q.onchange=c;q.onkeypress=function(a){13===a.keyCode&&c()}},getPosition:function(){var a=this.chart,c=a.options.rangeSelector;a="top"===c.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+c.buttonPosition.y,inputTop:a+c.inputPosition.y-10}},getYTDExtremes:function(a,c,b){var d=this.chart.time,e=new d.Date(a),f=d.get("FullYear",e);b=b?d.Date.UTC(f,0,1):+new d.Date(f,
0,1);c=Math.max(c||0,b);e=e.getTime();return{max:Math.min(a||e,e),min:c}},render:function(a,c){var b=this,d=b.chart,e=d.renderer,f=d.container,g=d.options,k=g.exporting&&!1!==g.exporting.enabled&&g.navigation&&g.navigation.buttonOptions,h=A.lang,q=b.div,l=g.rangeSelector,p=C(g.chart.style&&g.chart.style.zIndex,0)+1;g=l.floating;var n=b.buttons;q=b.inputGroup;var t=l.buttonTheme,u=l.buttonPosition,J=l.inputPosition,w=l.inputEnabled,x=t&&t.states,z=d.plotLeft,L=b.buttonGroup,B,D=b.options.verticalAlign,
E=d.legend,F=E&&E.options,I=u.y,Q=J.y,S=d.hasLoaded,T=S?"animate":"attr",O=0,N=0;if(!1!==l.enabled){b.rendered||(b.group=B=e.g("range-selector-group").attr({zIndex:7}).add(),b.buttonGroup=L=e.g("range-selector-buttons").add(B),b.zoomText=e.text(h.rangeSelectorZoom,0,15).add(L),d.styledMode||(b.zoomText.css(l.labelStyle),t["stroke-width"]=C(t["stroke-width"],0)),b.buttonOptions.forEach(function(a,c){n[c]=e.button(a.text,0,0,function(h){var d=a.events&&a.events.click,e;d&&(e=d.call(a,h));!1!==e&&b.clickButton(c);
b.isActive=!0},t,x&&x.hover,x&&x.select,x&&x.disabled).attr({"text-align":"center"}).add(L)}),!1!==w&&(b.div=q=r("div",null,{position:"relative",height:0,zIndex:p}),f.parentNode.insertBefore(q,f),b.inputGroup=q=e.g("input-group").add(B),q.offset=0,b.drawInput("min"),b.drawInput("max")));b.zoomText[T]({x:C(z+u.x,z)});var U=C(z+u.x,z)+b.zoomText.getBBox().width+5;b.buttonOptions.forEach(function(a,b){n[b][T]({x:U});U+=n[b].width+C(l.buttonSpacing,5)});z=d.plotLeft-d.spacing[3];b.updateButtonStates();
k&&this.titleCollision(d)&&"top"===D&&"right"===u.align&&u.y+L.getBBox().height-12<(k.y||0)+k.height&&(O=-40);f=u.x-d.spacing[3];"right"===u.align?f+=O-z:"center"===u.align&&(f-=z/2);L.align({y:u.y,width:L.getBBox().width,align:u.align,x:f},!0,d.spacingBox);b.group.placed=S;b.buttonGroup.placed=S;!1!==w&&(O=k&&this.titleCollision(d)&&"top"===D&&"right"===J.align&&J.y-q.getBBox().height-12<(k.y||0)+k.height+d.spacing[0]?-40:0,"left"===J.align?f=z:"right"===J.align&&(f=-Math.max(d.axisOffset[1],-O)),
q.align({y:J.y,width:q.getBBox().width,align:J.align,x:J.x+f-2},!0,d.spacingBox),k=q.alignAttr.translateX+q.alignOptions.x-O+q.getBBox().x+2,f=q.alignOptions.width,h=L.alignAttr.translateX+L.getBBox().x,z=L.getBBox().width+20,(J.align===u.align||h+z>k&&k+f>h&&I<Q+q.getBBox().height)&&q.attr({translateX:q.alignAttr.translateX+(d.axisOffset[1]>=-O?0:-O),translateY:q.alignAttr.translateY+L.getBBox().height+10}),b.setInputValue("min",a),b.setInputValue("max",c),b.inputGroup.placed=S);b.group.align({verticalAlign:D},
!0,d.spacingBox);a=b.group.getBBox().height+20;c=b.group.alignAttr.translateY;"bottom"===D&&(E=F&&"bottom"===F.verticalAlign&&F.enabled&&!F.floating?E.legendHeight+C(F.margin,10):0,a=a+E-20,N=c-a-(g?0:l.y)-(d.titleOffset?d.titleOffset[2]:0)-10);if("top"===D)g&&(N=0),d.titleOffset&&d.titleOffset[0]&&(N=d.titleOffset[0]),N+=d.margin[0]-d.spacing[0]||0;else if("middle"===D)if(Q===I)N=0>Q?c+void 0:c;else if(Q||I)N=0>Q||0>I?N-Math.min(Q,I):c-a+NaN;b.group.translate(l.x,l.y+Math.floor(N));!1!==w&&(b.minInput.style.marginTop=
b.group.translateY+"px",b.maxInput.style.marginTop=b.group.translateY+"px");b.rendered=!0}},getHeight:function(){var a=this.options,c=this.group,b=a.y,e=a.buttonPosition.y,f=a.inputPosition.y;if(a.height)return a.height;a=c?c.getBBox(!0).height+13+b:0;c=Math.min(f,e);if(0>f&&0>e||0<f&&0<e)a+=Math.abs(c);return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var c=this.chart;z(!0,c.options.rangeSelector,a);this.destroy();this.init(c);c.rangeSelector.render()},
destroy:function(){var a=this,c=a.minInput,b=a.maxInput;a.unMouseDown();a.unResize();B(a.buttons);c&&(c.onfocus=c.onblur=c.onchange=null);b&&(b.onfocus=b.onblur=b.onchange=null);E(a,function(b,c){b&&"chart"!==c&&(b.destroy?b.destroy():b.nodeType&&x(this[c]));b!==u.prototype[c]&&(a[c]=null)},this)}};k.prototype.minFromRange=function(){var a=this.range,c=a.type,b=this.max,e=this.chart.time,f=function(a,b){var h="year"===c?"FullYear":"Month",d=new e.Date(a),f=e.get(h,d);e.set(h,d,f+b);f===e.get(h,d)&&
e.set("Date",d,0);return d.getTime()-a};if(n(a)){var g=b-a;var k=a}else g=b+f(b,-a.count),this.chart&&(this.chart.fixedRange=b-g);var l=C(this.dataMin,Number.MIN_VALUE);n(g)||(g=l);g<=l&&(g=l,"undefined"===typeof k&&(k=f(g,a.count)),this.newMax=Math.min(g+k,this.dataMax));n(b)||(g=void 0);return g};l.RangeSelector||(g(a,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new u(this))}),g(a,"beforeRender",function(){var a=this.axes,c=this.rangeSelector;c&&(n(c.deferredYTDClick)&&
(c.clickButton(c.deferredYTDClick),delete c.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),c.render(),a=c.options.verticalAlign,c.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),g(a,"update",function(a){var c=a.options.rangeSelector;a=this.rangeSelector;var b=this.extraBottomMargin,d=this.extraTopMargin;c&&c.enabled&&!D(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new u(this));this.extraTopMargin=
this.extraBottomMargin=!1;a&&(a.render(),c=c&&c.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===c?this.extraBottomMargin=!0:"middle"!==c&&(this.extraTopMargin=!0)),this.extraBottomMargin!==b||this.extraTopMargin!==d)&&(this.isDirtyBox=!0)}),g(a,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),g(a,"getMargins",function(){var a=
this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),a.prototype.callbacks.push(function(a){function c(){b=a.xAxis[0].getExtremes();n(b.min)&&d.render(b.min,b.max)}var b,d=a.rangeSelector;if(d){var e=g(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)});var f=g(a,"redraw",c);c()}g(a,"destroy",function(){d&&(f(),e())})}),l.RangeSelector=u)});F(l,"parts/Navigator.js",[l["parts/Globals.js"],l["parts/Color.js"],l["parts/Scrollbar.js"],
l["parts/Utilities.js"]],function(l,a,w,g){a=a.parse;var r=g.addEvent,u=g.clamp,D=g.correctFloat,B=g.defined,x=g.destroyObjectProperties,f=g.erase,p=g.extend,n=g.find,z=g.isArray,E=g.isNumber,C=g.merge,t=g.pick,e=g.removeEvent,k=g.splat,A=l.Axis;g=l.Chart;var d=l.defaultOptions,c=l.hasTouch,b=l.isTouchDevice,m=l.Series,F=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];b=[].filter.call(b,E);if(b.length)return Math[a].apply(0,b)};var R="undefined"===typeof l.seriesTypes.areaspline?
"line":"areaspline";p(d,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:a("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:R,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,
2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},
yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});l.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,e){a=e.width/2;b=Math.round(a/3)+.5;e=e.height;return["M",-a-1,.5,"L",a,.5,"L",a,e+.5,"L",-a-1,e+.5,"L",-a-1,.5,"M",-b,4,"L",-b,e-3,"M",b-1,4,"L",b-1,e-3]};A.prototype.toFixedRange=function(a,b,c,d){var h=this.chart&&this.chart.fixedRange,
e=(this.pointRange||0)/2;a=t(c,this.translate(a,!0,!this.horiz));b=t(d,this.translate(b,!0,!this.horiz));var f=h&&(b-a)/h;B(c)||(a=D(a+e));B(d)||(b=D(b-e));.7<f&&1.3>f&&(d?a=b-h:b=a+h);E(a)&&E(b)||(a=b=void 0);return{min:a,max:b}};var M=function(){function a(a){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=
this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(a)}a.prototype.drawHandle=function(a,b,c,d){var h=this.navigatorOptions.handles.height;this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-h)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-h/2-1)})};a.prototype.drawOutline=function(a,b,c,d){var h=this.navigatorOptions.maskInside,e=this.outline.strokeWidth(),
f=e/2;e=e%2/2;var q=this.outlineHeight,g=this.scrollbarHeight,k=this.size,l=this.left-g,m=this.top;c?(l-=f,c=m+b+e,b=m+a+e,a=["M",l+q,m-g-e,"L",l+q,c,"L",l,c,"L",l,b,"L",l+q,b,"L",l+q,m+k+g].concat(h?["M",l+q,c-f,"L",l+q,b+f]:[])):(a+=l+g-e,b+=l+g-e,m+=f,a=["M",l,m,"L",a,m,"L",a,m+q,"L",b,m+q,"L",b,m,"L",l+k+2*g,m].concat(h?["M",a-f,m,"L",b+f,m]:[]));this.outline[d]({d:a})};a.prototype.drawMasks=function(a,b,c,d){var h=this.left,e=this.top,f=this.height;if(c){var q=[h,h,h];var g=[e,e+a,e+b];var k=
[f,f,f];var l=[a,b-a,this.size-b]}else q=[h,h+a,h+b],g=[e,e,e],k=[a,b-a,this.size-b],l=[f,f,f];this.shades.forEach(function(a,b){a[d]({x:q[b],y:g[b],width:k[b],height:l[b]})})};a.prototype.renderElements=function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,e=d.renderer,f,g={cursor:d.inverted?"ns-resize":"ew-resize"};a.navigatorGroup=f=e.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,h){a.shades[h]=e.rect().addClass("highcharts-navigator-mask"+
(1===h?"-inside":"-outside")).add(f);d.styledMode||a.shades[h].attr({fill:c?b.maskFill:"rgba(0,0,0,0)"}).css(1===h&&g)});a.outline=e.path().addClass("highcharts-navigator-outline").add(f);d.styledMode||a.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});b.handles.enabled&&[0,1].forEach(function(c){b.handles.inverted=d.inverted;a.handles[c]=e.symbol(b.handles.symbols[c],-b.handles.width/2-1,0,b.handles.width,b.handles.height,b.handles);a.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+
["left","right"][c]).add(f);if(!d.styledMode){var h=b.handles;a.handles[c].attr({fill:h.backgroundColor,stroke:h.borderColor,"stroke-width":h.lineWidth}).css(g)}})};a.prototype.update=function(a){(this.series||[]).forEach(function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();C(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)};a.prototype.render=function(a,b,c,d){var h=this.chart,e=this.scrollbarHeight,f,g=this.xAxis,q=g.pointRange||0;var k=g.fake?h.xAxis[0]:
g;var l=this.navigatorEnabled,m,n=this.rendered;var p=h.inverted;var y=h.xAxis[0].minRange,r=h.xAxis[0].options.maxRange;if(!this.hasDragged||B(c)){a=D(a-q/2);b=D(b+q/2);if(!E(a)||!E(b))if(n)c=0,d=t(g.width,k.width);else return;this.left=t(g.left,h.plotLeft+e+(p?h.plotWidth:0));this.size=m=f=t(g.len,(p?h.plotHeight:h.plotWidth)-2*e);h=p?e:f+2*e;c=t(c,g.toPixels(a,!0));d=t(d,g.toPixels(b,!0));E(c)&&Infinity!==Math.abs(c)||(c=0,d=h);a=g.toValue(c,!0);b=g.toValue(d,!0);var v=Math.abs(D(b-a));v<y?this.grabbedLeft?
c=g.toPixels(b-y-q,!0):this.grabbedRight&&(d=g.toPixels(a+y+q,!0)):B(r)&&D(v-q)>r&&(this.grabbedLeft?c=g.toPixels(b-r-q,!0):this.grabbedRight&&(d=g.toPixels(a+r+q,!0)));this.zoomedMax=u(Math.max(c,d),0,m);this.zoomedMin=u(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(c,d),0,m);this.range=this.zoomedMax-this.zoomedMin;m=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);l&&(this.navigatorGroup.attr({visibility:"visible"}),n=n&&!this.hasDragged?"animate":"attr",this.drawMasks(c,m,p,n),
this.drawOutline(c,m,p,n),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,p,n),this.drawHandle(m,1,p,n)));this.scrollbar&&(p?(p=this.top-e,k=this.left-e+(l||!k.opposite?0:(k.titleOffset||0)+k.axisTitleMargin),e=f+2*e):(p=this.top+(l?this.height:-e),k=this.left-e),this.scrollbar.position(k,p,h,e),this.scrollbar.setRange(this.zoomedMin/(f||1),this.zoomedMax/(f||1)));this.rendered=!0}};a.prototype.addMouseEvents=function(){var a=this,b=a.chart,d=b.container,e=[],f,g;a.mouseMoveHandler=f=
function(b){a.onMouseMove(b)};a.mouseUpHandler=g=function(b){a.onMouseUp(b)};e=a.getPartsEvents("mousedown");e.push(r(b.renderTo,"mousemove",f),r(d.ownerDocument,"mouseup",g));c&&(e.push(r(b.renderTo,"touchmove",f),r(d.ownerDocument,"touchend",g)),e.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=e;a.series&&a.series[0]&&e.push(r(a.series[0].xAxis,"foundExtremes",function(){b.navigator.modifyNavigatorAxisExtremes()}))};a.prototype.getPartsEvents=function(a){var b=this,c=[];["shades","handles"].forEach(function(h){b[h].forEach(function(d,
e){c.push(r(d.element,a,function(a){b[h+"Mousedown"](a,e)}))})});return c};a.prototype.shadesMousedown=function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,d=this.xAxis,e=this.zoomedMin,h=this.left,f=this.size,g=this.range,k=a.chartX;c.inverted&&(k=a.chartY,h=this.top);if(1===b)this.grabbedCenter=k,this.fixedWidth=g,this.dragOffset=k-e;else{a=k-h-g/2;if(0===b)a=Math.max(0,a);else if(2===b&&a+g>=f)if(a=f-g,this.reversedExtremes){a-=g;var q=this.getUnionExtremes().dataMin}else var l=this.getUnionExtremes().dataMax;
a!==e&&(this.fixedWidth=g,b=d.toFixedRange(a,a+g,q,l),B(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"}))}};a.prototype.handlesMousedown=function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],d=this.reversedExtremes;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?c.max:c.min);a.fixedRange=null};a.prototype.onMouseMove=
function(a){var c=this,d=c.chart,e=c.left,h=c.navigatorSize,f=c.range,g=c.dragOffset,k=d.inverted;a.touches&&0===a.touches[0].pageX||(a=d.pointer.normalize(a),d=a.chartX,k&&(e=c.top,d=a.chartY),c.grabbedLeft?(c.hasDragged=!0,c.render(0,0,d-e,c.otherHandlePos)):c.grabbedRight?(c.hasDragged=!0,c.render(0,0,c.otherHandlePos,d-e)):c.grabbedCenter&&(c.hasDragged=!0,d<g?d=g:d>h+g-f&&(d=h+g-f),c.render(0,0,d-g,d-g+f)),c.hasDragged&&c.scrollbar&&t(c.scrollbar.options.liveRedraw,l.svg&&!b&&!this.chart.isBoosting)&&
(a.DOMType=a.type,setTimeout(function(){c.onMouseUp(a)},0)))};a.prototype.onMouseUp=function(a){var b=this.chart,c=this.xAxis,d=this.scrollbar,e=a.DOMEvent||a,h=b.inverted,f=this.rendered&&!this.hasDragged?"animate":"attr",g=Math.round(this.zoomedMax),k=Math.round(this.zoomedMin);if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===a.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var l=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var m=this.fixedExtreme;
this.zoomedMax===this.size&&(m=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(l=this.reversedExtremes?d.dataMax:d.dataMin);c=c.toFixedRange(this.zoomedMin,this.zoomedMax,l,m);B(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:e})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=
this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&(this.shades&&this.drawMasks(k,g,h,f),this.outline&&this.drawOutline(k,g,h,f),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(k,0,h,f),this.drawHandle(g,1,h,f)))};a.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};a.prototype.removeBaseSeriesEvents=function(){var a=
this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){e(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&e(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};a.prototype.init=function(a){var b=a.options,c=b.navigator,d=c.enabled,e=b.scrollbar,h=e.enabled;b=d?c.height:0;var f=h?e.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=b;this.scrollbarHeight=f;this.scrollbarEnabled=h;this.navigatorEnabled=
d;this.navigatorOptions=c;this.scrollbarOptions=e;this.outlineHeight=b+f;this.opposite=t(c.opposite,!(d||!a.inverted));var g=this;d=g.baseSeries;e=a.xAxis.length;h=a.yAxis.length;var k=d&&d[0]&&d[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;g.navigatorEnabled?(g.xAxis=new A(a,C({breaks:k.options.breaks,ordinal:k.options.ordinal},c.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:e,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,
maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[f,0,-f,0],width:b}:{offsets:[0,-f,0,f],height:b})),g.yAxis=new A(a,C(c.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:h,isInternal:!0,zoomEnabled:!1},a.inverted?{width:b}:{height:b})),d||c.series.data?g.updateNavigatorSeries(!1):0===a.series.length&&(g.unbindRedraw=r(a,"beforeRedraw",function(){0<a.series.length&&!g.series&&(g.setBaseSeries(),g.unbindRedraw())})),g.reversedExtremes=a.inverted&&!g.xAxis.reversed||!a.inverted&&g.xAxis.reversed,
g.renderElements(),g.addMouseEvents()):g.xAxis={translate:function(b,c){var d=a.xAxis[0],e=d.getExtremes(),h=d.len-2*f,g=F("min",d.options.min,e.dataMin);d=F("max",d.options.max,e.dataMax)-g;return c?b*d/h+g:h*(b-g)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)},toFixedRange:A.prototype.toFixedRange,fake:!0};a.options.scrollbar.enabled&&(a.scrollbar=g.scrollbar=new w(a.renderer,C(a.options.scrollbar,{margin:g.navigatorEnabled?0:10,vertical:a.inverted}),
a),r(g.scrollbar,"changed",function(b){var c=g.size,d=c*this.to;c*=this.from;g.hasDragged=g.scrollbar.hasDragged;g.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&setTimeout(function(){g.onMouseUp(b)})}));g.addBaseSeriesEvents();g.addChartEvents()};a.prototype.getUnionExtremes=function(a){var b=this.chart.xAxis[0],c=this.xAxis,d=c.options,e=b.options,h;a&&null===b.dataMin||(h={dataMin:t(d&&d.min,F("min",e.min,b.dataMin,c.dataMin,c.min)),dataMax:t(d&&
d.max,F("max",e.max,b.dataMax,c.dataMax,c.max))});return h};a.prototype.setBaseSeries=function(a,b){var c=this.chart,d=this.baseSeries=[];a=a||c.options&&c.options.navigator.baseSeries||(c.series.length?n(c.series,function(a){return!a.options.isInternal}).index:0);(c.series||[]).forEach(function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==a||!1===b.options.showInNavigator)||d.push(b)});this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(!0,b)};a.prototype.updateNavigatorSeries=
function(a,b){var c=this,h=c.chart,f=c.baseSeries,g,l,m=c.navigatorOptions.series,q,n={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,states:{inactive:{opacity:1}}},r=c.series=(c.series||[]).filter(function(a){var b=a.baseSeries;return 0>f.indexOf(b)?(b&&(e(b,"updatedData",c.updatedDataHandler),delete b.navigatorSeries),a.chart&&a.destroy(),!1):!0});f&&f.length&&f.forEach(function(a){var e=
a.navigatorSeries,k=p({color:a.color,visible:a.visible},z(m)?d.navigator.series:m);e&&!1===c.navigatorOptions.adaptToUpdatedData||(n.name="Navigator "+f.length,g=a.options||{},q=g.navigatorOptions||{},l=C(g,n,k,q),l.pointRange=t(k.pointRange,q.pointRange,d.plotOptions[l.type||"line"].pointRange),k=q.data||k.data,c.hasNavigatorData=c.hasNavigatorData||!!k,l.data=k||g.data&&g.data.slice(0),e&&e.options?e.update(l,b):(a.navigatorSeries=h.initSeries(l),a.navigatorSeries.baseSeries=a,r.push(a.navigatorSeries)))});
if(m.data&&(!f||!f.length)||z(m))c.hasNavigatorData=!1,m=k(m),m.forEach(function(a,b){n.name="Navigator "+(r.length+1);l=C(d.navigator.series,{color:h.series[b]&&!h.series[b].options.isInternal&&h.series[b].color||h.options.colors[b]||h.options.colors[0]},n,a);l.data=a.data;l.data&&(c.hasNavigatorData=!0,r.push(h.initSeries(l)))});a&&this.addBaseSeriesEvents()};a.prototype.addBaseSeriesEvents=function(){var a=this,b=a.baseSeries||[];b[0]&&b[0].xAxis&&r(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);
b.forEach(function(b){r(b,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});r(b,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&b.xAxis&&r(b,"updatedData",this.updatedDataHandler);r(b,"remove",function(){this.navigatorSeries&&(f(a.series,this.navigatorSeries),B(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};a.prototype.getBaseSeriesMin=
function(a){return this.baseSeries.reduce(function(a,b){return Math.min(a,b.xData?b.xData[0]:a)},a)};a.prototype.modifyNavigatorAxisExtremes=function(){var a=this.xAxis,b;"undefined"!==typeof a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))};a.prototype.modifyBaseAxisExtremes=function(){var a=this.chart.navigator,b=this.getExtremes(),c=b.dataMin,d=b.dataMax;b=b.max-b.min;var e=a.stickToMin,f=a.stickToMax,g=t(this.options.overscroll,
0),k=a.series&&a.series[0],l=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(e){var m=c;var n=m+b}f&&(n=d+g,e||(m=Math.max(n-b,a.getBaseSeriesMin(k&&k.xData?k.xData[0]:-Number.MAX_VALUE))));l&&(e||f)&&E(m)&&(this.min=this.userMin=m,this.max=this.userMax=n)}a.stickToMin=a.stickToMax=null};a.prototype.updatedDataHandler=function(){var a=this.chart.navigator,b=this.navigatorSeries,c=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):
Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=E(this.xAxis.min)&&this.xAxis.min<=c&&(!this.chart.fixedRange||!a.stickToMax);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))};a.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(r(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);b&&a.render(b.min,
b.max)}),r(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";this.inverted&&(b=a.opposite?"marginRight":"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))};a.prototype.destroy=function(){this.removeEvents();this.xAxis&&(f(this.chart.xAxis,this.xAxis),f(this.chart.axes,this.xAxis));this.yAxis&&(f(this.chart.yAxis,this.yAxis),f(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&
a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){x(a)},this)};return a}();l.Navigator||(l.Navigator=M,r(A,"zoom",function(a){var c=this.chart.options,d=c.chart.zoomType,e=c.chart.pinchType,f=c.navigator;c=c.rangeSelector;this.isXAxis&&(f&&f.enabled||c&&c.enabled)&&("y"===d?a.zoomed=!1:(!b&&
"xy"===d||b&&"xy"===e)&&this.options.range&&(d=this.previousZoom,B(a.newMin)?this.previousZoom=[this.min,this.max]:d&&(a.newMin=d[0],a.newMax=d[1],delete this.previousZoom)));"undefined"!==typeof a.zoomed&&a.preventDefault()}),r(g,"beforeShowResetZoom",function(){var a=this.options,c=a.navigator,d=a.rangeSelector;if((c&&c.enabled||d&&d.enabled)&&(!b&&"x"===a.chart.zoomType||b&&"x"===a.chart.pinchType))return!1}),r(g,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=
this.navigator=new M(this)}),r(g,"afterSetChartSize",function(){var a=this.legend,b=this.navigator;if(b){var c=a&&a.options;var d=b.xAxis;var e=b.yAxis;var f=b.scrollbarHeight;this.inverted?(b.left=b.opposite?this.chartWidth-f-b.height:this.spacing[3]+f,b.top=this.plotTop+f):(b.left=this.plotLeft+f,b.top=b.navigatorOptions.top||this.chartHeight-b.height-f-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&c.enabled&&!c.floating?
a.legendHeight+t(c.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));d&&e&&(this.inverted?d.options.left=e.options.left=b.left:d.options.top=e.options.top=b.top,d.setAxisSize(),e.setAxisSize())}}),r(g,"update",function(a){var b=a.options.navigator||{},c=a.options.scrollbar||{};this.navigator||this.scroller||!b.enabled&&!c.enabled||(C(!0,this.options.navigator,b),C(!0,this.options.scrollbar,c),delete a.options.navigator,delete a.options.scrollbar)}),r(g,"afterUpdate",function(a){this.navigator||
this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new M(this),t(a.redraw,!0)&&this.redraw(a.animation))}),r(g,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),r(m,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),g.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}));
l.Navigator=M;return l.Navigator});F(l,"masters/modules/gantt.src.js",[],function(){})});
//# sourceMappingURL=gantt.js.map