/*
 Highmaps JS v8.0.4 (2020-03-19)

 Highmaps as a plugin for Highcharts or Highstock.

 (c) 2011-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(f){"object"===typeof module&&module.exports?(f["default"]=f,module.exports=f):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(x){f(x);f.Highcharts=x;return f}):f("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(f){function x(c,q,f,k){c.hasOwnProperty(q)||(c[q]=k.apply(null,f))}f=f?f._modules:{};x(f,"parts-map/MapAxis.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,q){var f=q.addEvent,k=q.pick;c=c.Axis;f(c,"getSeriesExtremes",
function(){var p=[];this.isXAxis&&(this.series.forEach(function(h,c){h.useMapGeometry&&(p[c]=h.xData,h.xData=[])}),this.seriesXData=p)});f(c,"afterGetSeriesExtremes",function(){var p=this.seriesXData,h;if(this.isXAxis){var c=k(this.dataMin,Number.MAX_VALUE);var f=k(this.dataMax,-Number.MAX_VALUE);this.series.forEach(function(q,t){q.useMapGeometry&&(c=Math.min(c,k(q.minX,c)),f=Math.max(f,k(q.maxX,f)),q.xData=p[t],h=!0)});h&&(this.dataMin=c,this.dataMax=f);delete this.seriesXData}});f(c,"afterSetAxisTranslation",
function(){var p=this.chart;var h=p.plotWidth/p.plotHeight;p=p.xAxis[0];var c;"yAxis"===this.coll&&"undefined"!==typeof p.transA&&this.series.forEach(function(h){h.preserveAspectRatio&&(c=!0)});if(c&&(this.transA=p.transA=Math.min(this.transA,p.transA),h/=(p.max-p.min)/(this.max-this.min),h=1>h?this:p,p=(h.max-h.min)*h.transA,h.pixelPadding=h.len-p,h.minPixelPadding=h.pixelPadding/2,p=h.fixTo)){p=p[1]-h.toValue(p[0],!0);p*=h.transA;if(Math.abs(p)>h.minPixelPadding||h.min===h.dataMin&&h.max===h.dataMax)p=
0;h.minPixelPadding-=p}});f(c,"render",function(){this.fixTo=null})});x(f,"parts-map/ColorSeriesMixin.js",[f["parts/Globals.js"]],function(c){c.colorPointMixin={setVisible:function(c){var f=this,k=c?"show":"hide";f.visible=f.options.visible=!!c;["graphic","dataLabel"].forEach(function(c){if(f[c])f[c][k]()})}};c.colorSeriesMixin={optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var c=this,f=this.options.nullColor,k=this.colorAxis,p=this.colorKey;(this.data.length?this.data:this.points).forEach(function(h){var q=
h.getNestedProperty(p);if(q=h.options.color||(h.isNull||null===h.value?f:k&&"undefined"!==typeof q?k.toColor(q,h):h.color||c.color))h.color=q})}}});x(f,"parts-map/ColorAxis.js",[f["parts/Globals.js"],f["parts/Color.js"],f["parts/Point.js"],f["parts/Legend.js"],f["mixins/legend-symbol.js"],f["parts/Utilities.js"]],function(c,f,u,k,p,h){"";var q=f.parse;f=h.addEvent;var y=h.erase,v=h.extend,t=h.Fx,a=h.isNumber,e=h.merge,g=h.pick,A=h.splat,w=c.Axis;h=c.Chart;var n=c.Series,m=c.colorPointMixin,l=c.noop;
v(n.prototype,c.colorSeriesMixin);v(u.prototype,m);h.prototype.collectionsWithUpdate.push("colorAxis");h.prototype.collectionsWithInit.colorAxis=[h.prototype.addColorAxis];var b=c.ColorAxis=function(){this.init.apply(this,arguments)};v(b.prototype,w.prototype);v(b.prototype,{defaultColorAxisOptions:{lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},
minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0},keepProps:["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"].concat(w.prototype.keepProps),init:function(d,b){this.coll="colorAxis";var r=this.buildOptions.call(d,this.defaultColorAxisOptions,b);w.prototype.init.call(this,d,r);b.dataClasses&&this.initDataClasses(b);this.initStops();this.horiz=!r.opposite;this.zoomEnabled=!1;this.defaultLegendLength=200},initDataClasses:function(d){var b=this.chart,a,
B=0,l=b.options.chart.colorCount,g=this.options,m=d.dataClasses.length;this.dataClasses=a=[];this.legendItems=[];d.dataClasses.forEach(function(d,r){d=e(d);a.push(d);if(b.styledMode||!d.color)"category"===g.dataClassColor?(b.styledMode||(r=b.options.colors,l=r.length,d.color=r[B]),d.colorIndex=B,B++,B===l&&(B=0)):d.color=q(g.minColor).tweenTo(q(g.maxColor),2>m?.5:r/(m-1))})},hasData:function(){return!(!this.tickPositions||!this.tickPositions.length)},setTickPositions:function(){if(!this.dataClasses)return w.prototype.setTickPositions.call(this)},
initStops:function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(d){d.color=q(d[1])})},buildOptions:function(d,b){var r=this.options.legend,a=b.layout?"vertical"!==b.layout:"vertical"!==r.layout;return e(d,{side:a?2:1,reversed:!a},b,{opposite:!a,showEmpty:!1,title:null,visible:r.enabled&&(b?!1!==b.visible:!0)})},setOptions:function(d){w.prototype.setOptions.call(this,d);this.options.crosshair=this.options.marker},setAxisSize:function(){var d=
this.legendSymbol,b=this.chart,a=b.options.legend||{},e,l;d?(this.left=a=d.attr("x"),this.top=e=d.attr("y"),this.width=l=d.attr("width"),this.height=d=d.attr("height"),this.right=b.chartWidth-a-l,this.bottom=b.chartHeight-e-d,this.len=this.horiz?l:d,this.pos=this.horiz?a:e):this.len=(this.horiz?a.symbolWidth:a.symbolHeight)||this.defaultLegendLength},normalizedValue:function(d){this.isLog&&(d=this.val2lin(d));return 1-(this.max-d)/(this.max-this.min||1)},toColor:function(d,b){var r=this.stops,a=this.dataClasses,
e;if(a)for(e=a.length;e--;){var l=a[e];var g=l.from;r=l.to;if(("undefined"===typeof g||d>=g)&&("undefined"===typeof r||d<=r)){var m=l.color;b&&(b.dataClass=e,b.colorIndex=l.colorIndex);break}}else{d=this.normalizedValue(d);for(e=r.length;e--&&!(d>r[e][0]););g=r[e]||r[e+1];r=r[e+1]||g;d=1-(r[0]-d)/(r[0]-g[0]||1);m=g.color.tweenTo(r.color,d)}return m},getOffset:function(){var d=this.legendGroup,b=this.chart.axisOffset[this.side];d&&(this.axisParent=d,w.prototype.getOffset.call(this),this.added||(this.added=
!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=b)},setLegendColor:function(){var d=this.reversed;var b=d?1:0;d=d?0:1;b=this.horiz?[b,0,d,0]:[0,d,0,b];this.legendColor={linearGradient:{x1:b[0],y1:b[1],x2:b[2],y2:b[3]},stops:this.stops}},drawLegendSymbol:function(d,b){var r=d.padding,a=d.options,e=this.horiz,l=g(a.symbolWidth,e?this.defaultLegendLength:12),m=g(a.symbolHeight,e?12:this.defaultLegendLength),c=g(a.labelPadding,e?16:30);a=g(a.itemDistance,10);this.setLegendColor();
b.legendSymbol=this.chart.renderer.rect(0,d.baseline-11,l,m).attr({zIndex:1}).add(b.legendGroup);this.legendItemWidth=l+r+(e?a:c);this.legendItemHeight=m+r+(e?c:0)},setState:function(d){this.series.forEach(function(b){b.setState(d)})},visible:!0,setVisible:l,getSeriesExtremes:function(){var d=this.series,b=d.length,a;this.dataMin=Infinity;for(this.dataMax=-Infinity;b--;){var e=d[b];var l=e.colorKey=g(e.options.colorKey,e.colorKey,e.pointValKey,e.zoneAxis,"y");var m=e.pointArrayMap;var c=e[l+"Min"]&&
e[l+"Max"];if(e[l+"Data"])var h=e[l+"Data"];else if(m){h=[];m=m.indexOf(l);var p=e.yData;if(0<=m&&p)for(a=0;a<p.length;a++)h.push(g(p[a][m],p[a]))}else h=e.yData;c?(e.minColorValue=e[l+"Min"],e.maxColorValue=e[l+"Max"]):(n.prototype.getExtremes.call(e,h),e.minColorValue=e.dataMin,e.maxColorValue=e.dataMax);"undefined"!==typeof e.minColorValue&&(this.dataMin=Math.min(this.dataMin,e.minColorValue),this.dataMax=Math.max(this.dataMax,e.maxColorValue));c||n.prototype.getExtremes.call(e)}},drawCrosshair:function(d,
b){var e=b&&b.plotX,a=b&&b.plotY,r=this.pos,l=this.len;if(b){var g=this.toPixels(b.getNestedProperty(b.series.colorKey));g<r?g=r-2:g>r+l&&(g=r+l+2);b.plotX=g;b.plotY=this.len-g;w.prototype.drawCrosshair.call(this,d,b);b.plotX=e;b.plotY=a;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||this.cross.attr({fill:this.crosshair.color}))}},getPlotLinePath:function(d){var b=
d.translatedValue;return a(b)?this.horiz?["M",b-4,this.top-6,"L",b+4,this.top-6,b,this.top,"Z"]:["M",this.left,b,"L",this.left-6,b+6,this.left-6,b-6,"Z"]:w.prototype.getPlotLinePath.apply(this,arguments)},update:function(d,b){var a=this.chart,r=a.legend,l=this.buildOptions.call(a,{},d);this.series.forEach(function(d){d.isDirtyData=!0});(d.dataClasses&&r.allItems||this.dataClasses)&&this.destroyItems();a.options[this.coll]=e(this.userOptions,l);w.prototype.update.call(this,l,b);this.legendItem&&(this.setLegendColor(),
r.colorizeItem(this,!0))},destroyItems:function(){var d=this.chart;this.legendItem?d.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(b){d.legend.destroyItem(b)});d.isDirtyLegend=!0},remove:function(d){this.destroyItems();w.prototype.remove.call(this,d)},getDataClassLegendSymbols:function(){var d=this,b=this.chart,e=this.legendItems,a=b.options.legend,g=a.valueDecimals,m=a.valueSuffix||"",c;e.length||this.dataClasses.forEach(function(a,r){var h=!0,n=a.from,B=a.to,z=b.numberFormatter;
c="";"undefined"===typeof n?c="< ":"undefined"===typeof B&&(c="> ");"undefined"!==typeof n&&(c+=z(n,g)+m);"undefined"!==typeof n&&"undefined"!==typeof B&&(c+=" - ");"undefined"!==typeof B&&(c+=z(B,g)+m);e.push(v({chart:b,name:c,options:{},drawLegendSymbol:p.drawRectangle,visible:!0,setState:l,isDataClass:!0,setVisible:function(){h=this.visible=!h;d.series.forEach(function(d){d.points.forEach(function(d){d.dataClass===r&&d.setVisible(h)})});b.legend.colorizeItem(this,h)}},a))});return e},beforePadding:!1,
name:""});["fill","stroke"].forEach(function(d){t.prototype[d+"Setter"]=function(){this.elem.attr(d,q(this.start).tweenTo(q(this.end),this.pos),null,!0)}});f(h,"afterGetAxes",function(){var d=this,a=d.options;this.colorAxis=[];a.colorAxis&&(a.colorAxis=A(a.colorAxis),a.colorAxis.forEach(function(a,e){a.index=e;new b(d,a)}))});f(n,"bindAxes",function(){var d=this.axisTypes;d?-1===d.indexOf("colorAxis")&&d.push("colorAxis"):this.axisTypes=["colorAxis"]});f(k,"afterGetAllItems",function(d){var b=[],
a,e;(this.chart.colorAxis||[]).forEach(function(e){(a=e.options)&&a.showInLegend&&(a.dataClasses&&a.visible?b=b.concat(e.getDataClassLegendSymbols()):a.visible&&b.push(e),e.series.forEach(function(b){if(!b.options.showInLegend||a.dataClasses)"point"===b.options.legendType?b.points.forEach(function(b){y(d.allItems,b)}):y(d.allItems,b)}))});for(e=b.length;e--;)d.allItems.unshift(b[e])});f(k,"afterColorizeItem",function(d){d.visible&&d.item.legendColor&&d.item.legendSymbol.attr({fill:d.item.legendColor})});
f(k,"afterUpdate",function(){var d=this.chart.colorAxis;d&&d.forEach(function(d,b,a){d.update({},a)})});f(n,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()})});x(f,"parts-map/ColorMapSeriesMixin.js",[f["parts/Globals.js"],f["parts/Point.js"],f["parts/Utilities.js"]],function(c,f,u){var k=u.defined;u=c.noop;var p=c.seriesTypes;c.colorMapPointMixin={dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&
-Infinity!==this.value},setState:function(c){f.prototype.setState.call(this,c);this.graphic&&this.graphic.attr({zIndex:"hover"===c?1:0})}};c.colorMapSeriesMixin={pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:u,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:p.column.prototype.pointAttribs,colorAttribs:function(c){var h={};k(c.color)&&(h[this.colorProp||"fill"]=c.color);return h}}});x(f,"parts-map/MapNavigation.js",
[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,f){function q(a){a&&(a.preventDefault&&a.preventDefault(),a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)}function k(a){this.init(a)}var p=f.addEvent,h=f.extend,C=f.merge,y=f.objectEach,v=f.pick;f=c.Chart;var t=c.doc;k.prototype.init=function(a){this.chart=a;a.mapNavButtons=[]};k.prototype.update=function(a){var e=this.chart,g=e.options.mapNavigation,c,f,n,m,l,b=function(d){this.handler.call(e,d);q(d)},d=e.mapNavButtons;a&&(g=e.options.mapNavigation=
C(e.options.mapNavigation,a));for(;d.length;)d.pop().destroy();v(g.enableButtons,g.enabled)&&!e.renderer.forExport&&y(g.buttons,function(a,z){c=C(g.buttonOptions,a);e.styledMode||(f=c.theme,f.style=C(c.theme.style,c.style),m=(n=f.states)&&n.hover,l=n&&n.select);a=e.renderer.button(c.text,0,0,b,f,m,l,0,"zoomIn"===z?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[z]).attr({width:c.width,height:c.height,title:e.options.lang[z],padding:c.padding,
zIndex:5}).add();a.handler=c.onclick;p(a.element,"dblclick",q);d.push(a);var r=c,D=p(e,"load",function(){a.align(h(r,{width:a.width,height:2*a.height}),null,r.alignTo);D()})});this.updateEvents(g)};k.prototype.updateEvents=function(a){var e=this.chart;v(a.enableDoubleClickZoom,a.enabled)||a.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||p(e.container,"dblclick",function(a){e.pointer.onContainerDblClick(a)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());v(a.enableMouseWheelZoom,
a.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||p(e.container,"undefined"===typeof t.onmousewheel?"DOMMouseScroll":"mousewheel",function(a){e.pointer.onContainerMouseWheel(a);q(a);return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};h(f.prototype,{fitToBox:function(a,e){[["x","width"],["y","height"]].forEach(function(c){var g=c[0];c=c[1];a[g]+a[c]>e[g]+e[c]&&(a[c]>e[c]?(a[c]=e[c],a[g]=e[g]):a[g]=e[g]+e[c]-a[c]);a[c]>e[c]&&(a[c]=e[c]);a[g]<e[g]&&(a[g]=e[g])});
return a},mapZoom:function(a,e,c,h,f){var g=this.xAxis[0],m=g.max-g.min,l=v(e,g.min+m/2),b=m*a;m=this.yAxis[0];var d=m.max-m.min,r=v(c,m.min+d/2);d*=a;l=this.fitToBox({x:l-b*(h?(h-g.pos)/g.len:.5),y:r-d*(f?(f-m.pos)/m.len:.5),width:b,height:d},{x:g.dataMin,y:m.dataMin,width:g.dataMax-g.dataMin,height:m.dataMax-m.dataMin});b=l.x<=g.dataMin&&l.width>=g.dataMax-g.dataMin&&l.y<=m.dataMin&&l.height>=m.dataMax-m.dataMin;h&&(g.fixTo=[h-g.pos,e]);f&&(m.fixTo=[f-m.pos,c]);"undefined"===typeof a||b?(g.setExtremes(void 0,
void 0,!1),m.setExtremes(void 0,void 0,!1)):(g.setExtremes(l.x,l.x+l.width,!1),m.setExtremes(l.y,l.y+l.height,!1));this.redraw()}});p(f,"beforeRender",function(){this.mapNavigation=new k(this);this.mapNavigation.update()});c.MapNavigation=k});x(f,"parts-map/MapPointer.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,f){var q=f.extend,k=f.pick;f=f.wrap;c=c.Pointer;q(c.prototype,{onContainerDblClick:function(c){var f=this.chart;c=this.normalize(c);f.options.mapNavigation.enableDoubleClickZoomTo?
f.pointer.inClass(c.target,"highcharts-tracker")&&f.hoverPoint&&f.hoverPoint.zoomTo():f.isInsidePlot(c.chartX-f.plotLeft,c.chartY-f.plotTop)&&f.mapZoom(.5,f.xAxis[0].toValue(c.chartX),f.yAxis[0].toValue(c.chartY),c.chartX,c.chartY)},onContainerMouseWheel:function(c){var f=this.chart;c=this.normalize(c);var p=c.detail||-(c.wheelDelta/120);f.isInsidePlot(c.chartX-f.plotLeft,c.chartY-f.plotTop)&&f.mapZoom(Math.pow(f.options.mapNavigation.mouseWheelSensitivity,p),f.xAxis[0].toValue(c.chartX),f.yAxis[0].toValue(c.chartY),
c.chartX,c.chartY)}});f(c.prototype,"zoomOption",function(c){var f=this.chart.options.mapNavigation;k(f.enableTouchZoom,f.enabled)&&(this.chart.options.chart.pinchType="xy");c.apply(this,[].slice.call(arguments,1))});f(c.prototype,"pinchTranslate",function(c,f,k,q,u,t,a){c.call(this,f,k,q,u,t,a);"map"===this.chart.options.chart.type&&this.hasZoom&&(c=q.scaleX>q.scaleY,this.pinchTranslateDirection(!c,f,k,q,u,t,a,c?q.scaleX:q.scaleY))})});x(f,"parts-map/MapSeries.js",[f["parts/Globals.js"],f["mixins/legend-symbol.js"],
f["parts/Point.js"],f["parts/Utilities.js"]],function(c,f,u,k){var p=k.extend,h=k.fireEvent,q=k.getNestedProperty,y=k.isArray,v=k.isNumber,t=k.merge,a=k.objectEach,e=k.pick,g=k.seriesType,A=k.splat,w=c.colorMapPointMixin,n=c.noop,m=c.Series,l=c.seriesTypes;g("map","scatter",{animation:!1,dataLabels:{crop:!1,formatter:function(){return this.point.value},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},
turboThreshold:0,allAreas:!0,borderColor:"#cccccc",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:"#cccccc"},inactive:{opacity:1}}},t(c.colorMapSeriesMixin,{type:"map",getExtremesFromAll:!0,useMapGeometry:!0,forceDL:!0,searchPoint:n,directTouch:!0,preserveAspectRatio:!0,pointArrayMap:["value"],setOptions:function(b){b=m.prototype.setOptions.call(this,b);var d=b.joinBy;null===d&&(d="_i");d=this.joinBy=A(d);d[1]||(d[1]=d[0]);return b},getBox:function(b){var d=
Number.MAX_VALUE,a=-d,l=d,f=-d,g=d,m=d,n=this.xAxis,h=this.yAxis,k;(b||[]).forEach(function(b){if(b.path){"string"===typeof b.path&&(b.path=c.splitPath(b.path));var r=b.path||[],n=r.length,h=!1,B=-d,D=d,z=-d,t=d,p=b.properties;if(!b._foundBox){for(;n--;)v(r[n])&&(h?(B=Math.max(B,r[n]),D=Math.min(D,r[n])):(z=Math.max(z,r[n]),t=Math.min(t,r[n])),h=!h);b._midX=D+(B-D)*e(b.middleX,p&&p["hc-middle-x"],.5);b._midY=t+(z-t)*e(b.middleY,p&&p["hc-middle-y"],.5);b._maxX=B;b._minX=D;b._maxY=z;b._minY=t;b.labelrank=
e(b.labelrank,(B-D)*(z-t));b._foundBox=!0}a=Math.max(a,b._maxX);l=Math.min(l,b._minX);f=Math.max(f,b._maxY);g=Math.min(g,b._minY);m=Math.min(b._maxX-b._minX,b._maxY-b._minY,m);k=!0}});k&&(this.minY=Math.min(g,e(this.minY,d)),this.maxY=Math.max(f,e(this.maxY,-d)),this.minX=Math.min(l,e(this.minX,d)),this.maxX=Math.max(a,e(this.maxX,-d)),n&&"undefined"===typeof n.options.minRange&&(n.minRange=Math.min(5*m,(this.maxX-this.minX)/5,n.minRange||d)),h&&"undefined"===typeof h.options.minRange&&(h.minRange=
Math.min(5*m,(this.maxY-this.minY)/5,h.minRange||d)))},hasData:function(){return!!this.processedXData.length},getExtremes:function(){m.prototype.getExtremes.call(this,this.valueData);this.chart.hasRendered&&this.isDirtyData&&this.getBox(this.options.data);this.valueMin=this.dataMin;this.valueMax=this.dataMax;this.dataMin=this.minY;this.dataMax=this.maxY},translatePath:function(b){var d=!1,a=this.xAxis,e=this.yAxis,c=a.min,l=a.transA;a=a.minPixelPadding;var f=e.min,g=e.transA;e=e.minPixelPadding;var m,
n=[];if(b)for(m=b.length;m--;)v(b[m])?(n[m]=d?(b[m]-c)*l+a:(b[m]-f)*g+e,d=!d):n[m]=b[m];return n},setData:function(b,d,e,l){var r=this.options,f=this.chart.options.chart,g=f&&f.map,n=r.mapData,h=this.joinBy,k=r.keys||this.pointArrayMap,z=[],p={},w=this.chart.mapTransforms;!n&&g&&(n="string"===typeof g?c.maps[g]:g);b&&b.forEach(function(d,a){var e=0;if(v(d))b[a]={value:d};else if(y(d)){b[a]={};!r.keys&&d.length>k.length&&"string"===typeof d[0]&&(b[a]["hc-key"]=d[0],++e);for(var c=0;c<k.length;++c,
++e)k[c]&&"undefined"!==typeof d[e]&&(0<k[c].indexOf(".")?u.prototype.setNestedProperty(b[a],d[e],k[c]):b[a][k[c]]=d[e])}h&&"_i"===h[0]&&(b[a]._i=a)});this.getBox(b);(this.chart.mapTransforms=w=f&&f.mapTransforms||n&&n["hc-transform"]||w)&&a(w,function(b){b.rotation&&(b.cosAngle=Math.cos(b.rotation),b.sinAngle=Math.sin(b.rotation))});if(n){"FeatureCollection"===n.type&&(this.mapTitle=n.title,n=c.geojson(n,this.type,this));this.mapData=n;this.mapMap={};for(w=0;w<n.length;w++)f=n[w],g=f.properties,
f._i=w,h[0]&&g&&g[h[0]]&&(f[h[0]]=g[h[0]]),p[f[h[0]]]=f;this.mapMap=p;if(b&&h[1]){var A=h[1];b.forEach(function(b){b=q(A,b);p[b]&&z.push(p[b])})}if(r.allAreas){this.getBox(n);b=b||[];if(h[1]){var C=h[1];b.forEach(function(b){z.push(q(C,b))})}z="|"+z.map(function(b){return b&&b[h[0]]}).join("|")+"|";n.forEach(function(d){h[0]&&-1!==z.indexOf("|"+d[h[0]]+"|")||(b.push(t(d,{value:null})),l=!1)})}else this.getBox(z)}m.prototype.setData.call(this,b,d,e,l)},drawGraph:n,drawDataLabels:n,doFullTranslate:function(){return this.isDirtyData||
this.chart.isResizing||this.chart.renderer.isVML||!this.baseTrans},translate:function(){var b=this,d=b.xAxis,a=b.yAxis,e=b.doFullTranslate();b.generatePoints();b.data.forEach(function(c){v(c._midX)&&v(c._midY)&&(c.plotX=d.toPixels(c._midX,!0),c.plotY=a.toPixels(c._midY,!0));e&&(c.shapeType="path",c.shapeArgs={d:b.translatePath(c.path)})});h(b,"afterTranslate")},pointAttribs:function(b,d){d=b.series.chart.styledMode?this.colorAttribs(b):l.column.prototype.pointAttribs.call(this,b,d);d["stroke-width"]=
e(b.options[this.pointAttrToOptions&&this.pointAttrToOptions["stroke-width"]||"borderWidth"],"inherit");return d},drawPoints:function(){var b=this,d=b.xAxis,a=b.yAxis,c=b.group,f=b.chart,g=f.renderer,m=this.baseTrans;b.transformGroup||(b.transformGroup=g.g().attr({scaleX:1,scaleY:1}).add(c),b.transformGroup.survive=!0);if(b.doFullTranslate())f.hasRendered&&!f.styledMode&&b.points.forEach(function(d){d.shapeArgs&&(d.shapeArgs.fill=b.pointAttribs(d,d.state).fill)}),b.group=b.transformGroup,l.column.prototype.drawPoints.apply(b),
b.group=c,b.points.forEach(function(d){if(d.graphic){var a="";d.name&&(a+="highcharts-name-"+d.name.replace(/ /g,"-").toLowerCase());d.properties&&d.properties["hc-key"]&&(a+=" highcharts-key-"+d.properties["hc-key"].toLowerCase());a&&d.graphic.addClass(a);f.styledMode&&d.graphic.css(b.pointAttribs(d,d.selected&&"select"||void 0))}}),this.baseTrans={originX:d.min-d.minPixelPadding/d.transA,originY:a.min-a.minPixelPadding/a.transA+(a.reversed?0:a.len/a.transA),transAX:d.transA,transAY:a.transA},this.transformGroup.animate({translateX:0,
translateY:0,scaleX:1,scaleY:1});else{var n=d.transA/m.transAX;var h=a.transA/m.transAY;var k=d.toPixels(m.originX,!0);var p=a.toPixels(m.originY,!0);.99<n&&1.01>n&&.99<h&&1.01>h&&(h=n=1,k=Math.round(k),p=Math.round(p));var t=this.transformGroup;if(f.renderer.globalAnimation){var w=t.attr("translateX");var q=t.attr("translateY");var A=t.attr("scaleX");var u=t.attr("scaleY");t.attr({animator:0}).animate({animator:1},{step:function(b,d){t.attr({translateX:w+(k-w)*d.pos,translateY:q+(p-q)*d.pos,scaleX:A+
(n-A)*d.pos,scaleY:u+(h-u)*d.pos})}})}else t.attr({translateX:k,translateY:p,scaleX:n,scaleY:h})}f.styledMode||c.element.setAttribute("stroke-width",e(b.options[b.pointAttrToOptions&&b.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(n||1));this.drawMapDataLabels()},drawMapDataLabels:function(){m.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)},render:function(){var b=this,d=m.prototype.render;b.chart.renderer.isVML&&3E3<b.data.length?
setTimeout(function(){d.call(b)}):d.call(b)},animate:function(b){var d=this.options.animation,a=this.group,e=this.xAxis,c=this.yAxis,l=e.pos,f=c.pos;this.chart.renderer.isSVG&&(!0===d&&(d={duration:1E3}),b?a.attr({translateX:l+e.len/2,translateY:f+c.len/2,scaleX:.001,scaleY:.001}):a.animate({translateX:l,translateY:f,scaleX:1,scaleY:1},d))},animateDrilldown:function(b){var d=this.chart.plotBox,a=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],e=a.bBox,c=this.chart.options.drilldown.animation;
b||(b=Math.min(e.width/d.width,e.height/d.height),a.shapeArgs={scaleX:b,scaleY:b,translateX:e.x,translateY:e.y},this.points.forEach(function(b){b.graphic&&b.graphic.attr(a.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},c)}))},drawLegendSymbol:f.drawRectangle,animateDrillupFrom:function(b){l.column.prototype.animateDrillupFrom.call(this,b)},animateDrillupTo:function(b){l.column.prototype.animateDrillupTo.call(this,b)}}),p({applyOptions:function(b,d){var a=this.series;b=u.prototype.applyOptions.call(this,
b,d);d=a.joinBy;a.mapData&&a.mapMap&&(d=u.prototype.getNestedProperty.call(b,d[1]),(d="undefined"!==typeof d&&a.mapMap[d])?(a.xyFromShape&&(b.x=d._midX,b.y=d._midY),p(b,d)):b.value=b.value||null);return b},onMouseOver:function(b){k.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)u.prototype.onMouseOver.call(this,b);else this.series.onMouseOut(b)},zoomTo:function(){var b=this.series;b.xAxis.setExtremes(this._minX,this._maxX,!1);b.yAxis.setExtremes(this._minY,
this._maxY,!1);b.chart.redraw()}},w));""});x(f,"parts-map/MapLineSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,f){f=f.seriesType;var q=c.seriesTypes;f("mapline","map",{lineWidth:1,fillColor:"none"},{type:"mapline",colorProp:"stroke",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(c,f){c=q.map.prototype.pointAttribs.call(this,c,f);c.fill=this.options.fillColor;return c},drawLegendSymbol:q.line.prototype.drawLegendSymbol});""});x(f,"parts-map/MapPointSeries.js",
[f["parts/Globals.js"]],function(c){var f=c.merge,u=c.Point,k=c.Series;c=c.seriesType;c("mappoint","scatter",{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:"#000000"}}},{type:"mappoint",forceDL:!0,drawDataLabels:function(){k.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)}},{applyOptions:function(c,h){c="undefined"!==typeof c.lat&&"undefined"!==typeof c.lon?f(c,this.series.chart.fromLatLonToPoint(c)):
c;return u.prototype.applyOptions.call(this,c,h)}});""});x(f,"parts-more/BubbleLegend.js",[f["parts/Globals.js"],f["parts/Color.js"],f["parts/Legend.js"],f["parts/Utilities.js"]],function(c,f,u,k){"";var p=f.parse;f=k.addEvent;var h=k.arrayMax,q=k.arrayMin,y=k.isNumber,v=k.merge,t=k.objectEach,a=k.pick,e=k.stableSort,g=k.wrap,A=c.Series,w=c.Chart,n=c.noop,m=c.setOptions;m({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,
connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});m=function(){function c(b,d){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=
this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=n;this.init(b,d)}c.prototype.init=function(b,d){this.options=b;this.visible=!0;this.chart=d.chart;this.legend=d};c.prototype.addToLegend=function(b){b.splice(this.options.legendIndex,0,this)};c.prototype.drawLegendSymbol=function(b){var d=this.chart,c=this.options,f=a(b.options.itemDistance,20),l=c.ranges;var g=c.connectorDistance;this.fontMetrics=d.renderer.fontMetrics(c.labels.style.fontSize.toString()+
"px");l&&l.length&&y(l[0].value)?(e(l,function(b,d){return d.value-b.value}),this.ranges=l,this.setOptions(),this.render(),d=this.getMaxLabelSize(),l=this.ranges[0].radius,b=2*l,g=g-l+d.width,g=0<g?g:0,this.maxLabel=d,this.movementX="left"===c.labels.align?g:0,this.legendItemWidth=b+g+f,this.legendItemHeight=b+this.fontMetrics.h/2):b.options.bubbleLegend.autoRanges=!0};c.prototype.setOptions=function(){var b=this.ranges,d=this.options,e=this.chart.series[d.seriesIndex],c=this.legend.baseline,f={"z-index":d.zIndex,
"stroke-width":d.borderWidth},l={"z-index":d.zIndex,"stroke-width":d.connectorWidth},g=this.getLabelStyles(),m=e.options.marker.fillOpacity,n=this.chart.styledMode;b.forEach(function(r,h){n||(f.stroke=a(r.borderColor,d.borderColor,e.color),f.fill=a(r.color,d.color,1!==m?p(e.color).setOpacity(m).get("rgba"):e.color),l.stroke=a(r.connectorColor,d.connectorColor,e.color));b[h].radius=this.getRangeRadius(r.value);b[h]=v(b[h],{center:b[0].radius-b[h].radius+c});n||v(!0,b[h],{bubbleStyle:v(!1,f),connectorStyle:v(!1,
l),labelStyle:g})},this)};c.prototype.getLabelStyles=function(){var b=this.options,d={},e="left"===b.labels.align,c=this.legend.options.rtl;t(b.labels.style,function(b,a){"color"!==a&&"fontSize"!==a&&"z-index"!==a&&(d[a]=b)});return v(!1,d,{"font-size":b.labels.style.fontSize,fill:a(b.labels.style.color,"#000000"),"z-index":b.zIndex,align:c||e?"right":"left"})};c.prototype.getRangeRadius=function(b){var d=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,d.ranges[d.ranges.length-
1].value,d.ranges[0].value,d.minSize,d.maxSize,b)};c.prototype.render=function(){var b=this.chart.renderer,d=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=b.g("bubble-legend");this.legendItem=b.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(b){b.value>=d&&this.renderRange(b)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};
c.prototype.renderRange=function(b){var d=this.options,a=d.labels,e=this.chart.renderer,c=this.symbols,f=c.labels,l=b.center,g=Math.abs(b.radius),m=d.connectorDistance,n=a.align,h=a.style.fontSize;m=this.legend.options.rtl||"left"===n?-m:m;a=d.connectorWidth;var k=this.ranges[0].radius,t=l-g-d.borderWidth/2+a/2;h=h/2-(this.fontMetrics.h-h)/2;var p=e.styledMode;"center"===n&&(m=0,d.connectorDistance=0,b.labelStyle.align="center");n=t+d.labels.y;var w=k+m+d.labels.x;c.bubbleItems.push(e.circle(k,l+
((t%1?1:.5)-(a%2?0:.5)),g).attr(p?{}:b.bubbleStyle).addClass((p?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(d.className||"")).add(this.legendSymbol));c.connectors.push(e.path(e.crispLine(["M",k,t,"L",k+m,t],d.connectorWidth)).attr(p?{}:b.connectorStyle).addClass((p?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(d.connectorClassName||"")).add(this.legendSymbol));b=e.text(this.formatLabel(b),w,n+h).attr(p?{}:
b.labelStyle).addClass("highcharts-bubble-legend-labels "+(d.labels.className||"")).add(this.legendSymbol);f.push(b);b.placed=!0;b.alignAttr={x:w,y:n+h}};c.prototype.getMaxLabelSize=function(){var b,d;this.symbols.labels.forEach(function(a){d=a.getBBox(!0);b=b?d.width>b.width?d:b:d});return b||{}};c.prototype.formatLabel=function(b){var d=this.options,a=d.labels.formatter;d=d.labels.format;var e=this.chart.numberFormatter;return d?k.format(d,b):a?a.call(b):e(b.value,1)};c.prototype.hideOverlappingLabels=
function(){var b=this.chart,d=this.symbols;!this.options.labels.allowOverlap&&d&&(b.hideOverlappingLabels(d.labels),d.labels.forEach(function(b,a){b.newOpacity?b.newOpacity!==b.oldOpacity&&d.connectors[a].show():d.connectors[a].hide()}))};c.prototype.getRanges=function(){var b=this.legend.bubbleLegend,d=b.options.ranges,e,c=Number.MAX_VALUE,f=-Number.MAX_VALUE;b.chart.series.forEach(function(b){b.isBubble&&!b.ignoreSeries&&(e=b.zData.filter(y),e.length&&(c=a(b.options.zMin,Math.min(c,Math.max(q(e),
!1===b.options.displayNegative?b.options.zThreshold:-Number.MAX_VALUE))),f=a(b.options.zMax,Math.max(f,h(e)))))});var l=c===f?[{value:f}]:[{value:c},{value:(c+f)/2},{value:f,autoRanges:!0}];d.length&&d[0].radius&&l.reverse();l.forEach(function(b,a){d&&d[a]&&(l[a]=v(!1,d[a],b))});return l};c.prototype.predictBubbleSizes=function(){var b=this.chart,d=this.fontMetrics,a=b.legend.options,e="horizontal"===a.layout,c=e?b.legend.lastLineHeight:0,f=b.plotSizeX,l=b.plotSizeY,g=b.series[this.options.seriesIndex];
b=Math.ceil(g.minPxSize);var m=Math.ceil(g.maxPxSize);g=g.options.maxSize;var n=Math.min(l,f);if(a.floating||!/%$/.test(g))d=m;else if(g=parseFloat(g),d=(n+c-d.h/2)*g/100/(g/100+1),e&&l-d>=f||!e&&f-d>=l)d=m;return[b,Math.ceil(d)]};c.prototype.updateRanges=function(b,d){var a=this.legend.options.bubbleLegend;a.minSize=b;a.maxSize=d;a.ranges=this.getRanges()};c.prototype.correctSizes=function(){var b=this.legend,d=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(d.maxPxSize)-this.options.maxSize)&&
(this.updateRanges(this.options.minSize,d.maxPxSize),b.render())};return c}();f(u,"afterGetAllItems",function(a){var b=this.bubbleLegend,d=this.options,e=d.bubbleLegend,f=this.chart.getVisibleBubbleSeriesIndex();b&&b.ranges&&b.ranges.length&&(e.ranges.length&&(e.autoRanges=!!e.ranges[0].autoRanges),this.destroyItem(b));0<=f&&d.enabled&&e.enabled&&(e.seriesIndex=f,this.bubbleLegend=new c.BubbleLegend(e,this),this.bubbleLegend.addToLegend(a.allItems))});w.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=
this.series,b=0;b<a.length;){if(a[b]&&a[b].isBubble&&a[b].visible&&a[b].zData.length)return b;b++}return-1};u.prototype.getLinesHeights=function(){var a=this.allItems,b=[],d=a.length,e,c=0;for(e=0;e<d;e++)if(a[e].legendItemHeight&&(a[e].itemHeight=a[e].legendItemHeight),a[e]===a[d-1]||a[e+1]&&a[e]._legendItemPos[1]!==a[e+1]._legendItemPos[1]){b.push({height:0});var f=b[b.length-1];for(c;c<=e;c++)a[c].itemHeight>f.height&&(f.height=a[c].itemHeight);f.step=e}return b};u.prototype.retranslateItems=function(a){var b,
d,e,c=this.options.rtl,f=0;this.allItems.forEach(function(g,l){b=g.legendGroup.translateX;d=g._legendItemPos[1];if((e=g.movementX)||c&&g.ranges)e=c?b-g.options.maxSize/2:b+e,g.legendGroup.attr({translateX:e});l>a[f].step&&f++;g.legendGroup.attr({translateY:Math.round(d+a[f].height/2)});g._legendItemPos[1]=d+a[f].height/2})};f(A,"legendItemClick",function(){var a=this.chart,b=this.visible,d=this.chart.legend;d&&d.bubbleLegend&&(this.visible=!b,this.ignoreSeries=b,a=0<=a.getVisibleBubbleSeriesIndex(),
d.bubbleLegend.visible!==a&&(d.update({bubbleLegend:{enabled:a}}),d.bubbleLegend.visible=a),this.visible=b)});g(w.prototype,"drawChartBox",function(a,b,d){var e=this.legend,c=0<=this.getVisibleBubbleSeriesIndex();if(e&&e.options.enabled&&e.bubbleLegend&&e.options.bubbleLegend.autoRanges&&c){var f=e.bubbleLegend.options;c=e.bubbleLegend.predictBubbleSizes();e.bubbleLegend.updateRanges(c[0],c[1]);f.placed||(e.group.placed=!1,e.allItems.forEach(function(b){b.legendGroup.translateY=null}));e.render();
this.getMargins();this.axes.forEach(function(b){b.visible&&b.render();f.placed||(b.setScale(),b.updateNames(),t(b.ticks,function(b){b.isNew=!0;b.isNewLabel=!0}))});f.placed=!0;this.getMargins();a.call(this,b,d);e.bubbleLegend.correctSizes();e.retranslateItems(e.getLinesHeights())}else a.call(this,b,d),e&&e.options.enabled&&e.bubbleLegend&&(e.render(),e.retranslateItems(e.getLinesHeights()))});c.BubbleLegend=m;return c.BubbleLegend});x(f,"parts-more/BubbleSeries.js",[f["parts/Globals.js"],f["parts/Color.js"],
f["parts/Point.js"],f["parts/Utilities.js"]],function(c,f,u,k){var p=f.parse,h=k.arrayMax,q=k.arrayMin,y=k.clamp,v=k.extend,t=k.isNumber,a=k.pick,e=k.pInt;f=k.seriesType;k=c.Axis;var g=c.noop,A=c.Series,w=c.seriesTypes;f("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},
tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(a,e){var c=this.options.marker.fillOpacity;a=A.prototype.pointAttribs.call(this,a,e);1!==c&&(a.fill=p(a.fill).setOpacity(c).get("rgba"));return a},getRadii:function(a,e,c){var b=this.zData,d=this.yData,
f=c.minPxSize,g=c.maxPxSize,m=[];var l=0;for(c=b.length;l<c;l++){var n=b[l];m.push(this.getRadius(a,e,f,g,n,d[l]))}this.radii=m},getRadius:function(a,e,c,b,d,f){var g=this.options,m="width"!==g.sizeBy,l=g.zThreshold,h=e-a,n=.5;if(null===f||null===d)return null;if(t(d)){g.sizeByAbsoluteValue&&(d=Math.abs(d-l),h=Math.max(e-l,Math.abs(a-l)),a=0);if(d<a)return c/2-1;0<h&&(n=(d-a)/h)}m&&0<=n&&(n=Math.sqrt(n));return Math.ceil(c+n*(b-c))/2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&
this.points.forEach(function(a){var e=a.graphic;if(e&&e.width){var b={x:e.x,y:e.y,width:e.width,height:e.height};e.attr({x:a.plotX,y:a.plotY,width:1,height:1});e.animate(b,this.options.animation)}},this)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,e=this.data,c=this.radii;w.scatter.prototype.translate.call(this);for(a=e.length;a--;){var b=e[a];var d=c?c[a]:0;t(d)&&d>=this.minPxSize/2?(b.marker=v(b.marker,{radius:d,width:2*d,height:2*d}),b.dlBox={x:b.plotX-d,
y:b.plotY-d,width:2*d,height:2*d}):b.shapeArgs=b.plotY=b.dlBox=void 0}},alignDataLabel:w.column.prototype.alignDataLabel,buildKDTree:g,applyZones:g},{haloPath:function(a){return u.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});k.prototype.beforePadding=function(){var c=this,f=this.len,g=this.chart,b=0,d=f,k=this.isXAxis,p=k?"xData":"yData",w=this.min,A={},u=Math.min(g.plotWidth,g.plotHeight),v=Number.MAX_VALUE,x=-Number.MAX_VALUE,C=this.max-w,E=f/C,F=[];
this.series.forEach(function(b){var d=b.options;!b.bubblePadding||!b.visible&&g.options.chart.ignoreHiddenSeries||(c.allowZoomOutside=!0,F.push(b),k&&(["minSize","maxSize"].forEach(function(b){var a=d[b],c=/%$/.test(a);a=e(a);A[b]=c?u*a/100:a}),b.minPxSize=A.minSize,b.maxPxSize=Math.max(A.maxSize,A.minSize),b=b.zData.filter(t),b.length&&(v=a(d.zMin,y(q(b),!1===d.displayNegative?d.zThreshold:-Number.MAX_VALUE,v)),x=a(d.zMax,Math.max(x,h(b))))))});F.forEach(function(a){var e=a[p],f=e.length;k&&a.getRadii(v,
x,a);if(0<C)for(;f--;)if(t(e[f])&&c.dataMin<=e[f]&&e[f]<=c.max){var g=a.radii?a.radii[f]:0;b=Math.min((e[f]-w)*E-g,b);d=Math.max((e[f]-w)*E+g,d)}});F.length&&0<C&&!this.isLog&&(d-=f,E*=(f+Math.max(0,b)-Math.min(d,f))/f,[["min","userMin",b],["max","userMax",d]].forEach(function(b){"undefined"===typeof a(c.options[b[0]],c[b[1]])&&(c[b[0]]+=b[2]/E)}))};""});x(f,"parts-map/MapBubbleSeries.js",[f["parts/Globals.js"],f["parts/Point.js"],f["parts/Utilities.js"]],function(c,f,u){var k=u.merge;u=u.seriesType;
var p=c.seriesTypes;p.bubble&&u("mapbubble","bubble",{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}},{xyFromShape:!0,type:"mapbubble",pointArrayMap:["z"],getMapData:p.map.prototype.getMapData,getBox:p.map.prototype.getBox,setData:p.map.prototype.setData,setOptions:p.map.prototype.setOptions},{applyOptions:function(c,q){return c&&"undefined"!==typeof c.lat&&"undefined"!==typeof c.lon?f.prototype.applyOptions.call(this,k(c,this.series.chart.fromLatLonToPoint(c)),q):p.map.prototype.pointClass.prototype.applyOptions.call(this,
c,q)},isValid:function(){return"number"===typeof this.z},ttBelow:!1});""});x(f,"parts-map/HeatmapSeries.js",[f["parts/Globals.js"],f["mixins/legend-symbol.js"],f["parts/Utilities.js"]],function(c,f,u){var k=u.clamp,p=u.extend,h=u.fireEvent,q=u.merge,x=u.pick;u=u.seriesType;var v=c.colorMapPointMixin,t=c.Series,a=c.SVGRenderer.prototype.symbols;u("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){return this.point.value},inside:!0,verticalAlign:"middle",
crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}},q(c.colorMapSeriesMixin,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){t.prototype.init.apply(this,arguments);var e=this.options;e.pointRange=x(e.pointRange,e.colsize||1);this.yAxis.axisPointRange=
e.rowsize||1;p(a,{ellipse:a.circle,rect:a.square})},getSymbol:t.prototype.getSymbol,setClip:function(a){var e=this.chart;t.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&this.sharedClipKey?e[this.sharedClipKey]:e.clipRect)},translate:function(){var e=this.options,c=e.marker&&e.marker.symbol||"",f=a[c]?c:"rect";e=this.options;var k=-1!==["circle","square"].indexOf(f);this.generatePoints();this.points.forEach(function(e){var g=e.getCellAttributes(),
l={x:Math.min(g.x1,g.x2),y:Math.min(g.y1,g.y2),width:Math.max(Math.abs(g.x2-g.x1),0),height:Math.max(Math.abs(g.y2-g.y1),0)};var b=e.hasImage=0===(e.marker&&e.marker.symbol||c||"").indexOf("url");if(k){var d=Math.abs(l.width-l.height);l.x=Math.min(g.x1,g.x2)+(l.width<l.height?0:d/2);l.y=Math.min(g.y1,g.y2)+(l.width<l.height?d/2:0);l.width=l.height=Math.min(l.width,l.height)}d={plotX:(g.x1+g.x2)/2,plotY:(g.y1+g.y2)/2,clientX:(g.x1+g.x2)/2,shapeType:"path",shapeArgs:q(!0,l,{d:a[f](l.x,l.y,l.width,l.height)})};
b&&(e.marker={width:l.width,height:l.height});p(e,d)});h(this,"afterTranslate")},pointAttribs:function(a,f){var e=t.prototype.pointAttribs.call(this,a,f),g=this.options||{},h=this.chart.options.plotOptions||{},m=h.series||{},l=h.heatmap||{};h=g.borderColor||l.borderColor||m.borderColor;m=g.borderWidth||l.borderWidth||m.borderWidth||e["stroke-width"];e.stroke=a&&a.marker&&a.marker.lineColor||g.marker&&g.marker.lineColor||h||this.color;e["stroke-width"]=m;f&&(a=q(g.states[f],g.marker&&g.marker.states[f],
a.options.states&&a.options.states[f]||{}),f=a.brightness,e.fill=a.color||c.color(e.fill).brighten(f||0).get(),e.stroke=a.lineColor);return e},markerAttribs:function(a,c){var e=a.marker||{},f=this.options.marker||{},g=a.shapeArgs||{},h={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(c){var l=f.states[c]||{};var b=e.states&&e.states[c]||{};[["width","x"],["height","y"]].forEach(function(a){h[a[0]]=(b[a[0]]||l[a[0]]||g[a[0]])+(b[a[0]+"Plus"]||l[a[0]+"Plus"]||0);h[a[1]]=g[a[1]]+(g[a[0]]-h[a[0]])/2})}return c?
h:g},drawPoints:function(){var a=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)t.prototype.drawPoints.call(this),this.points.forEach(function(e){e.graphic&&e.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(e))})},hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,c){return t.prototype.getValidPoints.call(this,a,c,!0)},getBox:c.noop,drawLegendSymbol:f.drawRectangle,alignDataLabel:c.seriesTypes.column.prototype.alignDataLabel,getExtremes:function(){t.prototype.getExtremes.call(this,
this.valueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;t.prototype.getExtremes.call(this)}}),q(v,{applyOptions:function(a,f){a=c.Point.prototype.applyOptions.call(this,a,f);a.formatPrefix=a.isNull||null===a.value?"null":"point";return a},isValid:function(){return Infinity!==this.value&&-Infinity!==this.value},haloPath:function(a){if(!a)return[];var e=this.shapeArgs;return["M",e.x-a,e.y-a,"L",e.x-a,e.y+e.height+a,e.x+e.width+a,e.y+e.height+a,e.x+e.width+a,e.y-a,"Z"]},getCellAttributes:function(){var a=
this.series,c=a.options,f=(c.colsize||1)/2,h=(c.rowsize||1)/2,n=a.xAxis,m=a.yAxis,l=this.options.marker||a.options.marker;a=a.pointPlacementToXValue();var b=x(this.pointPadding,c.pointPadding,0),d={x1:k(Math.round(n.len-(n.translate(this.x-f,!1,!0,!1,!0,-a)||0)),-n.len,2*n.len),x2:k(Math.round(n.len-(n.translate(this.x+f,!1,!0,!1,!0,-a)||0)),-n.len,2*n.len),y1:k(Math.round(m.translate(this.y-h,!1,!0,!1,!0)||0),-m.len,2*m.len),y2:k(Math.round(m.translate(this.y+h,!1,!0,!1,!0)||0),-m.len,2*m.len)};
[["width","x"],["height","y"]].forEach(function(a){var e=a[0];a=a[1];var c=a+"1",f=a+"2",g=Math.abs(d[c]-d[f]),h=l&&l.lineWidth||0,m=Math.abs(d[c]+d[f])/2;l[e]&&l[e]<g&&(d[c]=m-l[e]/2-h/2,d[f]=m+l[e]/2+h/2);b&&("y"===a&&(c=f,f=a+"1"),d[c]+=b,d[f]-=b)});return d}}));""});x(f,"parts-map/GeoJSON.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,f){function q(c,a){var e,f=!1,h=c.x,k=c.y;c=0;for(e=a.length-1;c<a.length;e=c++){var n=a[c][1]>k;var m=a[e][1]>k;n!==m&&h<(a[e][0]-a[c][0])*(k-a[c][1])/
(a[e][1]-a[c][1])+a[c][0]&&(f=!f)}return f}var k=f.error,p=f.extend,h=f.format,x=f.merge;f=f.wrap;var y=c.Chart,v=c.win;y.prototype.transformFromLatLon=function(c,a){var e,f=(null===(e=this.userOptions.chart)||void 0===e?void 0:e.proj4)||v.proj4;if(!f)return k(21,!1,this),{x:0,y:null};c=f(a.crs,[c.lon,c.lat]);e=a.cosAngle||a.rotation&&Math.cos(a.rotation);f=a.sinAngle||a.rotation&&Math.sin(a.rotation);c=a.rotation?[c[0]*e+c[1]*f,-c[0]*f+c[1]*e]:c;return{x:((c[0]-(a.xoffset||0))*(a.scale||1)+(a.xpan||
0))*(a.jsonres||1)+(a.jsonmarginX||0),y:(((a.yoffset||0)-c[1])*(a.scale||1)+(a.ypan||0))*(a.jsonres||1)-(a.jsonmarginY||0)}};y.prototype.transformToLatLon=function(c,a){if("undefined"===typeof v.proj4)k(21,!1,this);else{c={x:((c.x-(a.jsonmarginX||0))/(a.jsonres||1)-(a.xpan||0))/(a.scale||1)+(a.xoffset||0),y:((-c.y-(a.jsonmarginY||0))/(a.jsonres||1)+(a.ypan||0))/(a.scale||1)+(a.yoffset||0)};var e=a.cosAngle||a.rotation&&Math.cos(a.rotation),f=a.sinAngle||a.rotation&&Math.sin(a.rotation);a=v.proj4(a.crs,
"WGS84",a.rotation?{x:c.x*e+c.y*-f,y:c.x*f+c.y*e}:c);return{lat:a.y,lon:a.x}}};y.prototype.fromPointToLatLon=function(c){var a=this.mapTransforms,e;if(a){for(e in a)if(Object.hasOwnProperty.call(a,e)&&a[e].hitZone&&q({x:c.x,y:-c.y},a[e].hitZone.coordinates[0]))return this.transformToLatLon(c,a[e]);return this.transformToLatLon(c,a["default"])}k(22,!1,this)};y.prototype.fromLatLonToPoint=function(c){var a=this.mapTransforms,e;if(!a)return k(22,!1,this),{x:0,y:null};for(e in a)if(Object.hasOwnProperty.call(a,
e)&&a[e].hitZone){var f=this.transformFromLatLon(c,a[e]);if(q({x:f.x,y:-f.y},a[e].hitZone.coordinates[0]))return f}return this.transformFromLatLon(c,a["default"])};c.geojson=function(c,a,e){var f=[],k=[],q=function(a){var c,e=a.length;k.push("M");for(c=0;c<e;c++)1===c&&k.push("L"),k.push(a[c][0],-a[c][1])};a=a||"map";c.features.forEach(function(c){var e=c.geometry,g=e.type;e=e.coordinates;c=c.properties;var b;k=[];"map"===a||"mapbubble"===a?("Polygon"===g?(e.forEach(q),k.push("Z")):"MultiPolygon"===
g&&(e.forEach(function(a){a.forEach(q)}),k.push("Z")),k.length&&(b={path:k})):"mapline"===a?("LineString"===g?q(e):"MultiLineString"===g&&e.forEach(q),k.length&&(b={path:k})):"mappoint"===a&&"Point"===g&&(b={x:e[0],y:-e[1]});b&&f.push(p(b,{name:c.name||c.NAME,properties:c}))});e&&c.copyrightShort&&(e.chart.mapCredits=h(e.chart.options.credits.mapText,{geojson:c}),e.chart.mapCreditsFull=h(e.chart.options.credits.mapTextFull,{geojson:c}));return f};f(y.prototype,"addCredits",function(c,a){a=x(!0,this.options.credits,
a);this.mapCredits&&(a.href=null);c.call(this,a);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});x(f,"parts-map/Map.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,f){function q(a,c,f,h,k,n,m,l){return["M",a+k,c,"L",a+f-n,c,"C",a+f-n/2,c,a+f,c+n/2,a+f,c+n,"L",a+f,c+h-m,"C",a+f,c+h-m/2,a+f-m/2,c+h,a+f-m,c+h,"L",a+l,c+h,"C",a+l/2,c+h,a,c+h-l/2,a,c+h-l,"L",a,c+k,"C",a,c+k/2,a+k/2,c,a+k,c,"Z"]}var k=f.extend,p=f.merge,h=f.pick,x=c.Chart;f=c.defaultOptions;
var y=c.Renderer,v=c.SVGRenderer,t=c.VMLRenderer;k(f.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});f.mapNavigation={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};c.splitPath=function(a){var c;a=a.replace(/([A-Za-z])/g,
" $1 ");a=a.replace(/^\s*/,"").replace(/\s*$/,"");a=a.split(/[ ,]+/);for(c=0;c<a.length;c++)/[a-zA-Z]/.test(a[c])||(a[c]=parseFloat(a[c]));return a};c.maps={};v.prototype.symbols.topbutton=function(a,c,f,h,k){return q(a-1,c-1,f,h,k.r,k.r,0,0)};v.prototype.symbols.bottombutton=function(a,c,f,h,k){return q(a-1,c-1,f,h,0,0,k.r,k.r)};y===t&&["topbutton","bottombutton"].forEach(function(a){t.prototype.symbols[a]=v.prototype.symbols[a]});c.Map=c.mapChart=function(a,e,f){var g="string"===typeof a||a.nodeName,
k=arguments[g?1:0],n=k,m={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,startOnTick:!1},l=c.getOptions().credits;var b=k.series;k.series=null;k=p({chart:{panning:"xy",type:"map"},credits:{mapText:h(l.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:h(l.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},xAxis:m,yAxis:p(m,{reversed:!0})},k,{chart:{inverted:!1,alignTicks:!1}});k.series=n.series=b;return g?new x(a,k,f):new x(k,e)}});x(f,"masters/modules/map.src.js",
[],function(){})});
//# sourceMappingURL=map.js.map