/*
 Highstock JS v8.0.4 (2020-03-19)

 Highstock as a plugin for Highcharts

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(n){"object"===typeof module&&module.exports?(n["default"]=n,module.exports=n):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(G){n(G);n.Highcharts=G;return n}):n("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(n){function G(v,h,n,e){v.hasOwnProperty(h)||(v[h]=e.apply(null,n))}n=n?n._modules:{};G(n,"parts/ScrollbarAxis.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(v,h){var n=h.addEvent,e=h.defined,A=h.pick;return function(){function h(){}
h.init=function(h,t){n(h,"afterInit",function(){var g=this;g.options&&g.options.scrollbar&&g.options.scrollbar.enabled&&(g.options.scrollbar.vertical=!g.horiz,g.options.startOnTick=g.options.endOnTick=!1,g.scrollbar=new t(g.chart.renderer,g.options.scrollbar,g.chart),n(g.scrollbar,"changed",function(h){var t=Math.min(A(g.options.min,g.min),g.min,g.dataMin),B=Math.max(A(g.options.max,g.max),g.max,g.dataMax)-t;if(g.horiz&&!g.reversed||!g.horiz&&g.reversed){var z=t+B*this.to;t+=B*this.from}else z=t+
B*(1-this.from),t+=B*(1-this.to);A(this.options.liveRedraw,v.svg&&!v.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===h.DOMType||!e(h.DOMType)?g.setExtremes(t,z,!0,"mousemove"!==h.DOMType,h):this.setRange(this.from,this.to)}))});n(h,"afterRender",function(){var g=Math.min(A(this.options.min,this.min),this.min,A(this.dataMin,this.min)),h=Math.max(A(this.options.max,this.max),this.max,A(this.dataMax,this.max)),t=this.scrollbar,B=this.axisTitleMargin+(this.titleOffset||0),z=this.chart.scrollbarsOffsets,
C=this.options.margin||0;t&&(this.horiz?(this.opposite||(z[1]+=B),t.position(this.left,this.top+this.height+2+z[1]-(this.opposite?C:0),this.width,this.height),this.opposite||(z[1]+=C),B=1):(this.opposite&&(z[0]+=B),t.position(this.left+this.width+2+z[0]-(this.opposite?0:C),this.top,this.width,this.height),this.opposite&&(z[0]+=C),B=0),z[B]+=t.size+t.options.margin,isNaN(g)||isNaN(h)||!e(this.min)||!e(this.max)||this.min===this.max?t.setRange(0,1):(z=(this.min-g)/(h-g),g=(this.max-g)/(h-g),this.horiz&&
!this.reversed||!this.horiz&&this.reversed?t.setRange(z,g):t.setRange(1-g,1-z)))});n(h,"afterGetOffset",function(){var g=this.horiz?2:1,e=this.scrollbar;e&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[g]+=e.size+e.options.margin)})};return h}()});G(n,"parts/Scrollbar.js",[n["parts/Axis.js"],n["parts/Globals.js"],n["parts/ScrollbarAxis.js"],n["parts/Utilities.js"]],function(n,h,I,e){var A=e.addEvent,v=e.correctFloat,D=e.defined,t=e.destroyObjectProperties,g=e.fireEvent,E=e.merge,F=e.pick,
B=e.removeEvent;e=h.defaultOptions;var z=h.hasTouch,C=h.isTouchDevice,y=h.swapXY=function(d,b){var u=d.length;if(b)for(b=0;b<u;b+=3){var a=d[b+1];d[b+1]=d[b+2];d[b+2]=a}return d},m=function(){function d(b,u,a){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=
1;this.userOptions={};this.y=this.x=0;this.chart=a;this.options=u;this.renderer=a.renderer;this.init(b,u,a)}d.prototype.addEvents=function(){var b=this.options.inverted?[1,0]:[0,1],u=this.scrollbarButtons,a=this.scrollbarGroup.element,l=this.track.element,k=this.mouseDownHandler.bind(this),q=this.mouseMoveHandler.bind(this),d=this.mouseUpHandler.bind(this);b=[[u[b[0]].element,"click",this.buttonToMinClick.bind(this)],[u[b[1]].element,"click",this.buttonToMaxClick.bind(this)],[l,"click",this.trackClick.bind(this)],
[a,"mousedown",k],[a.ownerDocument,"mousemove",q],[a.ownerDocument,"mouseup",d]];z&&b.push([a,"touchstart",k],[a.ownerDocument,"touchmove",q],[a.ownerDocument,"touchend",d]);b.forEach(function(a){A.apply(null,a)});this._events=b};d.prototype.buttonToMaxClick=function(b){var u=(this.to-this.from)*F(this.options.step,.2);this.updatePosition(this.from+u,this.to+u);g(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};d.prototype.buttonToMinClick=function(b){var u=v(this.to-this.from)*
F(this.options.step,.2);this.updatePosition(v(this.from-u),v(this.to-u));g(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};d.prototype.cursorToScrollbarPosition=function(b){var u=this.options;u=u.minWidth>this.calculatedWidth?u.minWidth:0;return{chartX:(b.chartX-this.x-this.xOffset)/(this.barWidth-u),chartY:(b.chartY-this.y-this.yOffset)/(this.barWidth-u)}};d.prototype.destroy=function(){var b=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar",
"scrollbarGroup","group"].forEach(function(b){this[b]&&this[b].destroy&&(this[b]=this[b].destroy())},this);b&&this===b.scrollbar&&(b.scrollbar=null,t(b.scrollbarButtons))};d.prototype.drawScrollbarButton=function(b){var d=this.renderer,a=this.scrollbarButtons,l=this.options,k=this.size;var q=d.g().add(this.group);a.push(q);q=d.rect().addClass("highcharts-scrollbar-button").add(q);this.chart.styledMode||q.attr({stroke:l.buttonBorderColor,"stroke-width":l.buttonBorderWidth,fill:l.buttonBackgroundColor});
q.attr(q.crisp({x:-.5,y:-.5,width:k+1,height:k+1,r:l.buttonBorderRadius},q.strokeWidth()));q=d.path(y(["M",k/2+(b?-1:1),k/2-3,"L",k/2+(b?-1:1),k/2+3,"L",k/2+(b?2:-2),k/2],l.vertical)).addClass("highcharts-scrollbar-arrow").add(a[b]);this.chart.styledMode||q.attr({fill:l.buttonArrowColor})};d.prototype.init=function(b,u,a){this.scrollbarButtons=[];this.renderer=b;this.userOptions=u;this.options=E(d.defaultOptions,u);this.chart=a;this.size=F(this.options.size,this.options.height);u.enabled&&(this.render(),
this.addEvents())};d.prototype.mouseDownHandler=function(b){b=this.chart.pointer.normalize(b);b=this.cursorToScrollbarPosition(b);this.chartX=b.chartX;this.chartY=b.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};d.prototype.mouseMoveHandler=function(b){var d=this.chart.pointer.normalize(b),a=this.options.vertical?"chartY":"chartX",l=this.initPositions||[];!this.grabbedCenter||b.touches&&0===b.touches[0][a]||(d=this.cursorToScrollbarPosition(d)[a],a=this[a],a=d-a,this.hasDragged=
!0,this.updatePosition(l[0]+a,l[1]+a),this.hasDragged&&g(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b}))};d.prototype.mouseUpHandler=function(b){this.hasDragged&&g(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};d.prototype.position=function(b,d,a,l){var k=this.options.vertical,q=0,u=this.rendered?"animate":"attr";this.x=b;this.y=d+this.trackBorderWidth;
this.width=a;this.xOffset=this.height=l;this.yOffset=q;k?(this.width=this.yOffset=a=q=this.size,this.xOffset=d=0,this.barWidth=l-2*a,this.x=b+=this.options.margin):(this.height=this.xOffset=l=d=this.size,this.barWidth=a-2*l,this.y+=this.options.margin);this.group[u]({translateX:b,translateY:this.y});this.track[u]({width:a,height:l});this.scrollbarButtons[1][u]({translateX:k?0:a-d,translateY:k?l-q:0})};d.prototype.removeEvents=function(){this._events.forEach(function(b){B.apply(null,b)});this._events.length=
0};d.prototype.render=function(){var b=this.renderer,d=this.options,a=this.size,l=this.chart.styledMode,k;this.group=k=b.g("scrollbar").attr({zIndex:d.zIndex,translateY:-99999}).add();this.track=b.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:d.trackBorderRadius||0,height:a,width:a}).add(k);l||this.track.attr({fill:d.trackBackgroundColor,stroke:d.trackBorderColor,"stroke-width":d.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%
2/2});this.scrollbarGroup=b.g().add(k);this.scrollbar=b.rect().addClass("highcharts-scrollbar-thumb").attr({height:a,width:a,r:d.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=b.path(y(["M",-3,a/4,"L",-3,2*a/3,"M",0,a/4,"L",0,2*a/3,"M",3,a/4,"L",3,2*a/3],d.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);l||(this.scrollbar.attr({fill:d.barBackgroundColor,stroke:d.barBorderColor,"stroke-width":d.barBorderWidth}),this.scrollbarRifles.attr({stroke:d.rifleColor,
"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};d.prototype.setRange=function(b,d){var a=this.options,l=a.vertical,k=a.minWidth,q=this.barWidth,w,u=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(D(q)){b=Math.max(b,0);var p=Math.ceil(q*b);this.calculatedWidth=w=v(q*
Math.min(d,1)-p);w<k&&(p=(q-k+w)*b,w=k);k=Math.floor(p+this.xOffset+this.yOffset);q=w/2-.5;this.from=b;this.to=d;l?(this.scrollbarGroup[u]({translateY:k}),this.scrollbar[u]({height:w}),this.scrollbarRifles[u]({translateY:q}),this.scrollbarTop=k,this.scrollbarLeft=0):(this.scrollbarGroup[u]({translateX:k}),this.scrollbar[u]({width:w}),this.scrollbarRifles[u]({translateX:q}),this.scrollbarLeft=k,this.scrollbarTop=0);12>=w?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===a.showFull&&(0>=
b&&1<=d?this.group.hide():this.group.show());this.rendered=!0}};d.prototype.trackClick=function(b){var d=this.chart.pointer.normalize(b),a=this.to-this.from,l=this.y+this.scrollbarTop,k=this.x+this.scrollbarLeft;this.options.vertical&&d.chartY>l||!this.options.vertical&&d.chartX>k?this.updatePosition(this.from+a,this.to+a):this.updatePosition(this.from-a,this.to-a);g(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};d.prototype.update=function(b){this.destroy();this.init(this.chart.renderer,
E(!0,this.options,b),this.chart)};d.prototype.updatePosition=function(b,d){1<d&&(b=v(1-v(d-b)),d=1);0>b&&(d=v(d-b),b=0);this.from=b;this.to=d};d.defaultOptions={height:C?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",
trackBorderColor:"#f2f2f2",trackBorderWidth:1};return d}();h.Scrollbar||(e.scrollbar=E(!0,m.defaultOptions,e.scrollbar),h.Scrollbar=m,I.init(n,m));return h.Scrollbar});G(n,"parts/Navigator.js",[n["parts/Globals.js"],n["parts/Color.js"],n["parts/Scrollbar.js"],n["parts/Utilities.js"]],function(v,h,n,e){h=h.parse;var A=e.addEvent,H=e.clamp,D=e.correctFloat,t=e.defined,g=e.destroyObjectProperties,E=e.erase,F=e.extend,B=e.find,z=e.isArray,C=e.isNumber,y=e.merge,m=e.pick,d=e.removeEvent,b=e.splat,u=v.Axis;
e=v.Chart;var a=v.defaultOptions,l=v.hasTouch,k=v.isTouchDevice,q=v.Series,w=function(c){for(var f=[],r=1;r<arguments.length;r++)f[r-1]=arguments[r];f=[].filter.call(f,C);if(f.length)return Math[c].apply(0,f)};var M="undefined"===typeof v.seriesTypes.areaspline?"line":"areaspline";F(a,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:h("#6685c2").setOpacity(.3).get(),
outlineColor:"#cccccc",outlineWidth:1,series:{type:M,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},
threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});v.Renderer.prototype.symbols["navigator-handle"]=function(c,f,r,a,b){c=b.width/
2;f=Math.round(c/3)+.5;b=b.height;return["M",-c-1,.5,"L",c,.5,"L",c,b+.5,"L",-c-1,b+.5,"L",-c-1,.5,"M",-f,4,"L",-f,b-3,"M",f-1,4,"L",f-1,b-3]};u.prototype.toFixedRange=function(c,f,r,a){var x=this.chart&&this.chart.fixedRange,b=(this.pointRange||0)/2;c=m(r,this.translate(c,!0,!this.horiz));f=m(a,this.translate(f,!0,!this.horiz));var k=x&&(f-c)/x;t(r)||(c=D(c+b));t(a)||(f=D(f-b));.7<k&&1.3>k&&(a?c=f-x:f=c+x);C(c)&&C(f)||(c=f=void 0);return{min:c,max:f}};var p=function(){function c(f){this.zoomedMin=
this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(f)}c.prototype.drawHandle=function(f,r,c,a){var x=this.navigatorOptions.handles.height;this.handles[r][a](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+
parseInt(f,10)+.5-x)}:{translateX:Math.round(this.left+parseInt(f,10)),translateY:Math.round(this.top+this.height/2-x/2-1)})};c.prototype.drawOutline=function(f,r,c,a){var b=this.navigatorOptions.maskInside,x=this.outline.strokeWidth(),k=x/2;x=x%2/2;var d=this.outlineHeight,l=this.scrollbarHeight,J=this.size,p=this.left-l,q=this.top;c?(p-=k,c=q+r+x,r=q+f+x,f=["M",p+d,q-l-x,"L",p+d,c,"L",p,c,"L",p,r,"L",p+d,r,"L",p+d,q+J+l].concat(b?["M",p+d,c-k,"L",p+d,r+k]:[])):(f+=p+l-x,r+=p+l-x,q+=k,f=["M",p,q,
"L",f,q,"L",f,q+d,"L",r,q+d,"L",r,q,"L",p+J+2*l,q].concat(b?["M",f-k,q,"L",r+k,q]:[]));this.outline[a]({d:f})};c.prototype.drawMasks=function(f,r,c,a){var x=this.left,b=this.top,k=this.height;if(c){var d=[x,x,x];var l=[b,b+f,b+r];var p=[k,k,k];var q=[f,r-f,this.size-r]}else d=[x,x+f,x+r],l=[b,b,b],p=[f,r-f,this.size-r],q=[k,k,k];this.shades.forEach(function(f,r){f[a]({x:d[r],y:l[r],width:p[r],height:q[r]})})};c.prototype.renderElements=function(){var f=this,r=f.navigatorOptions,c=r.maskInside,a=f.chart,
b=a.renderer,k,d={cursor:a.inverted?"ns-resize":"ew-resize"};f.navigatorGroup=k=b.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,x){f.shades[x]=b.rect().addClass("highcharts-navigator-mask"+(1===x?"-inside":"-outside")).add(k);a.styledMode||f.shades[x].attr({fill:c?r.maskFill:"rgba(0,0,0,0)"}).css(1===x&&d)});f.outline=b.path().addClass("highcharts-navigator-outline").add(k);a.styledMode||f.outline.attr({"stroke-width":r.outlineWidth,stroke:r.outlineColor});
r.handles.enabled&&[0,1].forEach(function(c){r.handles.inverted=a.inverted;f.handles[c]=b.symbol(r.handles.symbols[c],-r.handles.width/2-1,0,r.handles.width,r.handles.height,r.handles);f.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][c]).add(k);if(!a.styledMode){var x=r.handles;f.handles[c].attr({fill:x.backgroundColor,stroke:x.borderColor,"stroke-width":x.lineWidth}).css(d)}})};c.prototype.update=function(f){(this.series||[]).forEach(function(f){f.baseSeries&&
delete f.baseSeries.navigatorSeries});this.destroy();y(!0,this.chart.options.navigator,this.options,f);this.init(this.chart)};c.prototype.render=function(f,r,c,a){var b=this.chart,x=this.scrollbarHeight,k,d=this.xAxis,l=d.pointRange||0;var p=d.fake?b.xAxis[0]:d;var q=this.navigatorEnabled,J,w=this.rendered;var u=b.inverted;var z=b.xAxis[0].minRange,g=b.xAxis[0].options.maxRange;if(!this.hasDragged||t(c)){f=D(f-l/2);r=D(r+l/2);if(!C(f)||!C(r))if(w)c=0,a=m(d.width,p.width);else return;this.left=m(d.left,
b.plotLeft+x+(u?b.plotWidth:0));this.size=J=k=m(d.len,(u?b.plotHeight:b.plotWidth)-2*x);b=u?x:k+2*x;c=m(c,d.toPixels(f,!0));a=m(a,d.toPixels(r,!0));C(c)&&Infinity!==Math.abs(c)||(c=0,a=b);f=d.toValue(c,!0);r=d.toValue(a,!0);var e=Math.abs(D(r-f));e<z?this.grabbedLeft?c=d.toPixels(r-z-l,!0):this.grabbedRight&&(a=d.toPixels(f+z+l,!0)):t(g)&&D(e-l)>g&&(this.grabbedLeft?c=d.toPixels(r-g-l,!0):this.grabbedRight&&(a=d.toPixels(f+g+l,!0)));this.zoomedMax=H(Math.max(c,a),0,J);this.zoomedMin=H(this.fixedWidth?
this.zoomedMax-this.fixedWidth:Math.min(c,a),0,J);this.range=this.zoomedMax-this.zoomedMin;J=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);q&&(this.navigatorGroup.attr({visibility:"visible"}),w=w&&!this.hasDragged?"animate":"attr",this.drawMasks(c,J,u,w),this.drawOutline(c,J,u,w),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,u,w),this.drawHandle(J,1,u,w)));this.scrollbar&&(u?(u=this.top-x,p=this.left-x+(q||!p.opposite?0:(p.titleOffset||0)+p.axisTitleMargin),x=k+2*x):(u=this.top+
(q?this.height:-x),p=this.left-x),this.scrollbar.position(p,u,b,x),this.scrollbar.setRange(this.zoomedMin/(k||1),this.zoomedMax/(k||1)));this.rendered=!0}};c.prototype.addMouseEvents=function(){var f=this,r=f.chart,c=r.container,a=[],b,k;f.mouseMoveHandler=b=function(r){f.onMouseMove(r)};f.mouseUpHandler=k=function(r){f.onMouseUp(r)};a=f.getPartsEvents("mousedown");a.push(A(r.renderTo,"mousemove",b),A(c.ownerDocument,"mouseup",k));l&&(a.push(A(r.renderTo,"touchmove",b),A(c.ownerDocument,"touchend",
k)),a.concat(f.getPartsEvents("touchstart")));f.eventsToUnbind=a;f.series&&f.series[0]&&a.push(A(f.series[0].xAxis,"foundExtremes",function(){r.navigator.modifyNavigatorAxisExtremes()}))};c.prototype.getPartsEvents=function(f){var r=this,c=[];["shades","handles"].forEach(function(a){r[a].forEach(function(b,x){c.push(A(b.element,f,function(f){r[a+"Mousedown"](f,x)}))})});return c};c.prototype.shadesMousedown=function(f,r){f=this.chart.pointer.normalize(f);var c=this.chart,a=this.xAxis,b=this.zoomedMin,
k=this.left,d=this.size,l=this.range,p=f.chartX;c.inverted&&(p=f.chartY,k=this.top);if(1===r)this.grabbedCenter=p,this.fixedWidth=l,this.dragOffset=p-b;else{f=p-k-l/2;if(0===r)f=Math.max(0,f);else if(2===r&&f+l>=d)if(f=d-l,this.reversedExtremes){f-=l;var q=this.getUnionExtremes().dataMin}else var w=this.getUnionExtremes().dataMax;f!==b&&(this.fixedWidth=l,r=a.toFixedRange(f,f+l,q,w),t(r.min)&&c.xAxis[0].setExtremes(Math.min(r.min,r.max),Math.max(r.min,r.max),!0,null,{trigger:"navigator"}))}};c.prototype.handlesMousedown=
function(f,r){this.chart.pointer.normalize(f);f=this.chart;var c=f.xAxis[0],a=this.reversedExtremes;0===r?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=a?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=a?c.max:c.min);f.fixedRange=null};c.prototype.onMouseMove=function(f){var c=this,a=c.chart,b=c.left,d=c.navigatorSize,l=c.range,p=c.dragOffset,q=a.inverted;f.touches&&0===f.touches[0].pageX||(f=a.pointer.normalize(f),a=f.chartX,q&&
(b=c.top,a=f.chartY),c.grabbedLeft?(c.hasDragged=!0,c.render(0,0,a-b,c.otherHandlePos)):c.grabbedRight?(c.hasDragged=!0,c.render(0,0,c.otherHandlePos,a-b)):c.grabbedCenter&&(c.hasDragged=!0,a<p?a=p:a>d+p-l&&(a=d+p-l),c.render(0,0,a-p,a-p+l)),c.hasDragged&&c.scrollbar&&m(c.scrollbar.options.liveRedraw,v.svg&&!k&&!this.chart.isBoosting)&&(f.DOMType=f.type,setTimeout(function(){c.onMouseUp(f)},0)))};c.prototype.onMouseUp=function(f){var c=this.chart,a=this.xAxis,b=this.scrollbar,k=f.DOMEvent||f,d=c.inverted,
l=this.rendered&&!this.hasDragged?"animate":"attr",p=Math.round(this.zoomedMax),q=Math.round(this.zoomedMin);if(this.hasDragged&&(!b||!b.hasDragged)||"scrollbar"===f.trigger){b=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var w=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var u=this.fixedExtreme;this.zoomedMax===this.size&&(u=this.reversedExtremes?b.dataMin:b.dataMax);0===this.zoomedMin&&(w=this.reversedExtremes?b.dataMax:b.dataMin);a=a.toFixedRange(this.zoomedMin,
this.zoomedMax,w,u);t(a.min)&&c.xAxis[0].setExtremes(Math.min(a.min,a.max),Math.max(a.min,a.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:k})}"mousemove"!==f.DOMType&&"touchmove"!==f.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&(this.shades&&this.drawMasks(q,p,d,l),this.outline&&this.drawOutline(q,p,d,l),this.navigatorOptions.handles.enabled&&
Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(q,0,d,l),this.drawHandle(p,1,d,l)))};c.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(f){f()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};c.prototype.removeBaseSeriesEvents=function(){var f=this.baseSeries||[];this.navigatorEnabled&&f[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&f.forEach(function(f){d(f,"updatedData",this.updatedDataHandler)},this),f[0].xAxis&&
d(f[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};c.prototype.init=function(f){var c=f.options,a=c.navigator,b=a.enabled,k=c.scrollbar,d=k.enabled;c=b?a.height:0;var l=d?k.height:0;this.handles=[];this.shades=[];this.chart=f;this.setBaseSeries();this.height=c;this.scrollbarHeight=l;this.scrollbarEnabled=d;this.navigatorEnabled=b;this.navigatorOptions=a;this.scrollbarOptions=k;this.outlineHeight=c+l;this.opposite=m(a.opposite,!(b||!f.inverted));var p=this;b=p.baseSeries;k=f.xAxis.length;
d=f.yAxis.length;var q=b&&b[0]&&b[0].xAxis||f.xAxis[0]||{options:{}};f.isDirtyBox=!0;p.navigatorEnabled?(p.xAxis=new u(f,y({breaks:q.options.breaks,ordinal:q.options.ordinal},a.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:k,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},f.inverted?{offsets:[l,0,-l,0],width:c}:{offsets:[0,-l,0,l],height:c})),p.yAxis=new u(f,y(a.yAxis,{id:"navigator-y-axis",alignTicks:!1,
offset:0,index:d,isInternal:!0,zoomEnabled:!1},f.inverted?{width:c}:{height:c})),b||a.series.data?p.updateNavigatorSeries(!1):0===f.series.length&&(p.unbindRedraw=A(f,"beforeRedraw",function(){0<f.series.length&&!p.series&&(p.setBaseSeries(),p.unbindRedraw())})),p.reversedExtremes=f.inverted&&!p.xAxis.reversed||!f.inverted&&p.xAxis.reversed,p.renderElements(),p.addMouseEvents()):p.xAxis={translate:function(c,a){var b=f.xAxis[0],r=b.getExtremes(),k=b.len-2*l,d=w("min",b.options.min,r.dataMin);b=w("max",
b.options.max,r.dataMax)-d;return a?c*b/k+d:k*(c-d)/b},toPixels:function(f){return this.translate(f)},toValue:function(f){return this.translate(f,!0)},toFixedRange:u.prototype.toFixedRange,fake:!0};f.options.scrollbar.enabled&&(f.scrollbar=p.scrollbar=new n(f.renderer,y(f.options.scrollbar,{margin:p.navigatorEnabled?0:10,vertical:f.inverted}),f),A(p.scrollbar,"changed",function(c){var a=p.size,b=a*this.to;a*=this.from;p.hasDragged=p.scrollbar.hasDragged;p.render(0,0,a,b);(f.options.scrollbar.liveRedraw||
"mousemove"!==c.DOMType&&"touchmove"!==c.DOMType)&&setTimeout(function(){p.onMouseUp(c)})}));p.addBaseSeriesEvents();p.addChartEvents()};c.prototype.getUnionExtremes=function(f){var c=this.chart.xAxis[0],a=this.xAxis,b=a.options,k=c.options,d;f&&null===c.dataMin||(d={dataMin:m(b&&b.min,w("min",k.min,c.dataMin,a.dataMin,a.min)),dataMax:m(b&&b.max,w("max",k.max,c.dataMax,a.dataMax,a.max))});return d};c.prototype.setBaseSeries=function(f,c){var a=this.chart,b=this.baseSeries=[];f=f||a.options&&a.options.navigator.baseSeries||
(a.series.length?B(a.series,function(f){return!f.options.isInternal}).index:0);(a.series||[]).forEach(function(c,a){c.options.isInternal||!c.options.showInNavigator&&(a!==f&&c.options.id!==f||!1===c.options.showInNavigator)||b.push(c)});this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(!0,c)};c.prototype.updateNavigatorSeries=function(f,c){var r=this,k=r.chart,l=r.baseSeries,p,q,w=r.navigatorOptions.series,u,g={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",
yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,states:{inactive:{opacity:1}}},e=r.series=(r.series||[]).filter(function(f){var c=f.baseSeries;return 0>l.indexOf(c)?(c&&(d(c,"updatedData",r.updatedDataHandler),delete c.navigatorSeries),f.chart&&f.destroy(),!1):!0});l&&l.length&&l.forEach(function(f){var b=f.navigatorSeries,d=F({color:f.color,visible:f.visible},z(w)?a.navigator.series:w);b&&!1===r.navigatorOptions.adaptToUpdatedData||(g.name="Navigator "+l.length,p=f.options||{},
u=p.navigatorOptions||{},q=y(p,g,d,u),q.pointRange=m(d.pointRange,u.pointRange,a.plotOptions[q.type||"line"].pointRange),d=u.data||d.data,r.hasNavigatorData=r.hasNavigatorData||!!d,q.data=d||p.data&&p.data.slice(0),b&&b.options?b.update(q,c):(f.navigatorSeries=k.initSeries(q),f.navigatorSeries.baseSeries=f,e.push(f.navigatorSeries)))});if(w.data&&(!l||!l.length)||z(w))r.hasNavigatorData=!1,w=b(w),w.forEach(function(f,c){g.name="Navigator "+(e.length+1);q=y(a.navigator.series,{color:k.series[c]&&!k.series[c].options.isInternal&&
k.series[c].color||k.options.colors[c]||k.options.colors[0]},g,f);q.data=f.data;q.data&&(r.hasNavigatorData=!0,e.push(k.initSeries(q)))});f&&this.addBaseSeriesEvents()};c.prototype.addBaseSeriesEvents=function(){var f=this,c=f.baseSeries||[];c[0]&&c[0].xAxis&&A(c[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);c.forEach(function(c){A(c,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});A(c,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,
!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&c.xAxis&&A(c,"updatedData",this.updatedDataHandler);A(c,"remove",function(){this.navigatorSeries&&(E(f.series,this.navigatorSeries),t(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};c.prototype.getBaseSeriesMin=function(f){return this.baseSeries.reduce(function(f,c){return Math.min(f,c.xData?c.xData[0]:f)},f)};c.prototype.modifyNavigatorAxisExtremes=function(){var f=this.xAxis,c;"undefined"!==
typeof f.getExtremes&&(!(c=this.getUnionExtremes(!0))||c.dataMin===f.min&&c.dataMax===f.max||(f.min=c.dataMin,f.max=c.dataMax))};c.prototype.modifyBaseAxisExtremes=function(){var f=this.chart.navigator,c=this.getExtremes(),a=c.dataMin,b=c.dataMax;c=c.max-c.min;var k=f.stickToMin,d=f.stickToMax,l=m(this.options.overscroll,0),p=f.series&&f.series[0],q=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(k){var w=a;var u=w+c}d&&(u=b+l,k||(w=Math.max(u-c,f.getBaseSeriesMin(p&&
p.xData?p.xData[0]:-Number.MAX_VALUE))));q&&(k||d)&&C(w)&&(this.min=this.userMin=w,this.max=this.userMax=u)}f.stickToMin=f.stickToMax=null};c.prototype.updatedDataHandler=function(){var c=this.chart.navigator,a=this.navigatorSeries,b=c.getBaseSeriesMin(this.xData[0]);c.stickToMax=c.reversedExtremes?0===Math.round(c.zoomedMin):Math.round(c.zoomedMax)>=Math.round(c.size);c.stickToMin=C(this.xAxis.min)&&this.xAxis.min<=b&&(!this.chart.fixedRange||!c.stickToMax);a&&!c.hasNavigatorData&&(a.options.pointStart=
this.xData[0],a.setData(this.options.data,!1,null,!1))};c.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(A(this.chart,"redraw",function(){var c=this.navigator,a=c&&(c.baseSeries&&c.baseSeries[0]&&c.baseSeries[0].xAxis||c.scrollbar&&this.xAxis[0]);a&&c.render(a.min,a.max)}),A(this.chart,"getMargins",function(){var c=this.navigator,a=c.opposite?"plotTop":"marginBottom";this.inverted&&(a=c.opposite?"marginRight":"plotLeft");this[a]=(this[a]||
0)+(c.navigatorEnabled||!this.inverted?c.outlineHeight:0)+c.navigatorOptions.margin}))};c.prototype.destroy=function(){this.removeEvents();this.xAxis&&(E(this.chart.xAxis,this.xAxis),E(this.chart.axes,this.xAxis));this.yAxis&&(E(this.chart.yAxis,this.yAxis),E(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(c){c.destroy&&c.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(c){this[c]&&
this[c].destroy&&this[c].destroy();this[c]=null},this);[this.handles].forEach(function(c){g(c)},this)};return c}();v.Navigator||(v.Navigator=p,A(u,"zoom",function(c){var f=this.chart.options,a=f.chart.zoomType,b=f.chart.pinchType,d=f.navigator;f=f.rangeSelector;this.isXAxis&&(d&&d.enabled||f&&f.enabled)&&("y"===a?c.zoomed=!1:(!k&&"xy"===a||k&&"xy"===b)&&this.options.range&&(a=this.previousZoom,t(c.newMin)?this.previousZoom=[this.min,this.max]:a&&(c.newMin=a[0],c.newMax=a[1],delete this.previousZoom)));
"undefined"!==typeof c.zoomed&&c.preventDefault()}),A(e,"beforeShowResetZoom",function(){var c=this.options,f=c.navigator,a=c.rangeSelector;if((f&&f.enabled||a&&a.enabled)&&(!k&&"x"===c.chart.zoomType||k&&"x"===c.chart.pinchType))return!1}),A(e,"beforeRender",function(){var c=this.options;if(c.navigator.enabled||c.scrollbar.enabled)this.scroller=this.navigator=new p(this)}),A(e,"afterSetChartSize",function(){var c=this.legend,f=this.navigator;if(f){var a=c&&c.options;var b=f.xAxis;var k=f.yAxis;var d=
f.scrollbarHeight;this.inverted?(f.left=f.opposite?this.chartWidth-d-f.height:this.spacing[3]+d,f.top=this.plotTop+d):(f.left=this.plotLeft+d,f.top=f.navigatorOptions.top||this.chartHeight-f.height-d-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(a&&"bottom"===a.verticalAlign&&a.enabled&&!a.floating?c.legendHeight+m(a.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));b&&k&&(this.inverted?b.options.left=k.options.left=f.left:b.options.top=k.options.top=
f.top,b.setAxisSize(),k.setAxisSize())}}),A(e,"update",function(c){var f=c.options.navigator||{},a=c.options.scrollbar||{};this.navigator||this.scroller||!f.enabled&&!a.enabled||(y(!0,this.options.navigator,f),y(!0,this.options.scrollbar,a),delete c.options.navigator,delete c.options.scrollbar)}),A(e,"afterUpdate",function(c){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new p(this),m(c.redraw,!0)&&this.redraw(c.animation))}),
A(e,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),A(q,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),e.prototype.callbacks.push(function(c){var f=c.navigator;f&&c.xAxis[0]&&(c=c.xAxis[0].getExtremes(),f.render(c.min,c.max))}));v.Navigator=p;return v.Navigator});G(n,"parts/OrdinalAxis.js",[n["parts/Axis.js"],n["parts/Globals.js"],n["parts/Utilities.js"]],function(v,h,n){var e=n.addEvent,A=
n.css,H=n.defined,D=n.pick,t=n.timeUnits;n=h.Chart;var g=h.Series,E=function(){function g(g){this.index={};this.axis=g}g.prototype.getExtendedPositions=function(){var g=this,e=g.axis,y=e.constructor.prototype,m=e.chart,d=e.series[0].currentDataGrouping,b=g.index,u=d?d.count+d.unitName:"raw",a=e.options.overscroll,l=e.getExtremes(),k;b||(b=g.index={});if(!b[u]){var q={series:[],chart:m,getExtremes:function(){return{min:l.dataMin,max:l.dataMax+a}},options:{ordinal:!0},ordinal:{},ordinal2lin:y.ordinal2lin,
val2lin:y.val2lin};q.ordinal.axis=q;e.series.forEach(function(a){k={xAxis:q,xData:a.xData.slice(),chart:m,destroyGroupedData:h.noop};k.xData=k.xData.concat(g.getOverscrollPositions());k.options={dataGrouping:d?{enabled:!0,forced:!0,approximation:"open",units:[[d.unitName,[d.count]]]}:{enabled:!1}};a.processData.apply(k);q.series.push(k)});e.beforeSetTickPositions.apply(q);b[u]=q.ordinal.positions}return b[u]};g.prototype.getGroupIntervalFactor=function(g,e,h){h=h.processedXData;var m=h.length,d=[];
var b=this.groupIntervalFactor;if(!b){for(b=0;b<m-1;b++)d[b]=h[b+1]-h[b];d.sort(function(b,a){return b-a});d=d[Math.floor(m/2)];g=Math.max(g,h[0]);e=Math.min(e,h[m-1]);this.groupIntervalFactor=b=m*d/(e-g)}return b};g.prototype.getOverscrollPositions=function(){var g=this.axis,e=g.options.overscroll,h=this.overscrollPointsRange,m=[],d=g.dataMax;if(H(h))for(m.push(d);d<=g.dataMax+e;)d+=h,m.push(d);return m};g.prototype.postProcessTickInterval=function(g){var e=this.axis,h=this.slope;return h?e.options.breaks?
e.closestPointRange||g:g/(h/e.closestPointRange):g};return g}(),F=function(){function g(){}g.init=function(g,h,B){var m=g.prototype;m.beforeSetTickPositions=function(){var d=this.ordinal,b=[],u,a=!1,l=this.getExtremes(),k=l.min,q=l.max,w,g=this.isXAxis&&!!this.options.breaks;l=this.options.ordinal;var p=Number.MAX_VALUE,c=this.chart.options.chart.ignoreHiddenSeries,f;if(l||g){this.series.forEach(function(a,k){u=[];if(!(c&&!1===a.visible||!1===a.takeOrdinalPosition&&!g)&&(b=b.concat(a.processedXData),
r=b.length,b.sort(function(c,f){return c-f}),p=Math.min(p,D(a.closestPointRange,p)),r)){for(k=0;k<r-1;)b[k]!==b[k+1]&&u.push(b[k+1]),k++;u[0]!==b[0]&&u.unshift(b[0]);b=u}a.isSeriesBoosting&&(f=!0)});f&&(b.length=0);var r=b.length;if(2<r){var x=b[1]-b[0];for(w=r-1;w--&&!a;)b[w+1]-b[w]!==x&&(a=!0);!this.options.keepOrdinalPadding&&(b[0]-k>x||q-b[b.length-1]>x)&&(a=!0)}else this.options.overscroll&&(2===r?p=b[1]-b[0]:1===r?(p=this.options.overscroll,b=[b[0],b[0]+p]):p=d.overscrollPointsRange);a?(this.options.overscroll&&
(d.overscrollPointsRange=p,b=b.concat(d.getOverscrollPositions())),d.positions=b,x=this.ordinal2lin(Math.max(k,b[0]),!0),w=Math.max(this.ordinal2lin(Math.min(q,b[b.length-1]),!0),1),d.slope=q=(q-k)/(w-x),d.offset=k-x*q):(d.overscrollPointsRange=D(this.closestPointRange,d.overscrollPointsRange),d.positions=this.ordinal.slope=d.offset=void 0)}this.isOrdinal=l&&a;d.groupIntervalFactor=null};g.prototype.getTimeTicks=function(d,b,u,a,l,k,q){void 0===l&&(l=[]);void 0===k&&(k=0);var w=0,g,p,c={},f=[],r=
-Number.MAX_VALUE,x=this.options.tickPixelInterval,m=this.chart.time,e=[];if(!this.options.ordinal&&!this.options.breaks||!l||3>l.length||"undefined"===typeof b)return m.getTimeTicks.apply(m,arguments);var h=l.length;for(g=0;g<h;g++){var z=g&&l[g-1]>u;l[g]<b&&(w=g);if(g===h-1||l[g+1]-l[g]>5*k||z){if(l[g]>r){for(p=m.getTimeTicks(d,l[w],l[g],a);p.length&&p[0]<=r;)p.shift();p.length&&(r=p[p.length-1]);e.push(f.length);f=f.concat(p)}w=g+1}if(z)break}p=p.info;if(q&&p.unitRange<=t.hour){g=f.length-1;for(w=
1;w<g;w++)if(m.dateFormat("%d",f[w])!==m.dateFormat("%d",f[w-1])){c[f[w]]="day";var B=!0}B&&(c[f[0]]="day");p.higherRanks=c}p.segmentStarts=e;f.info=p;if(q&&H(x)){w=e=f.length;B=[];var y;for(m=[];w--;)g=this.translate(f[w]),y&&(m[w]=y-g),B[w]=y=g;m.sort();m=m[Math.floor(m.length/2)];m<.6*x&&(m=null);w=f[e-1]>u?e-1:e;for(y=void 0;w--;)g=B[w],e=Math.abs(y-g),y&&e<.8*x&&(null===m||e<.8*m)?(c[f[w]]&&!c[f[w+1]]?(e=w+1,y=g):e=w,f.splice(e,1)):y=g}return f};m.lin2val=function(d,b){var g=this.ordinal,a=g.positions;
if(a){var l=g.slope,k=g.offset;g=a.length-1;if(b)if(0>d)d=a[0];else if(d>g)d=a[g];else{g=Math.floor(d);var q=d-g}else for(;g--;)if(b=l*g+k,d>=b){l=l*(g+1)+k;q=(d-b)/(l-b);break}return"undefined"!==typeof q&&"undefined"!==typeof a[g]?a[g]+(q?q*(a[g+1]-a[g]):0):d}return d};m.val2lin=function(d,b){var g=this.ordinal,a=g.positions;if(a){var l=a.length,k;for(k=l;k--;)if(a[k]===d){var q=k;break}for(k=l-1;k--;)if(d>a[k]||0===k){d=(d-a[k])/(a[k+1]-a[k]);q=k+d;break}b=b?q:g.slope*(q||0)+g.offset}else b=d;
return b};m.ordinal2lin=m.val2lin;e(g,"afterInit",function(){this.ordinal=new E(this)});e(g,"foundExtremes",function(){this.isXAxis&&H(this.options.overscroll)&&this.max===this.dataMax&&(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=this.options.overscroll,!this.isInternal&&H(this.userMin)&&(this.min+=this.options.overscroll))});e(g,"afterSetScale",function(){this.horiz&&!this.isDirty&&(this.isDirty=this.isOrdinal&&this.chart.navigator&&
!this.chart.navigator.adaptToUpdatedData)});e(h,"pan",function(d){var b=this.xAxis[0],g=b.options.overscroll,a=d.originalEvent.chartX,l=this.options.chart&&this.options.chart.panning,k=!1;if(l&&"y"!==l.type&&b.options.ordinal&&b.series.length){var q=this.mouseDownX,w=b.getExtremes(),m=w.dataMax,p=w.min,c=w.max,f=this.hoverPoints,r=b.closestPointRange||b.ordinal&&b.ordinal.overscrollPointsRange;q=(q-a)/(b.translationSlope*(b.ordinal.slope||r));var x={ordinal:{positions:b.ordinal.getExtendedPositions()}};
r=b.lin2val;var e=b.val2lin;if(!x.ordinal.positions)k=!0;else if(1<Math.abs(q)){f&&f.forEach(function(c){c.setState()});if(0>q){f=x;var h=b.ordinal.positions?b:x}else f=b.ordinal.positions?b:x,h=x;x=h.ordinal.positions;m>x[x.length-1]&&x.push(m);this.fixedRange=c-p;q=b.toFixedRange(null,null,r.apply(f,[e.apply(f,[p,!0])+q,!0]),r.apply(h,[e.apply(h,[c,!0])+q,!0]));q.min>=Math.min(w.dataMin,p)&&q.max<=Math.max(m,c)+g&&b.setExtremes(q.min,q.max,!0,!1,{trigger:"pan"});this.mouseDownX=a;A(this.container,
{cursor:"move"})}}else k=!0;k||l&&/y/.test(l.type)?g&&(b.max=b.dataMax+g):d.preventDefault()});e(B,"updatedData",function(){var d=this.xAxis;d&&d.options.ordinal&&delete d.ordinal.index})};return g}();F.init(v,n,g);return F});G(n,"modules/broken-axis.src.js",[n["parts/Globals.js"],n["parts/Utilities.js"],n["parts/Stacking.js"]],function(n,h,I){var e=h.addEvent,A=h.extend,v=h.find,D=h.fireEvent,t=h.isArray,g=h.pick,E=n.Axis;h=n.Series;var F=function(g,e){return v(e,function(e){return e.from<g&&g<e.to})};
A(E.prototype,{isInBreak:function(g,e){var h=g.repeat||Infinity,t=g.from,m=g.to-g.from;e=e>=t?(e-t)%h:h-(t-e)%h;return g.inclusive?e<=m:e<m&&0!==e},isInAnyBreak:function(e,h){var t=this.options.breaks,y=t&&t.length,m;if(y){for(;y--;)if(this.isInBreak(t[y],e)){var d=!0;m||(m=g(t[y].showPoints,!this.isXAxis))}var b=d&&h?d&&!m:d}return b}});e(E,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});e(E,"afterSetTickPositions",function(){if(this.isBroken){var g=
this.tickPositions,e=this.tickPositions.info,h=[],t;for(t=0;t<g.length;t++)this.isInAnyBreak(g[t])||h.push(g[t]);this.tickPositions=h;this.tickPositions.info=e}});e(E,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});E.prototype.setBreaks=function(e,h){function z(b){var d=b,a;for(a=0;a<m.breakArray.length;a++){var l=m.breakArray[a];if(l.to<=b)d-=l.len;else if(l.from>=b)break;else if(m.isInBreak(l,b)){d-=b-l.from;break}}return d}function n(b){var d;for(d=0;d<m.breakArray.length;d++){var a=
m.breakArray[d];if(a.from>=b)break;else a.to<b?b+=a.len:m.isInBreak(a,b)&&(b+=a.len)}return b}var m=this,d=t(e)&&!!e.length;m.isDirty=m.isBroken!==d;m.isBroken=d;m.options.breaks=m.userOptions.breaks=e;m.forceRedraw=!0;m.series.forEach(function(b){b.isDirty=!0});d||m.val2lin!==z||(delete m.val2lin,delete m.lin2val);d&&(m.userOptions.ordinal=!1,m.val2lin=z,m.lin2val=n,m.setExtremes=function(b,d,a,l,k){if(this.isBroken){for(var q,g=this.options.breaks;q=F(b,g);)b=q.to;for(;q=F(d,g);)d=q.from;d<b&&(d=
b)}E.prototype.setExtremes.call(this,b,d,a,l,k)},m.setAxisTranslation=function(b){E.prototype.setAxisTranslation.call(this,b);this.unitLength=null;if(this.isBroken){b=m.options.breaks;var d=[],a=[],l=0,k,q=m.userMin||m.min,e=m.userMax||m.max,h=g(m.pointRangePadding,0),p;b.forEach(function(c){k=c.repeat||Infinity;m.isInBreak(c,q)&&(q+=c.to%k-q%k);m.isInBreak(c,e)&&(e-=e%k-c.from%k)});b.forEach(function(c){f=c.from;for(k=c.repeat||Infinity;f-k>q;)f-=k;for(;f<q;)f+=k;for(p=f;p<e;p+=k)d.push({value:p,
move:"in"}),d.push({value:p+(c.to-c.from),move:"out",size:c.breakSize})});d.sort(function(c,f){return c.value===f.value?("in"===c.move?0:1)-("in"===f.move?0:1):c.value-f.value});var c=0;var f=q;d.forEach(function(b){c+="in"===b.move?1:-1;1===c&&"in"===b.move&&(f=b.value);0===c&&(a.push({from:f,to:b.value,len:b.value-f-(b.size||0)}),l+=b.value-f-(b.size||0))});m.breakArray=a;m.unitLength=e-q-l+h;D(m,"afterBreaks");m.staticScale?m.transA=m.staticScale:m.unitLength&&(m.transA*=(e-m.min+h)/m.unitLength);
h&&(m.minPixelPadding=m.transA*m.minPointOffset);m.min=q;m.max=e}});g(h,!0)&&this.chart.redraw()};e(h,"afterGeneratePoints",function(){var g=this.options.connectNulls,e=this.points,h=this.xAxis,t=this.yAxis;if(this.isDirty)for(var m=e.length;m--;){var d=e[m],b=!(null===d.y&&!1===g)&&(h&&h.isInAnyBreak(d.x,!0)||t&&t.isInAnyBreak(d.y,!0));d.visible=b?!1:!1!==d.options.visible}});e(h,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,g(this.pointArrayMap,["y"]))});
n.Series.prototype.drawBreaks=function(e,h){var t=this,n=t.points,m,d,b,u;e&&h.forEach(function(a){m=e.breakArray||[];d=e.isXAxis?e.min:g(t.options.threshold,e.min);n.forEach(function(l){u=g(l["stack"+a.toUpperCase()],l[a]);m.forEach(function(a){b=!1;if(d<a.from&&u>a.to||d>a.from&&u<a.from)b="pointBreak";else if(d<a.from&&u>a.from&&u<a.to||d>a.from&&u>a.to&&u<a.from)b="pointInBreak";b&&D(e,b,{point:l,brk:a})})})})};n.Series.prototype.gappedPath=function(){var g=this.currentDataGrouping,e=g&&g.gapSize;
g=this.options.gapSize;var h=this.points.slice(),t=h.length-1,m=this.yAxis,d;if(g&&0<t)for("value"!==this.options.gapUnit&&(g*=this.basePointRange),e&&e>g&&e>=this.basePointRange&&(g=e),d=void 0;t--;)d&&!1!==d.visible||(d=h[t+1]),e=h[t],!1!==d.visible&&!1!==e.visible&&(d.x-e.x>g&&(d=(e.x+d.x)/2,h.splice(t+1,0,{isNull:!0,x:d}),this.options.stacking&&(d=m.stacks[this.stackKey][d]=new I(m,m.options.stackLabels,!1,d,this.stack),d.total=0)),d=e);return this.getGraphPath(h)}});G(n,"masters/modules/broken-axis.src.js",
[],function(){});G(n,"parts/DataGrouping.js",[n["parts/Globals.js"],n["parts/Point.js"],n["parts/Tooltip.js"],n["parts/Utilities.js"]],function(n,h,I,e){"";var A=e.addEvent,v=e.arrayMax,D=e.arrayMin,t=e.correctFloat,g=e.defined,E=e.error,F=e.extend,B=e.format,z=e.isNumber,C=e.merge,y=e.pick,m=n.Axis,d=n.defaultPlotOptions;e=n.Series;var b=n.approximations={sum:function(c){var f=c.length;if(!f&&c.hasNulls)var a=null;else if(f)for(a=0;f--;)a+=c[f];return a},average:function(c){var a=c.length;c=b.sum(c);
z(c)&&a&&(c=t(c/a));return c},averages:function(){var c=[];[].forEach.call(arguments,function(a){c.push(b.average(a))});return"undefined"===typeof c[0]?void 0:c},open:function(c){return c.length?c[0]:c.hasNulls?null:void 0},high:function(c){return c.length?v(c):c.hasNulls?null:void 0},low:function(c){return c.length?D(c):c.hasNulls?null:void 0},close:function(c){return c.length?c[c.length-1]:c.hasNulls?null:void 0},ohlc:function(c,a,d,k){c=b.open(c);a=b.high(a);d=b.low(d);k=b.close(k);if(z(c)||z(a)||
z(d)||z(k))return[c,a,d,k]},range:function(c,a){c=b.low(c);a=b.high(a);if(z(c)||z(a))return[c,a];if(null===c&&null===a)return null}},u=function(c,a,d,k){var f=this,l=f.data,p=f.options&&f.options.data,r=[],q=[],e=[],x=c.length,m=!!a,w=[],h=f.pointArrayMap,u=h&&h.length,t=["x"].concat(h||["y"]),n=0,A=0,y;k="function"===typeof k?k:b[k]?b[k]:b[f.getDGApproximation&&f.getDGApproximation()||"average"];u?h.forEach(function(){w.push([])}):w.push([]);var M=u||1;for(y=0;y<=x&&!(c[y]>=d[0]);y++);for(y;y<=x;y++){for(;"undefined"!==
typeof d[n+1]&&c[y]>=d[n+1]||y===x;){var v=d[n];f.dataGroupInfo={start:f.cropStart+A,length:w[0].length};var B=k.apply(f,w);f.pointClass&&!g(f.dataGroupInfo.options)&&(f.dataGroupInfo.options=C(f.pointClass.prototype.optionsToObject.call({series:f},f.options.data[f.cropStart+A])),t.forEach(function(c){delete f.dataGroupInfo.options[c]}));"undefined"!==typeof B&&(r.push(v),q.push(B),e.push(f.dataGroupInfo));A=y;for(v=0;v<M;v++)w[v].length=0,w[v].hasNulls=!1;n+=1;if(y===x)break}if(y===x)break;if(h)for(v=
f.cropStart+y,B=l&&l[v]||f.pointClass.prototype.applyOptions.apply({series:f},[p[v]]),v=0;v<u;v++){var H=B[h[v]];z(H)?w[v].push(H):null===H&&(w[v].hasNulls=!0)}else v=m?a[y]:null,z(v)?w[0].push(v):null===v&&(w[0].hasNulls=!0)}return{groupedXData:r,groupedYData:q,groupMap:e}},a={approximations:b,groupData:u},l=e.prototype,k=l.processData,q=l.generatePoints,w={groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S",
"%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},M={line:{},spline:{},area:{},areaspline:{},arearange:{},column:{groupPixelWidth:10},columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},ohlc:{groupPixelWidth:5}},p=n.defaultDataGroupingUnits=
[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]];l.getDGApproximation=function(){return this.is("arearange")?"range":this.is("ohlc")?"ohlc":this.is("column")?"sum":"average"};l.groupData=u;l.processData=function(){var c=this.chart,a=this.options.dataGrouping,b=!1!==this.allowDG&&a&&y(a.enabled,c.options.isStock),d=this.visible||!c.options.chart.ignoreHiddenSeries,
q,e=this.currentDataGrouping,w=!1;this.forceCrop=b;this.groupPixelWidth=null;this.hasProcessed=!0;b&&!this.requireSorting&&(this.requireSorting=w=!0);b=!1===k.apply(this,arguments)||!b;w&&(this.requireSorting=!1);if(!b){this.destroyGroupedData();b=a.groupAll?this.xData:this.processedXData;var m=a.groupAll?this.yData:this.processedYData,h=c.plotSizeX;c=this.xAxis;var u=c.options.ordinal,t=this.groupPixelWidth=c.getGroupPixelWidth&&c.getGroupPixelWidth();if(t){this.isDirty=q=!0;this.points=null;w=c.getExtremes();
var n=w.min;w=w.max;u=u&&c.ordinal&&c.ordinal.getGroupIntervalFactor(n,w,this)||1;t=t*(w-n)/h*u;h=c.getTimeTicks(c.normalizeTimeTickInterval(t,a.units||p),Math.min(n,b[0]),Math.max(w,b[b.length-1]),c.options.startOfWeek,b,this.closestPointRange);m=l.groupData.apply(this,[b,m,h,a.approximation]);b=m.groupedXData;u=m.groupedYData;var A=0;if(a.smoothed&&b.length){var v=b.length-1;for(b[v]=Math.min(b[v],w);v--&&0<v;)b[v]+=t/2;b[0]=Math.max(b[0],n)}for(v=1;v<h.length;v++)h.info.segmentStarts&&-1!==h.info.segmentStarts.indexOf(v)||
(A=Math.max(h[v]-h[v-1],A));n=h.info;n.gapSize=A;this.closestPointRange=h.info.totalRange;this.groupMap=m.groupMap;if(g(b[0])&&b[0]<c.min&&d){if(!g(c.options.min)&&c.min<=c.dataMin||c.min===c.dataMin)c.min=Math.min(b[0],c.min);c.dataMin=Math.min(b[0],c.dataMin)}a.groupAll&&(a=this.cropData(b,u,c.min,c.max,1),b=a.xData,u=a.yData);this.processedXData=b;this.processedYData=u}else this.groupMap=null;this.hasGroupedData=q;this.currentDataGrouping=n;this.preventGraphAnimation=(e&&e.totalRange)!==(n&&n.totalRange)}};
l.destroyGroupedData=function(){this.groupedData&&(this.groupedData.forEach(function(c,a){c&&(this.groupedData[a]=c.destroy?c.destroy():null)},this),this.groupedData.length=0)};l.generatePoints=function(){q.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};A(h,"update",function(){if(this.dataGroup)return E(24,!1,this.series.chart),!1});A(I,"headerFormatter",function(c){var a=this.chart,b=a.time,d=c.labelConfig,k=d.series,l=k.tooltipOptions,p=k.options.dataGrouping,
g=l.xDateFormat,q=k.xAxis,e=l[(c.isFooter?"footer":"header")+"Format"];if(q&&"datetime"===q.options.type&&p&&z(d.key)){var m=k.currentDataGrouping;p=p.dateTimeLabelFormats||w.dateTimeLabelFormats;if(m)if(l=p[m.unitName],1===m.count)g=l[0];else{g=l[1];var h=l[2]}else!g&&p&&(g=this.getXDateFormat(d,l,q));g=b.dateFormat(g,d.key);h&&(g+=b.dateFormat(h,d.key+m.totalRange-1));k.chart.styledMode&&(e=this.styledModeFormat(e));c.text=B(e,{point:F(d.point,{key:g}),series:k},a);c.preventDefault()}});A(e,"destroy",
l.destroyGroupedData);A(e,"afterSetOptions",function(c){c=c.options;var a=this.type,b=this.chart.options.plotOptions,k=d[a].dataGrouping,l=this.useCommonDataGrouping&&w;if(M[a]||l)k||(k=C(w,M[a])),c.dataGrouping=C(l,k,b.series&&b.series.dataGrouping,b[a].dataGrouping,this.userOptions.dataGrouping)});A(m,"afterSetScale",function(){this.series.forEach(function(c){c.hasProcessed=!1})});m.prototype.getGroupPixelWidth=function(){var c=this.series,a=c.length,b,d=0,k=!1,l;for(b=a;b--;)(l=c[b].options.dataGrouping)&&
(d=Math.max(d,y(l.groupPixelWidth,w.groupPixelWidth)));for(b=a;b--;)(l=c[b].options.dataGrouping)&&c[b].hasProcessed&&(a=(c[b].processedXData||c[b].data).length,c[b].groupPixelWidth||a>this.chart.plotSizeX/d||a&&l.forced)&&(k=!0);return k?d:0};m.prototype.setDataGrouping=function(c,a){var b;a=y(a,!0);c||(c={forced:!1,units:null});if(this instanceof m)for(b=this.series.length;b--;)this.series[b].update({dataGrouping:c},!1);else this.chart.options.series.forEach(function(a){a.dataGrouping=c},!1);this.ordinal&&
(this.ordinal.slope=void 0);a&&this.chart.redraw()};n.dataGrouping=a;"";return a});G(n,"parts/OHLCSeries.js",[n["parts/Globals.js"],n["parts/Point.js"],n["parts/Utilities.js"]],function(n,h,I){I=I.seriesType;var e=n.seriesTypes;I("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},
{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(e){return[e.open,e.high,e.low,e.close]},pointValKey:"close",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},init:function(){e.column.prototype.init.apply(this,arguments);this.options.stacking=!1},pointAttribs:function(h,n){n=e.column.prototype.pointAttribs.call(this,h,n);var v=this.options;delete n.fill;!h.options.color&&v.upColor&&h.open<h.close&&(n.stroke=v.upColor);return n},translate:function(){var h=this,
n=h.yAxis,v=!!h.modifyValue,t=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];e.column.prototype.translate.apply(h);h.points.forEach(function(g){[g.open,g.high,g.low,g.close,g.low].forEach(function(e,A){null!==e&&(v&&(e=h.modifyValue(e)),g[t[A]]=n.toPixels(e,!0))});g.tooltipPos[1]=g.plotHigh+n.pos-h.chart.plotTop})},drawPoints:function(){var e=this,h=e.chart,n=function(e,g,h){e[2]=Math.max(h+g,e[2]);e[5]=Math.min(h-g,e[5])};e.points.forEach(function(t){var g=t.graphic,v=!g;if("undefined"!==
typeof t.plotY){g||(t.graphic=g=h.renderer.path().add(e.group));h.styledMode||g.attr(e.pointAttribs(t,t.selected&&"select"));var A=g.strokeWidth();var B=A%2/2;var z=Math.round(t.plotX)-B;var C=Math.round(t.shapeArgs.width/2);var y=["M",z,Math.round(t.yBottom),"L",z,Math.round(t.plotHigh)];if(null!==t.open){var m=Math.round(t.plotOpen)+B;y.push("M",z,m,"L",z-C,m);n(y,A/2,m)}null!==t.close&&(m=Math.round(t.plotClose)+B,y.push("M",z,m,"L",z+C,m),n(y,A/2,m));g[v?"attr":"animate"]({d:y}).addClass(t.getClassName(),
!0)}})},animate:null},{getClassName:function(){return h.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}});""});G(n,"parts/CandlestickSeries.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,h){var v=h.merge;h=h.seriesType;var e=n.defaultPlotOptions,A=n.seriesTypes;h("candlestick","ohlc",v(e.column,{states:{hover:{lineWidth:2}},tooltip:e.ohlc.tooltip,threshold:null,lineColor:"#000000",lineWidth:1,upColor:"#ffffff",stickyTracking:!0}),
{pointAttribs:function(e,h){var n=A.column.prototype.pointAttribs.call(this,e,h),g=this.options,v=e.open<e.close,D=g.lineColor||this.color;n["stroke-width"]=g.lineWidth;n.fill=e.options.color||(v?g.upColor||this.color:this.color);n.stroke=e.options.lineColor||(v?g.upLineColor||D:D);h&&(e=g.states[h],n.fill=e.color||n.fill,n.stroke=e.lineColor||n.stroke,n["stroke-width"]=e.lineWidth||n["stroke-width"]);return n},drawPoints:function(){var e=this,h=e.chart,n=e.yAxis.reversed;e.points.forEach(function(g){var t=
g.graphic,v=!t;if("undefined"!==typeof g.plotY){t||(g.graphic=t=h.renderer.path().add(e.group));e.chart.styledMode||t.attr(e.pointAttribs(g,g.selected&&"select")).shadow(e.options.shadow);var A=t.strokeWidth()%2/2;var z=Math.round(g.plotX)-A;var C=g.plotOpen;var y=g.plotClose;var m=Math.min(C,y);C=Math.max(C,y);var d=Math.round(g.shapeArgs.width/2);y=n?C!==g.yBottom:Math.round(m)!==Math.round(g.plotHigh);var b=n?Math.round(m)!==Math.round(g.plotHigh):C!==g.yBottom;m=Math.round(m)+A;C=Math.round(C)+
A;A=[];A.push("M",z-d,C,"L",z-d,m,"L",z+d,m,"L",z+d,C,"Z","M",z,m,"L",z,y?Math.round(n?g.yBottom:g.plotHigh):m,"M",z,C,"L",z,b?Math.round(n?g.plotHigh:g.yBottom):C);t[v?"attr":"animate"]({d:A}).addClass(g.getClassName(),!0)}})}});""});G(n,"mixins/on-series.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,h){var v=h.defined,e=h.stableSort,A=n.seriesTypes;return{getPlotBox:function(){return n.Series.prototype.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||
this)},translate:function(){A.column.prototype.translate.apply(this);var h=this,n=h.options,t=h.chart,g=h.points,E=g.length-1,F,B=n.onSeries;B=B&&t.get(B);n=n.onKey||"y";var z=B&&B.options.step,C=B&&B.points,y=C&&C.length,m=t.inverted,d=h.xAxis,b=h.yAxis,u=0,a;if(B&&B.visible&&y){u=(B.pointXOffset||0)+(B.barW||0)/2;t=B.currentDataGrouping;var l=C[y-1].x+(t?t.totalRange:0);e(g,function(a,b){return a.x-b.x});for(n="plot"+n[0].toUpperCase()+n.substr(1);y--&&g[E];){var k=C[y];t=g[E];t.y=k.y;if(k.x<=t.x&&
"undefined"!==typeof k[n]){if(t.x<=l&&(t.plotY=k[n],k.x<t.x&&!z&&(a=C[y+1])&&"undefined"!==typeof a[n])){var q=(t.x-k.x)/(a.x-k.x);t.plotY+=q*(a[n]-k[n]);t.y+=q*(a.y-k.y)}E--;y++;if(0>E)break}}}g.forEach(function(a,k){a.plotX+=u;if("undefined"===typeof a.plotY||m)0<=a.plotX&&a.plotX<=d.len?m?(a.plotY=d.translate(a.x,0,1,0,1),a.plotX=v(a.y)?b.translate(a.y,0,0,0,1):0):a.plotY=(d.opposite?0:h.yAxis.len)+d.offset:a.shapeArgs={};if((F=g[k-1])&&F.plotX===a.plotX){"undefined"===typeof F.stackIndex&&(F.stackIndex=
0);var l=F.stackIndex+1}a.stackIndex=l});this.onSeries=B}}});G(n,"parts/FlagsSeries.js",[n["parts/Globals.js"],n["parts/Utilities.js"],n["mixins/on-series.js"]],function(n,h,I){function e(d){m[d+"pin"]=function(b,e,a,l,k){var g=k&&k.anchorX;k=k&&k.anchorY;"circle"===d&&l>a&&(b-=Math.round((l-a)/2),a=l);var h=m[d](b,e,a,l);g&&k&&(h.push("M","circle"===d?b+a/2:h[1]+h[4]/2,e>k?e:e+l,"L",g,k),h=h.concat(m.circle(g-1,k-1,2,2)));return h}}var v=h.addEvent,H=h.defined,D=h.isNumber,t=h.merge,g=h.objectEach,
E=h.seriesType,F=h.wrap;h=n.noop;var B=n.Renderer,z=n.Series,C=n.TrackerMixin,y=n.VMLRenderer,m=n.SVGRenderer.prototype.symbols;E("flags","column",{pointRange:0,allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},threshold:null,y:-30,fillColor:"#ffffff",lineWidth:1,states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],
forceCrop:!0,init:z.prototype.init,pointAttribs:function(d,b){var e=this.options,a=d&&d.color||this.color,l=e.lineColor,k=d&&d.lineWidth;d=d&&d.fillColor||e.fillColor;b&&(d=e.states[b].fillColor,l=e.states[b].lineColor,k=e.states[b].lineWidth);return{fill:d||a,stroke:l||a,"stroke-width":k||e.lineWidth||0}},translate:I.translate,getPlotBox:I.getPlotBox,drawPoints:function(){var d=this.points,b=this.chart,e=b.renderer,a=b.inverted,l=this.options,k=l.y,q,h=this.yAxis,m={},p=[];for(q=d.length;q--;){var c=
d[q];var f=(a?c.plotY:c.plotX)>this.xAxis.len;var r=c.plotX;var x=c.stackIndex;var v=c.options.shape||l.shape;var y=c.plotY;"undefined"!==typeof y&&(y=c.plotY+k-("undefined"!==typeof x&&x*l.stackDistance));c.anchorX=x?void 0:c.plotX;var A=x?void 0:c.plotY;var z="flag"!==v;x=c.graphic;"undefined"!==typeof y&&0<=r&&!f?(x||(x=c.graphic=e.label("",null,null,v,null,null,l.useHTML),b.styledMode||x.attr(this.pointAttribs(c)).css(t(l.style,c.style)),x.attr({align:z?"center":"left",width:l.width,height:l.height,
"text-align":l.textAlign}).addClass("highcharts-point").add(this.markerGroup),c.graphic.div&&(c.graphic.div.point=c),b.styledMode||x.shadow(l.shadow),x.isNew=!0),0<r&&(r-=x.strokeWidth()%2),v={y:y,anchorY:A},l.allowOverlapX&&(v.x=r,v.anchorX=c.anchorX),x.attr({text:c.options.title||l.title||"A"})[x.isNew?"attr":"animate"](v),l.allowOverlapX||(m[c.plotX]?m[c.plotX].size=Math.max(m[c.plotX].size,x.width):m[c.plotX]={align:z?.5:0,size:x.width,target:r,anchorX:r}),c.tooltipPos=[r,y+h.pos-b.plotTop]):
x&&(c.graphic=x.destroy())}l.allowOverlapX||(g(m,function(c){c.plotX=c.anchorX;p.push(c)}),n.distribute(p,a?h.len:this.xAxis.len,100),d.forEach(function(c){var a=c.graphic&&m[c.plotX];a&&(c.graphic[c.graphic.isNew?"attr":"animate"]({x:a.pos+a.align*a.size,anchorX:c.anchorX}),H(a.pos)?c.graphic.isNew=!1:(c.graphic.attr({x:-9999,anchorX:-9999}),c.graphic.isNew=!0))}));l.useHTML&&F(this.markerGroup,"on",function(c){return n.SVGElement.prototype.on.apply(c.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,
1))})},drawTracker:function(){var d=this.points;C.drawTrackerPoint.apply(this);d.forEach(function(b){var e=b.graphic;e&&v(e.element,"mouseover",function(){0<b.stackIndex&&!b.raised&&(b._y=e.y,e.attr({y:b._y-8}),b.raised=!0);d.forEach(function(a){a!==b&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=!1)})})})},animate:function(d){d&&this.setClip()},setClip:function(){z.prototype.setClip.apply(this,arguments);!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup.clip(this.chart[this.sharedClipKey])},
buildKDTree:h,invertGroups:h},{isValid:function(){return D(this.y)||"undefined"===typeof this.y}});m.flag=function(d,b,e,a,l){var k=l&&l.anchorX||d;l=l&&l.anchorY||b;return m.circle(k-1,l-1,2,2).concat(["M",k,l,"L",d,b+a,d,b,d+e,b,d+e,b+a,d,b+a,"Z"])};e("circle");e("square");B===y&&["circlepin","flag","squarepin"].forEach(function(d){y.prototype.symbols[d]=m[d]});""});G(n,"parts/RangeSelector.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,h){function v(a){this.init(a)}var e=h.addEvent,
A=h.createElement,H=h.css,D=h.defined,t=h.destroyObjectProperties,g=h.discardElement,E=h.extend,F=h.fireEvent,B=h.isNumber,z=h.merge,C=h.objectEach,y=h.pick,m=h.pInt,d=h.splat,b=n.Axis;h=n.Chart;var u=n.defaultOptions;E(u,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});u.lang=z(u.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",
rangeSelectorTo:"To"});v.prototype={clickButton:function(a,l){var k=this.chart,g=this.buttonOptions[a],h=k.xAxis[0],m=k.scroller&&k.scroller.getUnionExtremes()||h||{},p=m.dataMin,c=m.dataMax,f=h&&Math.round(Math.min(h.max,y(c,h.max))),r=g.type;m=g._range;var n,t=g.dataGrouping;if(null!==p&&null!==c){k.fixedRange=m;t&&(this.forcedDataGrouping=!0,b.prototype.setDataGrouping.call(h||{chart:this.chart},t,!1),this.frozenStates=g.preserveDataGrouping);if("month"===r||"year"===r)if(h){r={range:g,max:f,chart:k,
dataMin:p,dataMax:c};var u=h.minFromRange.call(r);B(r.newMax)&&(f=r.newMax)}else m=g;else if(m)u=Math.max(f-m,p),f=Math.min(u+m,c);else if("ytd"===r)if(h)"undefined"===typeof c&&(p=Number.MAX_VALUE,c=Number.MIN_VALUE,k.series.forEach(function(a){a=a.xData;p=Math.min(a[0],p);c=Math.max(a[a.length-1],c)}),l=!1),f=this.getYTDExtremes(c,p,k.time.useUTC),u=n=f.min,f=f.max;else{this.deferredYTDClick=a;return}else"all"===r&&h&&(u=p,f=c);u+=g._offsetMin;f+=g._offsetMax;this.setSelected(a);if(h)h.setExtremes(u,
f,y(l,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:g});else{var v=d(k.options.xAxis)[0];var A=v.range;v.range=m;var z=v.min;v.min=n;e(k,"load",function(){v.range=A;v.min=z})}}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var b=this,d=a.options.rangeSelector,
g=d.buttons||[].concat(b.defaultButtons),h=d.selected,m=function(){var a=b.minInput,c=b.maxInput;a&&a.blur&&F(a,"blur");c&&c.blur&&F(c,"blur")};b.chart=a;b.options=d;b.buttons=[];b.buttonOptions=g;this.unMouseDown=e(a.container,"mousedown",m);this.unResize=e(a,"resize",m);g.forEach(b.computeButtonRange);"undefined"!==typeof h&&g[h]&&this.clickButton(h,!1);e(a,"load",function(){a.xAxis&&a.xAxis[0]&&e(a.xAxis[0],"setExtremes",function(d){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==d.trigger&&
"updatedData"!==d.trigger&&b.forcedDataGrouping&&!b.frozenStates&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this,b=this.chart,d=b.xAxis[0],e=Math.round(d.max-d.min),g=!d.hasVisibleSeries,h=b.scroller&&b.scroller.getUnionExtremes()||d,p=h.dataMin,c=h.dataMax;b=a.getYTDExtremes(c,p,b.time.useUTC);var f=b.min,m=b.max,n=a.selected,u=B(n),t=a.options.allButtonsEnabled,v=a.buttons;a.buttonOptions.forEach(function(b,k){var l=b._range,h=b.type,q=b.count||1,r=v[k],x=0,w=b._offsetMax-
b._offsetMin;b=k===n;var y=l>c-p,A=l<d.minRange,z=!1,B=!1;l=l===e;("month"===h||"year"===h)&&e+36E5>=864E5*{month:28,year:365}[h]*q-w&&e-36E5<=864E5*{month:31,year:366}[h]*q+w?l=!0:"ytd"===h?(l=m-f+w===e,z=!b):"all"===h&&(l=d.max-d.min>=c-p,B=!b&&u&&l);h=!t&&(y||A||B||g);q=b&&l||l&&!u&&!z||b&&a.frozenStates;h?x=3:q&&(u=!0,x=2);r.state!==x&&(r.setState(x),0===x&&n===k&&a.setSelected(null))})},computeButtonRange:function(a){var b=a.type,d=a.count||1,e={millisecond:1,second:1E3,minute:6E4,hour:36E5,
day:864E5,week:6048E5};if(e[b])a._range=e[b]*d;else if("month"===b||"year"===b)a._range=864E5*{month:30,year:365}[b]*d;a._offsetMin=y(a.offsetMin,0);a._offsetMax=y(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,b){var d=this.chart.options.rangeSelector,e=this.chart.time,l=this[a+"Input"];D(b)&&(l.previousValue=l.HCTime,l.HCTime=b);l.value=e.dateFormat(d.inputEditDateFormat||"%Y-%m-%d",l.HCTime);this[a+"DateBox"].attr({text:e.dateFormat(d.inputDateFormat||"%b %e, %Y",
l.HCTime)})},showInput:function(a){var b=this.inputGroup,d=this[a+"DateBox"];H(this[a+"Input"],{left:b.translateX+d.x+"px",top:b.translateY+"px",width:d.width-2+"px",height:d.height-2+"px",border:"2px solid silver"})},hideInput:function(a){H(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(a){function b(){var c=r.value,a=(p.inputDateParser||Date.parse)(c),b=e.xAxis[0],k=e.scroller&&e.scroller.xAxis?e.scroller.xAxis:b,g=k.dataMin;k=k.dataMax;a!==r.previousValue&&
(r.previousValue=a,B(a)||(a=c.split("-"),a=Date.UTC(m(a[0]),m(a[1])-1,m(a[2]))),B(a)&&(e.time.useUTC||(a+=6E4*(new Date).getTimezoneOffset()),f?a>d.maxInput.HCTime?a=void 0:a<g&&(a=g):a<d.minInput.HCTime?a=void 0:a>k&&(a=k),"undefined"!==typeof a&&b.setExtremes(f?a:b.min,f?b.max:a,void 0,void 0,{trigger:"rangeSelectorInput"})))}var d=this,e=d.chart,g=e.renderer.style||{},h=e.renderer,p=e.options.rangeSelector,c=d.div,f="min"===a,r,x,t=this.inputGroup;this[a+"Label"]=x=h.label(u.lang[f?"rangeSelectorFrom":
"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(t);t.offset+=x.width+5;this[a+"DateBox"]=h=h.label("",t.offset).addClass("highcharts-range-input").attr({padding:2,width:p.inputBoxWidth||90,height:p.inputBoxHeight||17,"text-align":"center"}).on("click",function(){d.showInput(a);d[a+"Input"].focus()});e.styledMode||h.attr({stroke:p.inputBoxBorderColor||"#cccccc","stroke-width":1});h.add(t);t.offset+=h.width+(f?10:0);this[a+"Input"]=r=A("input",{name:a,
className:"highcharts-range-selector",type:"text"},{top:e.plotTop+"px"},c);e.styledMode||(x.css(z(g,p.labelStyle)),h.css(z({color:"#333333"},g,p.inputStyle)),H(r,E({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:g.fontSize,fontFamily:g.fontFamily,top:"-9999em"},p.inputStyle)));r.onfocus=function(){d.showInput(a)};r.onblur=function(){r===n.doc.activeElement&&b();d.hideInput(a);r.blur()};r.onchange=b;r.onkeypress=function(a){13===a.keyCode&&b()}},getPosition:function(){var a=
this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}},getYTDExtremes:function(a,b,d){var k=this.chart.time,e=new k.Date(a),g=k.get("FullYear",e);d=d?k.Date.UTC(g,0,1):+new k.Date(g,0,1);b=Math.max(b||0,d);e=e.getTime();return{max:Math.min(a||e,e),min:b}},render:function(a,b){var d=this,e=d.chart,g=e.renderer,l=e.container,p=e.options,c=p.exporting&&!1!==p.exporting.enabled&&p.navigation&&p.navigation.buttonOptions,
f=u.lang,h=d.div,m=p.rangeSelector,n=y(p.chart.style&&p.chart.style.zIndex,0)+1;p=m.floating;var t=d.buttons;h=d.inputGroup;var v=m.buttonTheme,z=m.buttonPosition,B=m.inputPosition,C=m.inputEnabled,E=v&&v.states,D=e.plotLeft,F=d.buttonGroup,H,G=d.options.verticalAlign,I=e.legend,O=I&&I.options,P=z.y,N=B.y,Q=e.hasLoaded,R=Q?"animate":"attr",L=0,K=0;if(!1!==m.enabled){d.rendered||(d.group=H=g.g("range-selector-group").attr({zIndex:7}).add(),d.buttonGroup=F=g.g("range-selector-buttons").add(H),d.zoomText=
g.text(f.rangeSelectorZoom,0,15).add(F),e.styledMode||(d.zoomText.css(m.labelStyle),v["stroke-width"]=y(v["stroke-width"],0)),d.buttonOptions.forEach(function(a,c){t[c]=g.button(a.text,0,0,function(b){var f=a.events&&a.events.click,e;f&&(e=f.call(a,b));!1!==e&&d.clickButton(c);d.isActive=!0},v,E&&E.hover,E&&E.select,E&&E.disabled).attr({"text-align":"center"}).add(F)}),!1!==C&&(d.div=h=A("div",null,{position:"relative",height:0,zIndex:n}),l.parentNode.insertBefore(h,l),d.inputGroup=h=g.g("input-group").add(H),
h.offset=0,d.drawInput("min"),d.drawInput("max")));d.zoomText[R]({x:y(D+z.x,D)});var S=y(D+z.x,D)+d.zoomText.getBBox().width+5;d.buttonOptions.forEach(function(a,c){t[c][R]({x:S});S+=t[c].width+y(m.buttonSpacing,5)});D=e.plotLeft-e.spacing[3];d.updateButtonStates();c&&this.titleCollision(e)&&"top"===G&&"right"===z.align&&z.y+F.getBBox().height-12<(c.y||0)+c.height&&(L=-40);l=z.x-e.spacing[3];"right"===z.align?l+=L-D:"center"===z.align&&(l-=D/2);F.align({y:z.y,width:F.getBBox().width,align:z.align,
x:l},!0,e.spacingBox);d.group.placed=Q;d.buttonGroup.placed=Q;!1!==C&&(L=c&&this.titleCollision(e)&&"top"===G&&"right"===B.align&&B.y-h.getBBox().height-12<(c.y||0)+c.height+e.spacing[0]?-40:0,"left"===B.align?l=D:"right"===B.align&&(l=-Math.max(e.axisOffset[1],-L)),h.align({y:B.y,width:h.getBBox().width,align:B.align,x:B.x+l-2},!0,e.spacingBox),c=h.alignAttr.translateX+h.alignOptions.x-L+h.getBBox().x+2,l=h.alignOptions.width,f=F.alignAttr.translateX+F.getBBox().x,D=F.getBBox().width+20,(B.align===
z.align||f+D>c&&c+l>f&&P<N+h.getBBox().height)&&h.attr({translateX:h.alignAttr.translateX+(e.axisOffset[1]>=-L?0:-L),translateY:h.alignAttr.translateY+F.getBBox().height+10}),d.setInputValue("min",a),d.setInputValue("max",b),d.inputGroup.placed=Q);d.group.align({verticalAlign:G},!0,e.spacingBox);a=d.group.getBBox().height+20;b=d.group.alignAttr.translateY;"bottom"===G&&(I=O&&"bottom"===O.verticalAlign&&O.enabled&&!O.floating?I.legendHeight+y(O.margin,10):0,a=a+I-20,K=b-a-(p?0:m.y)-(e.titleOffset?
e.titleOffset[2]:0)-10);if("top"===G)p&&(K=0),e.titleOffset&&e.titleOffset[0]&&(K=e.titleOffset[0]),K+=e.margin[0]-e.spacing[0]||0;else if("middle"===G)if(N===P)K=0>N?b+void 0:b;else if(N||P)K=0>N||0>P?K-Math.min(N,P):b-a+NaN;d.group.translate(m.x,m.y+Math.floor(K));!1!==C&&(d.minInput.style.marginTop=d.group.translateY+"px",d.maxInput.style.marginTop=d.group.translateY+"px");d.rendered=!0}},getHeight:function(){var a=this.options,b=this.group,d=a.y,e=a.buttonPosition.y,g=a.inputPosition.y;if(a.height)return a.height;
a=b?b.getBBox(!0).height+13+d:0;b=Math.min(g,e);if(0>g&&0>e||0<g&&0<e)a+=Math.abs(b);return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var b=this.chart;z(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()},destroy:function(){var a=this,b=a.minInput,d=a.maxInput;a.unMouseDown();a.unResize();t(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);d&&(d.onfocus=d.onblur=d.onchange=null);C(a,function(b,d){b&&"chart"!==
d&&(b.destroy?b.destroy():b.nodeType&&g(this[d]));b!==v.prototype[d]&&(a[d]=null)},this)}};b.prototype.minFromRange=function(){var a=this.range,b=a.type,d=this.max,e=this.chart.time,g=function(a,c){var d="year"===b?"FullYear":"Month",f=new e.Date(a),g=e.get(d,f);e.set(d,f,g+c);g===e.get(d,f)&&e.set("Date",f,0);return f.getTime()-a};if(B(a)){var h=d-a;var p=a}else h=d+g(d,-a.count),this.chart&&(this.chart.fixedRange=d-h);var c=y(this.dataMin,Number.MIN_VALUE);B(h)||(h=c);h<=c&&(h=c,"undefined"===typeof p&&
(p=g(h,a.count)),this.newMax=Math.min(h+p,this.dataMax));B(d)||(h=void 0);return h};n.RangeSelector||(e(h,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new v(this))}),e(h,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(B(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===
a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),e(h,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var d=this.extraBottomMargin,e=this.extraTopMargin;b&&b.enabled&&!D(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new v(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=
!0)),this.extraBottomMargin!==d||this.extraTopMargin!==e)&&(this.isDirtyBox=!0)}),e(h,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),e(h,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),h.prototype.callbacks.push(function(a){function b(){d=a.xAxis[0].getExtremes();
B(d.min)&&g.render(d.min,d.max)}var d,g=a.rangeSelector;if(g){var h=e(a.xAxis[0],"afterSetExtremes",function(a){g.render(a.min,a.max)});var m=e(a,"redraw",b);b()}e(a,"destroy",function(){g&&(m(),h())})}),n.RangeSelector=v)});G(n,"parts/StockChart.js",[n["parts/Axis.js"],n["parts/Globals.js"],n["parts/Point.js"],n["parts/Utilities.js"]],function(n,h,G,e){var v=e.addEvent,H=e.arrayMax,D=e.arrayMin,t=e.clamp,g=e.defined,E=e.extend,F=e.find,B=e.format,z=e.isNumber,C=e.isString,y=e.merge,m=e.pick,d=e.splat,
b=h.Chart;e=h.Renderer;var u=h.Series,a=h.SVGRenderer,l=h.VMLRenderer,k=u.prototype,q=k.init,w=k.processData,I=G.prototype.tooltipFormatter;h.StockChart=h.stockChart=function(a,c,f){var e=C(a)||a.nodeName,g=arguments[e?1:0],p=g,k=g.series,l=h.getOptions(),n,q=g.chart&&g.chart.panning,t=m(g.navigator&&g.navigator.enabled,l.navigator.enabled,!0),u=q&&/y/.test(q.type),v={startOnTick:!1,endOnTick:!1};g.xAxis=d(g.xAxis||{}).map(function(a,c){return y({minPadding:0,maxPadding:0,overscroll:0,ordinal:!0,
title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},l.xAxis,l.xAxis&&l.xAxis[c],a,{type:"datetime",categories:null},t?v:null)});g.yAxis=d(g.yAxis||{}).map(function(a,c){n=m(a.opposite,!0);return y({labels:{y:-2},opposite:n,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},l.yAxis,l.yAxis&&l.yAxis[c],a,u?v:null)});g.series=null;g=y({chart:{panning:{enabled:!0,type:"x"},pinchType:"x"},navigator:{enabled:t},scrollbar:{enabled:m(l.scrollbar.enabled,!0)},rangeSelector:{enabled:m(l.rangeSelector.enabled,
!0)},title:{text:null},tooltip:{split:m(l.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1}},g,{isStock:!0});g.series=p.series=k;return e?new b(a,g,f):new b(g,c)};v(u,"setOptions",function(a){var c;this.chart.options.isStock&&(this.is("column")||this.is("columnrange")?c={borderWidth:0,shadow:!1}:this.is("scatter")||this.is("sma")||(c={marker:{enabled:!1,radius:2}}),c&&(a.plotOptions[this.type]=y(a.plotOptions[this.type],c)))});v(n,"autoLabelAlign",function(a){var c=this.chart,b=this.options;c=
c._labelPanes=c._labelPanes||{};var d=this.options.labels;this.chart.options.isStock&&"yAxis"===this.coll&&(b=b.top+","+b.height,!c[b]&&d.enabled&&(15===d.x&&(d.x=0),"undefined"===typeof d.align&&(d.align="right"),c[b]=this,a.align="right",a.preventDefault()))});v(n,"destroy",function(){var a=this.chart,c=this.options&&this.options.top+","+this.options.height;c&&a._labelPanes&&a._labelPanes[c]===this&&delete a._labelPanes[c]});v(n,"getPlotLinePath",function(a){function c(a){var c="xAxis"===a?"yAxis":
"xAxis";a=b.options[c];return z(a)?[e[c][a]]:C(a)?[e.get(a)]:d.map(function(a){return a[c]})}var b=this,d=this.isLinked&&!this.series?this.linkedParent.series:this.series,e=b.chart,h=e.renderer,k=b.left,l=b.top,p,n,q,u,v=[],w=[],y=a.translatedValue,A=a.value,B=a.force;if(e.options.isStock&&!1!==a.acrossPanes&&"xAxis"===b.coll||"yAxis"===b.coll){a.preventDefault();w=c(b.coll);var E=b.isXAxis?e.yAxis:e.xAxis;E.forEach(function(a){if(g(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var c=a.isXAxis?
"yAxis":"xAxis";c=g(a.options[c])?e[c][a.options[c]]:e[c][0];b===c&&w.push(a)}});var D=w.length?[]:[b.isXAxis?e.yAxis[0]:e.xAxis[0]];w.forEach(function(a){-1!==D.indexOf(a)||F(D,function(b){return b.pos===a.pos&&b.len===a.len})||D.push(a)});var G=m(y,b.translate(A,null,null,a.old));z(G)&&(b.horiz?D.forEach(function(a){var c;n=a.pos;u=n+a.len;p=q=Math.round(G+b.transB);"pass"!==B&&(p<k||p>k+b.width)&&(B?p=q=t(p,k,k+b.width):c=!0);c||v.push("M",p,n,"L",q,u)}):D.forEach(function(a){var c;p=a.pos;q=p+
a.len;n=u=Math.round(l+b.height-G);"pass"!==B&&(n<l||n>l+b.height)&&(B?n=u=t(n,l,l+b.height):c=!0);c||v.push("M",p,n,"L",q,u)}));a.path=0<v.length?h.crispPolyLine(v,a.lineWidth||1):null}});a.prototype.crispPolyLine=function(a,c){var b;for(b=0;b<a.length;b+=6)a[b+1]===a[b+4]&&(a[b+1]=a[b+4]=Math.round(a[b+1])-c%2/2),a[b+2]===a[b+5]&&(a[b+2]=a[b+5]=Math.round(a[b+2])+c%2/2);return a};e===l&&(l.prototype.crispPolyLine=a.prototype.crispPolyLine);v(n,"afterHideCrosshair",function(){this.crossLabel&&(this.crossLabel=
this.crossLabel.hide())});v(n,"afterDrawCrosshair",function(a){var b,d;if(g(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var e=this.chart,h=this.options.crosshair.label,k=this.horiz,l=this.opposite,p=this.left,n=this.top,q=this.crossLabel,t=h.format,u="",v="inside"===this.options.tickPosition,w=!1!==this.crosshair.snap,y=0,z=a.e||this.cross&&this.cross.e,A=a.point;var C=this.lin2log;if(this.isLog){a=C(this.min);var D=C(this.max)}else a=this.min,D=this.max;C=k?"center":l?"right"===
this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";q||(q=this.crossLabel=e.renderer.label(null,null,null,h.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:h.align||C,padding:m(h.padding,8),r:m(h.borderRadius,3),zIndex:2}).add(this.labelGroup),e.styledMode||q.attr({fill:h.backgroundColor||this.series[0]&&this.series[0].color||"#666666",stroke:h.borderColor||"","stroke-width":h.borderWidth||0}).css(E({color:"#ffffff",
fontWeight:"normal",fontSize:"11px",textAlign:"center"},h.style)));k?(C=w?A.plotX+p:z.chartX,n+=l?0:this.height):(C=l?this.width+p:0,n=w?A.plotY+n:z.chartY);t||h.formatter||(this.isDatetimeAxis&&(u="%b %d, %Y"),t="{value"+(u?":"+u:"")+"}");u=w?A[this.isXAxis?"x":"y"]:this.toValue(k?z.chartX:z.chartY);q.attr({text:t?B(t,{value:u},e):h.formatter.call(this,u),x:C,y:n,visibility:u<a||u>D?"hidden":"visible"});h=q.getBBox();if(k){if(v&&!l||!v&&l)n=q.y-h.height}else n=q.y-h.height/2;k?(b=p-h.x,d=p+this.width-
h.x):(b="left"===this.labelAlign?p:0,d="right"===this.labelAlign?p+this.width:e.chartWidth);q.translateX<b&&(y=b-q.translateX);q.translateX+h.width>=d&&(y=-(q.translateX+h.width-d));q.attr({x:C+y,y:n,anchorX:k?C:this.opposite?0:e.chartWidth,anchorY:k?this.opposite?e.chartHeight:0:n+h.height/2})}});k.init=function(){q.apply(this,arguments);this.setCompare(this.options.compare)};k.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,d){var c=this.compareValue;return"undefined"!==
typeof b&&"undefined"!==typeof c?(b="value"===a?b-c:b/c*100-(100===this.options.compareBase?0:100),d&&(d.change=b),b):0}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};k.processData=function(a){var b,d=-1,e=!0===this.options.compareStart?0:1;w.apply(this,arguments);if(this.xAxis&&this.processedYData){var g=this.processedXData;var h=this.processedYData;var k=h.length;this.pointArrayMap&&(d=this.pointArrayMap.indexOf(this.options.pointValKey||this.pointValKey||"y"));for(b=
0;b<k-e;b++){var l=h[b]&&-1<d?h[b][d]:h[b];if(z(l)&&g[b+e]>=this.xAxis.min&&0!==l){this.compareValue=l;break}}}};v(u,"afterGetExtremes",function(){if(this.modifyValue){var a=[this.modifyValue(this.dataMin),this.modifyValue(this.dataMax)];this.dataMin=D(a);this.dataMax=H(a)}});n.prototype.setCompare=function(a,b){this.isXAxis||(this.series.forEach(function(b){b.setCompare(a)}),m(b,!0)&&this.chart.redraw())};G.prototype.tooltipFormatter=function(a){var b=this.series.chart.numberFormatter;a=a.replace("{point.change}",
(0<this.change?"+":"")+b(this.change,m(this.series.tooltipOptions.changeDecimals,2)));return I.apply(this,[a])};v(u,"render",function(){var a=this.chart;if(!(a.is3d&&a.is3d()||a.polar)&&this.xAxis&&!this.xAxis.isRadial){var b=this.yAxis.len;if(this.xAxis.axisLine){var d=a.plotTop+a.plotHeight-this.yAxis.pos-this.yAxis.len,e=Math.floor(this.xAxis.axisLine.strokeWidth()/2);0<=d&&(b-=Math.max(e-d,0))}!this.clipBox&&this.animate?(this.clipBox=y(a.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=
b):a[this.sharedClipKey]&&(a[this.sharedClipKey].animate({width:this.xAxis.len,height:b}),a[this.sharedClipKey+"m"]&&a[this.sharedClipKey+"m"].animate({width:this.xAxis.len}))}});v(b,"update",function(a){a=a.options;"scrollbar"in a&&this.navigator&&(y(!0,this.options.scrollbar,a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)});v(n,"afterSetScale",function(){var a=this,b=a.chart.options.chart&&a.chart.options.chart.panning;if(b&&("y"===b.type||"xy"===b.type)&&!a.isXAxis&&!g(a.panningState)){var d=
Number.MAX_VALUE,e=Number.MIN_VALUE;a.series.forEach(function(b){d=Math.min(D(b.yData),d)-(a.min&&a.dataMin?a.dataMin-a.min:0);e=Math.max(H(b.yData),e)+(a.max&&a.dataMax?a.max-a.dataMax:0)});a.panningState={startMin:d,startMax:e}}})});G(n,"masters/modules/stock.src.js",[],function(){})});
//# sourceMappingURL=stock.js.map