/*
 Highmaps JS v8.0.4 (2020-03-19)

 Tilemap module

 (c) 2010-2019 Highsoft AS

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/tilemap",["highcharts","highcharts/modules/map"],function(e){d(e);d.Highcharts=e;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function e(u,d,e,y){u.hasOwnProperty(d)||(u[d]=y.apply(null,e))}d=d?d._modules:{};e(d,"modules/tilemap.src.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(d,e){function x(a,b,
c){a=a.options;return{xPad:(a.colsize||1)/-b,yPad:(a.rowsize||1)/-c}}"";var y=e.addEvent,g=e.clamp,u=e.extend,z=e.pick;e=e.seriesType;d.tileShapeTypes={hexagon:{alignDataLabel:d.seriesTypes.scatter.prototype.alignDataLabel,getSeriesPadding:function(a){return x(a,3,2)},haloPath:function(a){if(!a)return[];var b=this.tileEdges;return["M",b.x2-a,b.y1+a,"L",b.x3+a,b.y1+a,b.x4+1.5*a,b.y2,b.x3+a,b.y3-a,b.x2-a,b.y3-a,b.x1-1.5*a,b.y2,"Z"]},translate:function(){var a=this.options,b=this.xAxis,c=this.yAxis,
d=a.pointPadding||0,e=(a.colsize||1)/3,v=(a.rowsize||1)/2,m;this.generatePoints();this.points.forEach(function(a){var r=g(Math.floor(b.len-b.translate(a.x-2*e,0,1,0,1)),-b.len,2*b.len),h=g(Math.floor(b.len-b.translate(a.x-e,0,1,0,1)),-b.len,2*b.len),p=g(Math.floor(b.len-b.translate(a.x+e,0,1,0,1)),-b.len,2*b.len),t=g(Math.floor(b.len-b.translate(a.x+2*e,0,1,0,1)),-b.len,2*b.len),q=g(Math.floor(c.translate(a.y-v,0,1,0,1)),-c.len,2*c.len),f=g(Math.floor(c.translate(a.y,0,1,0,1)),-c.len,2*c.len),k=g(Math.floor(c.translate(a.y+
v,0,1,0,1)),-c.len,2*c.len),l=z(a.pointPadding,d),n=l*Math.abs(h-r)/Math.abs(k-f);n=b.reversed?-n:n;var w=b.reversed?-l:l;l=c.reversed?-l:l;a.x%2&&(m=m||Math.round(Math.abs(k-q)/2)*(c.reversed?-1:1),q+=m,f+=m,k+=m);a.plotX=a.clientX=(h+p)/2;a.plotY=f;r+=n+w;h+=w;p-=w;t-=n+w;q-=l;k+=l;a.tileEdges={x1:r,x2:h,x3:p,x4:t,y1:q,y2:f,y3:k};a.shapeType="path";a.shapeArgs={d:["M",h,q,"L",p,q,t,f,p,k,h,k,r,f,"Z"]}});this.translateColors()}},diamond:{alignDataLabel:d.seriesTypes.scatter.prototype.alignDataLabel,
getSeriesPadding:function(a){return x(a,2,2)},haloPath:function(a){if(!a)return[];var b=this.tileEdges;return["M",b.x2,b.y1+a,"L",b.x3+a,b.y2,b.x2,b.y3-a,b.x1-a,b.y2,"Z"]},translate:function(){var a=this.options,b=this.xAxis,c=this.yAxis,d=a.pointPadding||0,e=a.colsize||1,v=(a.rowsize||1)/2,m;this.generatePoints();this.points.forEach(function(a){var n=g(Math.round(b.len-b.translate(a.x-e,0,1,0,0)),-b.len,2*b.len),h=g(Math.round(b.len-b.translate(a.x,0,1,0,0)),-b.len,2*b.len),p=g(Math.round(b.len-
b.translate(a.x+e,0,1,0,0)),-b.len,2*b.len),t=g(Math.round(c.translate(a.y-v,0,1,0,0)),-c.len,2*c.len),q=g(Math.round(c.translate(a.y,0,1,0,0)),-c.len,2*c.len),f=g(Math.round(c.translate(a.y+v,0,1,0,0)),-c.len,2*c.len),k=z(a.pointPadding,d),l=k*Math.abs(h-n)/Math.abs(f-q);l=b.reversed?-l:l;k=c.reversed?-k:k;a.x%2&&(m=Math.abs(f-t)/2*(c.reversed?-1:1),t+=m,q+=m,f+=m);a.plotX=a.clientX=h;a.plotY=q;n+=l;p-=l;t-=k;f+=k;a.tileEdges={x1:n,x2:h,x3:p,y1:t,y2:q,y3:f};a.shapeType="path";a.shapeArgs={d:["M",
h,t,"L",p,q,h,f,n,q,"Z"]}});this.translateColors()}},circle:{alignDataLabel:d.seriesTypes.scatter.prototype.alignDataLabel,getSeriesPadding:function(a){return x(a,2,2)},haloPath:function(a){return d.seriesTypes.scatter.prototype.pointClass.prototype.haloPath.call(this,a+(a&&this.radius))},translate:function(){var a=this.options,b=this.xAxis,c=this.yAxis,d=a.pointPadding||0,e=(a.rowsize||1)/2,v=a.colsize||1,m,r,u,h,p=!1;this.generatePoints();this.points.forEach(function(a){var n=g(Math.round(b.len-
b.translate(a.x,0,1,0,0)),-b.len,2*b.len),f=g(Math.round(c.translate(a.y,0,1,0,0)),-c.len,2*c.len),k=d,l=!1;"undefined"!==typeof a.pointPadding&&(k=a.pointPadding,p=l=!0);if(!h||p)m=Math.abs(g(Math.floor(b.len-b.translate(a.x+v,0,1,0,0)),-b.len,2*b.len)-n),r=Math.abs(g(Math.floor(c.translate(a.y+e,0,1,0,0)),-c.len,2*c.len)-f),u=Math.floor(Math.sqrt(m*m+r*r)/2),h=Math.min(m,u,r)-k,p&&!l&&(p=!1);a.x%2&&(f+=r*(c.reversed?-1:1));a.plotX=a.clientX=n;a.plotY=f;a.radius=h;a.shapeType="circle";a.shapeArgs=
{x:n,y:f,r:h}});this.translateColors()}},square:{alignDataLabel:d.seriesTypes.heatmap.prototype.alignDataLabel,translate:d.seriesTypes.heatmap.prototype.translate,getSeriesPadding:function(){},haloPath:d.seriesTypes.heatmap.prototype.pointClass.prototype.haloPath}};y(d.Axis,"afterSetAxisTranslation",function(){if(!this.recomputingForTilemap&&"colorAxis"!==this.coll){var a=this,b=a.series.map(function(b){return b.getSeriesPixelPadding&&b.getSeriesPixelPadding(a)}).reduce(function(a,b){return(a&&a.padding)>
(b&&b.padding)?a:b},void 0)||{padding:0,axisLengthFactor:1},c=Math.round(b.padding*b.axisLengthFactor);b.padding&&(a.len-=c,a.recomputingForTilemap=!0,a.setAxisTranslation(),delete a.recomputingForTilemap,a.minPixelPadding+=b.padding,a.len+=c)}});e("tilemap","heatmap",{states:{hover:{halo:{enabled:!0,size:2,opacity:.5,attributes:{zIndex:3}}}},pointPadding:2,tileShape:"hexagon"},{drawPoints:function(){var a=this;d.seriesTypes.column.prototype.drawPoints.call(this);this.points.forEach(function(b){b.graphic&&
b.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(b))})},setOptions:function(){var a=d.seriesTypes.heatmap.prototype.setOptions.apply(this,Array.prototype.slice.call(arguments));this.tileShape=d.tileShapeTypes[a.tileShape];return a},alignDataLabel:function(){return this.tileShape.alignDataLabel.apply(this,Array.prototype.slice.call(arguments))},getSeriesPixelPadding:function(a){var b=a.isXAxis,c=this.tileShape.getSeriesPadding(this);if(!c)return{padding:0,axisLengthFactor:1};var d=Math.round(a.translate(b?
2*c.xPad:c.yPad,0,1,0,1));a=Math.round(a.translate(b?c.xPad:0,0,1,0,1));return{padding:Math.abs(d-a)||0,axisLengthFactor:b?2:1.1}},translate:function(){return this.tileShape.translate.apply(this,Array.prototype.slice.call(arguments))}},u({haloPath:function(){return this.series.tileShape.haloPath.apply(this,Array.prototype.slice.call(arguments))}},d.colorPointMixin));""});e(d,"masters/modules/tilemap.src.js",[],function(){})});
//# sourceMappingURL=tilemap.js.map