/*
 Highcharts Gantt JS v8.0.4 (2020-03-19)

 Tree Grid

 (c) 2016-2019 Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(A){c(A);c.Highcharts=A;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function A(c,u,v,w){c.hasOwnProperty(u)||(c[u]=w.apply(null,v))}c=c?c._modules:{};A(c,"mixins/tree-series.js",[c["parts/Color.js"],c["parts/Utilities.js"]],function(c,u){var v=u.extend,w=u.isArray,k=u.isNumber,x=
u.isObject,F=u.merge,D=u.pick;return{getColor:function(f,b){var r=b.index,g=b.mapOptionsToLevel,n=b.parentColor,t=b.parentColorIndex,p=b.series,a=b.colors,d=b.siblings,h=p.points,y=p.chart.options.chart,B;if(f){h=h[f.i];f=g[f.level]||{};if(g=h&&f.colorByPoint){var e=h.index%(a?a.length:y.colorCount);var l=a&&a[e]}if(!p.chart.styledMode){a=h&&h.options.color;y=f&&f.color;if(B=n)B=(B=f&&f.colorVariation)&&"brightness"===B.key?c.parse(n).brighten(r/d*B.to).get():n;B=D(a,y,l,B,p.color)}var C=D(h&&h.options.colorIndex,
f&&f.colorIndex,e,t,b.colorIndex)}return{color:B,colorIndex:C}},getLevelOptions:function(f){var b=null;if(x(f)){b={};var r=k(f.from)?f.from:1;var g=f.levels;var n={};var t=x(f.defaults)?f.defaults:{};w(g)&&(n=g.reduce(function(b,a){if(x(a)&&k(a.level)){var d=F({},a);var h="boolean"===typeof d.levelIsConstant?d.levelIsConstant:t.levelIsConstant;delete d.levelIsConstant;delete d.level;a=a.level+(h?0:r-1);x(b[a])?v(b[a],d):b[a]=d}return b},{}));g=k(f.to)?f.to:1;for(f=0;f<=g;f++)b[f]=F({},t,x(n[f])?n[f]:
{})}return b},setTreeValues:function g(b,r){var n=r.before,t=r.idRoot,p=r.mapIdToNode[t],a=r.points[b.i],d=a&&a.options||{},h=0,y=[];v(b,{levelDynamic:b.level-(("boolean"===typeof r.levelIsConstant?r.levelIsConstant:1)?0:p.level),name:D(a&&a.name,""),visible:t===b.id||("boolean"===typeof r.visible?r.visible:!1)});"function"===typeof n&&(b=n(b,r));b.children.forEach(function(a,e){var l=v({},r);v(l,{index:e,siblings:b.children.length,visible:b.visible});a=g(a,l);y.push(a);a.visible&&(h+=a.val)});b.visible=
0<h||b.visible;n=D(d.value,h);v(b,{children:y,childrenTotal:h,isLeaf:b.visible&&!h,val:n});return b},updateRootId:function(b){if(x(b)){var r=x(b.options)?b.options:{};r=D(b.rootNode,r.rootId,"");x(b.userOptions)&&(b.userOptions.rootId=r);b.rootNode=r}return r}}});A(c,"parts-gantt/Tree.js",[c["parts/Utilities.js"]],function(c){var u=c.extend,v=c.isNumber,w=c.pick,k=function(c,k){var f=c.reduce(function(b,f){var g=w(f.parent,"");"undefined"===typeof b[g]&&(b[g]=[]);b[g].push(f);return b},{});Object.keys(f).forEach(function(b,
c){var g=f[b];""!==b&&-1===k.indexOf(b)&&(g.forEach(function(b){c[""].push(b)}),delete c[b])});return f},x=function(c,k,f,b,r,g){var n=0,t=0,p=g&&g.after,a=g&&g.before;k={data:b,depth:f-1,id:c,level:f,parent:k};var d,h;"function"===typeof a&&a(k,g);a=(r[c]||[]).map(function(a){var b=x(a.id,c,f+1,a,r,g),e=a.start;a=!0===a.milestone?e:a.end;d=!v(d)||e<d?e:d;h=!v(h)||a>h?a:h;n=n+1+b.descendants;t=Math.max(b.height+1,t);return b});b&&(b.start=w(b.start,d),b.end=w(b.end,h));u(k,{children:a,descendants:n,
height:t});"function"===typeof p&&p(k,g);return k};return{getListOfParents:k,getNode:x,getTree:function(c,u){var f=c.map(function(b){return b.id});c=k(c,f);return x("",null,1,null,c,u)}}});A(c,"parts-gantt/GridAxis.js",[c["parts/Globals.js"],c["parts/Tick.js"],c["parts/Utilities.js"]],function(c,u,v){var w=v.addEvent,k=v.defined,x=v.erase,A=v.find,D=v.isArray,f=v.isNumber,b=v.merge,r=v.pick,g=v.timeUnits,n=v.wrap,t=c.dateFormat,p=function(e){return v.isObject(e,!0)},a=c.Chart,d=c.Axis,h=function(e){var l=
e.options;l.labels||(l.labels={});l.labels.align=r(l.labels.align,"center");e.categories||(l.showLastLabel=!1);e.labelRotation=0;l.labels.rotation=0},y={top:0,right:1,bottom:2,left:3,0:"top",1:"right",2:"bottom",3:"left"};d.prototype.isOuterAxis=function(){var e=this,l=e.columnIndex,a=e.linkedParent&&e.linkedParent.columns||e.columns,b=l?e.linkedParent:e,h=-1,d=0;e.chart[e.coll].forEach(function(l,m){l.side!==e.side||l.options.isInternal||(d=m,l===b&&(h=m))});return d===h&&(f(l)?a.length===l:!0)};
d.prototype.getMaxLabelDimensions=function(e,l){var a={width:0,height:0};l.forEach(function(l){l=e[l];if(p(l)){var C=p(l.label)?l.label:{};l=C.getBBox?C.getBBox().height:0;C.textStr&&!f(C.textPxLength)&&(C.textPxLength=C.getBBox().width);C=f(C.textPxLength)?Math.round(C.textPxLength):0;a.height=Math.max(l,a.height);a.width=Math.max(C,a.width)}});return a};c.dateFormats.W=function(e){e=new this.Date(e);var l=(this.get("Day",e)+6)%7,a=new this.Date(e.valueOf());this.set("Date",a,this.get("Date",e)-
l+3);l=new this.Date(this.get("FullYear",a),0,1);4!==this.get("Day",l)&&(this.set("Month",e,0),this.set("Date",e,1+(11-this.get("Day",l))%7));return(1+Math.floor((a.valueOf()-l.valueOf())/6048E5)).toString()};c.dateFormats.E=function(e){return t("%a",e,!0).charAt(0)};w(u,"afterGetLabelPosition",function(e){var l=this.label,a=this.axis,b=a.reversed,h=a.chart,d=a.options,z=d&&p(d.grid)?d.grid:{};d=a.options.labels;var m=d.align,q=y[a.side],g=e.tickmarkOffset,c=a.tickPositions,n=this.pos-g;c=f(c[e.index+
1])?c[e.index+1]-g:a.max+g;var E=a.tickSize("tick",!0);g=D(E)?E[0]:0;E=E&&E[1]/2;if(!0===z.enabled){if("top"===q){z=a.top+a.offset;var t=z-g}else"bottom"===q?(t=h.chartHeight-a.bottom+a.offset,z=t+g):(z=a.top+a.len-a.translate(b?c:n),t=a.top+a.len-a.translate(b?n:c));"right"===q?(q=h.chartWidth-a.right+a.offset,b=q+g):"left"===q?(b=a.left+a.offset,q=b-g):(q=Math.round(a.left+a.translate(b?c:n))-E,b=Math.round(a.left+a.translate(b?n:c))-E);this.slotWidth=b-q;e.pos.x="left"===m?q:"right"===m?b:q+(b-
q)/2;e.pos.y=t+(z-t)/2;h=h.renderer.fontMetrics(d.style.fontSize,l.element);l=l.getBBox().height;d.useHTML?e.pos.y+=h.b+-(l/2):(l=Math.round(l/h.h),e.pos.y+=(h.b-(h.h-h.f))/2+-((l-1)*h.h/2));e.pos.x+=a.horiz&&d.x||0}});w(d,"afterTickSize",function(a){var e=d.defaultLeftAxisOptions,b=this.horiz,h=this.options.grid;h=void 0===h?{}:h;var g=this.maxLabelDimensions;h.enabled&&(e=2*Math.abs(e.labels.x),b=b?h.cellHeight||e+g.height:e+g.width,D(a.tickSize)?a.tickSize[0]=b:a.tickSize=[b])});w(d,"afterGetTitlePosition",
function(a){var e=this.options;if(!0===(e&&p(e.grid)?e.grid:{}).enabled){var b=this.axisTitle,h=b&&b.getBBox().width,d=this.horiz,g=this.left,z=this.top,m=this.width,q=this.height,c=e.title;e=this.opposite;var n=this.offset,f=this.tickSize()||[0],t=c.x||0,k=c.y||0,B=r(c.margin,d?5:10);b=this.chart.renderer.fontMetrics(c.style&&c.style.fontSize,b).f;f=(d?z+q:g)+f[0]/2*(e?-1:1)*(d?1:-1)+(this.side===y.bottom?b:0);a.titlePosition.x=d?g-h/2-B+t:f+(e?m:0)+n+t;a.titlePosition.y=d?f-(e?q:0)+(e?b:-b)/2+n+
k:z-B+k}});n(d.prototype,"unsquish",function(a){var e=this.options;return!0===(e&&p(e.grid)?e.grid:{}).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))});w(d,"afterSetOptions",function(a){var e=this.options;a=a.userOptions;var h=e&&p(e.grid)?e.grid:{};if(!0===h.enabled){var d=b(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},
month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(k(a.linkedTo)&&!k(a.tickPixelInterval)&&(d.tickPixelInterval=350),k(a.tickPixelInterval)||!k(a.linkedTo)||k(a.tickPositioner)||k(a.tickInterval)||(d.tickPositioner=function(a,e){var b=this.linkedParent&&
this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(b){var m,q=d.units;for(m=0;m<q.length;m++)if(q[m][0]===b.unitName){var h=m;break}if(q[h+1]){var l=q[h+1][0];var c=(q[h+1][1]||[1])[0]}else"year"===b.unitName&&(l="year",c=10*b.count);b=g[l];this.tickInterval=b*c;return this.getTimeTicks({unitRange:b,count:c,unitName:l},a,e,this.options.startOfWeek)}}));b(!0,this.options,d);this.horiz&&(e.minPadding=r(a.minPadding,0),e.maxPadding=r(a.maxPadding,0));f(e.grid.borderWidth)&&(e.tickWidth=
e.lineWidth=h.borderWidth)}});w(d,"afterSetAxisTranslation",function(){var a=this.options,b=a&&p(a.grid)?a.grid:{},h=this.tickPositions&&this.tickPositions.info,d=this.userOptions.labels||{};this.horiz&&(!0===b.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),h&&(!1===a.dateTimeLabelFormats[h.unitName].range||1<h.count)&&!k(d.align)&&(a.labels.align="left",k(d.x)||(a.labels.x=3)))});w(d,"trimTicks",function(){var a=this.options,b=a&&p(a.grid)?a.grid:{},h=this.categories,d=this.tickPositions,
g=d[0],c=d[d.length-1],z=this.linkedParent&&this.linkedParent.min||this.min,m=this.linkedParent&&this.linkedParent.max||this.max,q=this.tickInterval;!0!==b.enabled||h||!this.horiz&&!this.isLinked||(g<z&&g+q>z&&!a.startOnTick&&(d[0]=z),c>m&&c-q<m&&!a.endOnTick&&(d[d.length-1]=m))});w(d,"afterRender",function(){var a=this.options,b=a&&p(a.grid)?a.grid:{},h=this.chart.renderer;if(!0===b.enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();
if(this.isOuterAxis()&&this.axisLine){var d=a.lineWidth;if(d){var g=this.getLinePath(d);var c=g.indexOf("M")+1;var z=g.indexOf("L")+1;b=g.indexOf("M")+2;var m=g.indexOf("L")+2;var q=(this.tickSize("tick")[0]-1)*(this.side===y.top||this.side===y.left?-1:1);this.horiz?(g[b]+=q,g[m]+=q):(g[c]+=q,g[z]+=q);this.axisLineExtra?this.axisLineExtra.animate({d:g}):(this.axisLineExtra=h.path(g).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),h.styledMode||this.axisLineExtra.attr({stroke:a.lineColor,
"stroke-width":d}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(this.columns||[]).forEach(function(a){a.render()})}});var B={afterGetOffset:function(){(this.columns||[]).forEach(function(a){a.getOffset()})},afterInit:function(){var a=this.chart,g=this.userOptions,c=this.options;c=c&&p(c.grid)?c.grid:{};c.enabled&&(h(this),n(this,"labelFormatter",function(a){var m=this.axis,q=m.tickPositions,b=this.value,e=(m.isLinked?m.linkedParent:m).series[0],h=b===q[0];q=b===q[q.length-1];e=e&&A(e.options.data,
function(a){return a[m.isXAxis?"x":"y"]===b});this.isFirst=h;this.isLast=q;this.point=e;return a.call(this)}));if(c.columns)for(var f=this.columns=[],t=this.columnIndex=0;++t<c.columns.length;){var y=b(g,c.columns[c.columns.length-t-1],{linkedTo:0,type:"category"});delete y.grid.columns;y=new d(this.chart,y,!0);y.isColumn=!0;y.columnIndex=t;x(a.axes,y);x(a[this.coll],y);f.push(y)}},afterSetOptions:function(a){a=(a=a.userOptions)&&p(a.grid)?a.grid:{};var e=a.columns;a.enabled&&e&&b(!0,this.options,
e[e.length-1])},afterSetScale:function(){(this.columns||[]).forEach(function(a){a.setScale()})},destroy:function(a){(this.columns||[]).forEach(function(b){b.destroy(a.keepEvents)})},init:function(a){var b=(a=a.userOptions)&&p(a.grid)?a.grid:{};b.enabled&&k(b.borderColor)&&(a.tickColor=a.lineColor=b.borderColor)}};Object.keys(B).forEach(function(a){w(d,a,B[a])});w(a,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.columns||[]).forEach(function(a){a.setAxisSize();a.setAxisTranslation()})})})});
A(c,"modules/broken-axis.src.js",[c["parts/Globals.js"],c["parts/Utilities.js"],c["parts/Stacking.js"]],function(c,u,v){var w=u.addEvent,k=u.extend,x=u.find,A=u.fireEvent,D=u.isArray,f=u.pick,b=c.Axis;u=c.Series;var r=function(b,c){return x(c,function(c){return c.from<b&&b<c.to})};k(b.prototype,{isInBreak:function(b,c){var g=b.repeat||Infinity,f=b.from,a=b.to-b.from;c=c>=f?(c-f)%g:g-(f-c)%g;return b.inclusive?c<=a:c<a&&0!==c},isInAnyBreak:function(b,c){var g=this.options.breaks,n=g&&g.length,a;if(n){for(;n--;)if(this.isInBreak(g[n],
b)){var d=!0;a||(a=f(g[n].showPoints,!this.isXAxis))}var h=d&&c?d&&!a:d}return h}});w(b,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});w(b,"afterSetTickPositions",function(){if(this.isBroken){var b=this.tickPositions,c=this.tickPositions.info,f=[],p;for(p=0;p<b.length;p++)this.isInAnyBreak(b[p])||f.push(b[p]);this.tickPositions=f;this.tickPositions.info=c}});w(b,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});b.prototype.setBreaks=
function(c,n){function g(b){var c=b,h;for(h=0;h<a.breakArray.length;h++){var e=a.breakArray[h];if(e.to<=b)c-=e.len;else if(e.from>=b)break;else if(a.isInBreak(e,b)){c-=b-e.from;break}}return c}function p(b){var c;for(c=0;c<a.breakArray.length;c++){var d=a.breakArray[c];if(d.from>=b)break;else d.to<b?b+=d.len:a.isInBreak(d,b)&&(b+=d.len)}return b}var a=this,d=D(c)&&!!c.length;a.isDirty=a.isBroken!==d;a.isBroken=d;a.options.breaks=a.userOptions.breaks=c;a.forceRedraw=!0;a.series.forEach(function(a){a.isDirty=
!0});d||a.val2lin!==g||(delete a.val2lin,delete a.lin2val);d&&(a.userOptions.ordinal=!1,a.val2lin=g,a.lin2val=p,a.setExtremes=function(a,c,d,e,g){if(this.isBroken){for(var h,l=this.options.breaks;h=r(a,l);)a=h.to;for(;h=r(c,l);)c=h.from;c<a&&(c=a)}b.prototype.setExtremes.call(this,a,c,d,e,g)},a.setAxisTranslation=function(c){b.prototype.setAxisTranslation.call(this,c);this.unitLength=null;if(this.isBroken){c=a.options.breaks;var d=[],g=[],e=0,h,n=a.userMin||a.min,p=a.userMax||a.max,k=f(a.pointRangePadding,
0),t;c.forEach(function(b){h=b.repeat||Infinity;a.isInBreak(b,n)&&(n+=b.to%h-n%h);a.isInBreak(b,p)&&(p-=p%h-b.from%h)});c.forEach(function(a){m=a.from;for(h=a.repeat||Infinity;m-h>n;)m-=h;for(;m<n;)m+=h;for(t=m;t<p;t+=h)d.push({value:t,move:"in"}),d.push({value:t+(a.to-a.from),move:"out",size:a.breakSize})});d.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});var z=0;var m=n;d.forEach(function(a){z+="in"===a.move?1:-1;1===z&&"in"===a.move&&(m=a.value);
0===z&&(g.push({from:m,to:a.value,len:a.value-m-(a.size||0)}),e+=a.value-m-(a.size||0))});a.breakArray=g;a.unitLength=p-n-e+k;A(a,"afterBreaks");a.staticScale?a.transA=a.staticScale:a.unitLength&&(a.transA*=(p-a.min+k)/a.unitLength);k&&(a.minPixelPadding=a.transA*a.minPointOffset);a.min=n;a.max=p}});f(n,!0)&&this.chart.redraw()};w(u,"afterGeneratePoints",function(){var b=this.options.connectNulls,c=this.points,f=this.xAxis,p=this.yAxis;if(this.isDirty)for(var a=c.length;a--;){var d=c[a],h=!(null===
d.y&&!1===b)&&(f&&f.isInAnyBreak(d.x,!0)||p&&p.isInAnyBreak(d.y,!0));d.visible=h?!1:!1!==d.options.visible}});w(u,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,f(this.pointArrayMap,["y"]))});c.Series.prototype.drawBreaks=function(b,c){var g=this,n=g.points,a,d,h,k;b&&c.forEach(function(c){a=b.breakArray||[];d=b.isXAxis?b.min:f(g.options.threshold,b.min);n.forEach(function(e){k=f(e["stack"+c.toUpperCase()],e[c]);a.forEach(function(a){h=!1;if(d<a.from&&k>a.to||
d>a.from&&k<a.from)h="pointBreak";else if(d<a.from&&k>a.from&&k<a.to||d>a.from&&k>a.to&&k<a.from)h="pointInBreak";h&&A(b,h,{point:e,brk:a})})})})};c.Series.prototype.gappedPath=function(){var b=this.currentDataGrouping,c=b&&b.gapSize;b=this.options.gapSize;var f=this.points.slice(),k=f.length-1,a=this.yAxis,d;if(b&&0<k)for("value"!==this.options.gapUnit&&(b*=this.basePointRange),c&&c>b&&c>=this.basePointRange&&(b=c),d=void 0;k--;)d&&!1!==d.visible||(d=f[k+1]),c=f[k],!1!==d.visible&&!1!==c.visible&&
(d.x-c.x>b&&(d=(c.x+d.x)/2,f.splice(k+1,0,{isNull:!0,x:d}),this.options.stacking&&(d=a.stacks[this.stackKey][d]=new v(a,a.options.stackLabels,!1,d,this.stack),d.total=0)),d=c);return this.getGraphPath(f)}});A(c,"parts-gantt/TreeGrid.js",[c["parts/Globals.js"],c["mixins/tree-series.js"],c["parts/Tick.js"],c["parts-gantt/Tree.js"],c["parts/Utilities.js"]],function(c,u,v,w,k){var x=k.addEvent,A=k.defined,D=k.fireEvent,f=k.extend,b=k.isNumber,r=k.isString,g=k.merge,n=k.pick,t=k.wrap,p=function(a){return Array.prototype.slice.call(a,
1)},a=k.find,d=u.getLevelOptions,h=function(a){return k.isObject(a,!0)};c=c.Axis;u=function(a,b){var c;for(c in b)if(Object.hasOwnProperty.call(b,c)){var m=b[c];t(a,c,m)}};var y=function(a,b){var c=a.collapseStart;a=a.collapseEnd;a>=b&&(c-=.5);return{from:c,to:a,showPoints:!1}},B=function(a){return Object.keys(a.mapOfPosToGridNode).reduce(function(b,c){c=+c;a.min<=c&&a.max>=c&&!a.isInAnyBreak(c)&&b.push(c);return b},[])},e=function(a,b){var c=a.options.breaks||[],m=y(b,a.max);return c.some(function(a){return a.from===
m.from&&a.to===m.to})},l=function(a,b){var c=a.options.breaks||[];a=y(b,a.max);c.push(a);return c},C=function(a,b){var c=a.options.breaks||[],m=y(b,a.max);return c.reduce(function(a,b){b.to===m.to&&b.from===m.from||a.push(b);return a},[])},H=function(a,c){var d=a.labelIcon,m=!d,h=c.renderer,e=c.xy,g=c.options,f=g.width,k=g.height,l=e.x-f/2-g.padding;e=e.y-k/2;var z=c.collapsed?90:180,p=c.show&&b(e);m&&(a.labelIcon=d=h.path(h.symbols[g.type](g.x,g.y,f,k)).addClass("highcharts-label-icon").add(c.group));
p||d.attr({y:-9999});h.styledMode||d.attr({"stroke-width":1,fill:n(c.color,"#666666")}).css({cursor:"pointer",stroke:g.lineColor,strokeWidth:g.lineWidth});d[m?"attr":"animate"]({translateX:l,translateY:e,rotation:z})},I=function(b,c,d){var m=[],e=[],g={},f={},q=-1,k="boolean"===typeof c?c:!1;b=w.getTree(b,{after:function(a){a=f[a.pos];var b=0,c=0;a.children.forEach(function(a){c+=a.descendants+1;b=Math.max(a.height+1,b)});a.descendants=c;a.height=b;a.collapsed&&e.push(a)},before:function(b){var c=
h(b.data)?b.data:{},d=r(c.name)?c.name:"",e=g[b.parent];e=h(e)?f[e.pos]:null;var l=function(a){return a.name===d},n;k&&h(e)&&(n=a(e.children,l))?(l=n.pos,n.nodes.push(b)):l=q++;f[l]||(f[l]=n={depth:e?e.depth+1:0,name:d,nodes:[b],children:[],pos:l},-1!==l&&m.push(d),h(e)&&e.children.push(n));r(b.id)&&(g[b.id]=b);!0===c.collapsed&&(n.collapsed=!0);b.pos=l}});f=function(a,b){var c=function(a,d,e){var m=d+(-1===d?0:b-1),g=(m-d)/2,f=d+g;a.nodes.forEach(function(a){var b=a.data;h(b)&&(b.y=d+b.seriesIndex,
delete b.seriesIndex);a.pos=f});e[f]=a;a.pos=f;a.tickmarkOffset=g+.5;a.collapseStart=m+.5;a.children.forEach(function(a){c(a,m+1,e);m=a.collapseEnd-.5});a.collapseEnd=m+.5;return e};return c(a["-1"],-1,{})}(f,d);return{categories:m,mapOfIdToNode:g,mapOfPosToGridNode:f,collapsedNodes:e,tree:b}},G=function(a){a.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(b){var c=b.options||{},e=c.labels,m,f=c.uniqueNames,k=0;if(!b.mapOfPosToGridNode||b.series.some(function(a){return!a.hasRendered||
a.isDirtyData||a.isDirty})){c=b.series.reduce(function(a,b){b.visible&&(b.options.data.forEach(function(b){h(b)&&(b.seriesIndex=k,a.push(b))}),!0===f&&k++);return a},[]);var n=I(c,f,!0===f?k:1);b.categories=n.categories;b.mapOfPosToGridNode=n.mapOfPosToGridNode;b.hasNames=!0;b.tree=n.tree;b.series.forEach(function(a){var b=a.options.data.map(function(a){return h(a)?g(a):a});a.visible&&a.setData(b,!1)});b.mapOptionsToLevel=d({defaults:e,from:1,levels:e.levels,to:b.tree.height});"beforeRender"===a.type&&
(m=x(b,"foundExtremes",function(){n.collapsedNodes.forEach(function(a){a=l(b,a);b.setBreaks(a,!1)});m()}))}})};u(c.prototype,{init:function(a,b,c){var d="treegrid"===c.type;d&&(x(b,"beforeRender",G),x(b,"beforeRedraw",G),c=g({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},c,{reversed:!0,grid:{columns:void 0}}));a.apply(this,[b,c]);d&&(this.hasNames=!0,this.options.showLastLabel=
!0)},getMaxLabelDimensions:function(a){var c=this.options,d=c&&c.labels;c=d&&b(d.indentation)?c.labels.indentation:0;d=a.apply(this,p(arguments));if("treegrid"===this.options.type&&this.mapOfPosToGridNode){var e=this.mapOfPosToGridNode[-1].height;d.width+=c*(e-1)}return d},generateTick:function(a,b){var c=h(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},d=this.ticks,e=d[b],g;if("treegrid"===this.options.type){var f=this.mapOfPosToGridNode[b];(c=c[f.depth])&&(g={labels:c});e?(e.parameters.category=
f.name,e.options=g,e.addLabel()):d[b]=new v(this,b,null,void 0,{category:f.name,tickmarkOffset:f.tickmarkOffset,options:g})}else a.apply(this,p(arguments))},setTickInterval:function(a){var b=this.options;"treegrid"===b.type?(this.min=n(this.userMin,b.min,this.dataMin),this.max=n(this.userMax,b.max,this.dataMax),D(this,"foundExtremes"),this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?B(this):[]):a.apply(this,p(arguments))}});u(v.prototype,
{getLabelPosition:function(a,c,d,e,g,f,k,l,p){var m=n(this.options&&this.options.labels,f);f=this.pos;var q=this.axis,r="treegrid"===q.options.type;a=a.apply(this,[c,d,e,g,m,k,l,p]);r&&(c=m&&h(m.symbol)?m.symbol:{},m=m&&b(m.indentation)?m.indentation:0,f=(f=(q=q.mapOfPosToGridNode)&&q[f])&&f.depth||1,a.x+=c.width+2*c.padding+(f-1)*m);return a},renderLabel:function(a){var b=this,c=b.pos,d=b.axis,f=b.label,g=d.mapOfPosToGridNode,k=d.options,l=n(b.options&&b.options.labels,k&&k.labels),r=l&&h(l.symbol)?
l.symbol:{},t=(g=g&&g[c])&&g.depth;k="treegrid"===k.type;var u=!(!f||!f.element),v=-1<d.tickPositions.indexOf(c);c=d.chart.styledMode;k&&g&&u&&f.addClass("highcharts-treegrid-node-level-"+t);a.apply(b,p(arguments));k&&g&&u&&0<g.descendants&&(d=e(d,g),H(b,{color:!c&&f.styles.color,collapsed:d,group:f.parentGroup,options:r,renderer:f.renderer,show:v,xy:f.xy}),r="highcharts-treegrid-node-"+(d?"expanded":"collapsed"),f.addClass("highcharts-treegrid-node-"+(d?"collapsed":"expanded")).removeClass(r),c||
f.css({cursor:"pointer"}),[f,b.labelIcon].forEach(function(a){a.attachedTreeGridEvents||(x(a.element,"mouseover",function(){f.addClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:"underline"})}),x(a.element,"mouseout",function(){var a=A(l.style)?l.style:{};f.removeClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:a.textDecoration})}),x(a.element,"click",function(){b.toggleCollapse()}),a.attachedTreeGridEvents=!0)}))}});f(v.prototype,
{collapse:function(a){var b=this.axis,c=l(b,b.mapOfPosToGridNode[this.pos]);b.setBreaks(c,n(a,!0))},expand:function(a){var b=this.axis,c=C(b,b.mapOfPosToGridNode[this.pos]);b.setBreaks(c,n(a,!0))},toggleCollapse:function(a){var b=this.axis;var c=b.mapOfPosToGridNode[this.pos];c=e(b,c)?C(b,c):l(b,c);b.setBreaks(c,n(a,!0))}});c.prototype.utils={getNode:w.getNode}});A(c,"masters/modules/treegrid.src.js",[],function(){})});
//# sourceMappingURL=treegrid.js.map