/*
 Highcharts JS v8.0.4 (2020-03-19)

 (c) 2009-2018 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(f){"object"===typeof module&&module.exports?(f["default"]=f,module.exports=f):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(E){f(E);f.Highcharts=E;return f}):f("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(f){function E(l,a,e,b){l.hasOwnProperty(a)||(l[a]=b.apply(null,e))}f=f?f._modules:{};E(f,"parts-more/Pane.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(l,a){function e(h,b,a){return Math.sqrt(Math.pow(h-
a[0],2)+Math.pow(b-a[1],2))<a[2]/2}var b=a.addEvent,r=a.extend,q=a.merge,y=a.pick,f=a.splat,B=l.CenteredSeriesMixin;l.Chart.prototype.collectionsWithUpdate.push("pane");a=function(){function h(h,b){this.options=this.chart=this.center=this.background=void 0;this.coll="pane";this.defaultOptions={center:["50%","50%"],size:"85%",innerSize:"0%",startAngle:0};this.defaultBackgroundOptions={shape:"circle",borderWidth:1,borderColor:"#cccccc",backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,
"#ffffff"],[1,"#e6e6e6"]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"};this.init(h,b)}h.prototype.init=function(h,b){this.chart=b;this.background=[];b.pane.push(this);this.setOptions(h)};h.prototype.setOptions=function(h){this.options=q(this.defaultOptions,this.chart.angular?{background:{}}:void 0,h)};h.prototype.render=function(){var h=this.options,b=this.options.background,a=this.chart.renderer;this.group||(this.group=a.g("pane-group").attr({zIndex:h.zIndex||0}).add());
this.updateCenter();if(b)for(b=f(b),h=Math.max(b.length,this.background.length||0),a=0;a<h;a++)b[a]&&this.axis?this.renderBackground(q(this.defaultBackgroundOptions,b[a]),a):this.background[a]&&(this.background[a]=this.background[a].destroy(),this.background.splice(a,1))};h.prototype.renderBackground=function(h,b){var a="animate",k={"class":"highcharts-pane "+(h.className||"")};this.chart.styledMode||r(k,{fill:h.backgroundColor,stroke:h.borderColor,"stroke-width":h.borderWidth});this.background[b]||
(this.background[b]=this.chart.renderer.path().add(this.group),a="attr");this.background[b][a]({d:this.axis.getPlotBandPath(h.from,h.to,h)}).attr(k)};h.prototype.updateCenter=function(h){this.center=(h||this.axis||{}).center=B.getCenter.call(this)};h.prototype.update=function(h,b){q(!0,this.options,h);q(!0,this.chart.options.pane,h);this.setOptions(this.options);this.render();this.chart.axes.forEach(function(h){h.pane===this&&(h.pane=null,h.update({},b))},this)};return h}();l.Chart.prototype.getHoverPane=
function(h){var b=this,a;h&&b.pane.forEach(function(w){var k=h.chartX-b.plotLeft,m=h.chartY-b.plotTop;e(b.inverted?m:k,b.inverted?k:m,w.center)&&(a=w)});return a};b(l.Chart,"afterIsInsidePlot",function(h){this.polar&&(h.isInsidePlot=this.pane.some(function(b){return e(h.x,h.y,b.center)}))});b(l.Pointer,"beforeGetHoverData",function(h){var b=this.chart;b.polar&&(b.hoverPane=b.getHoverPane(h),h.filter=function(a){return a.visible&&!(!h.shared&&a.directTouch)&&y(a.options.enableMouseTracking,!0)&&(!b.hoverPane||
a.xAxis.pane===b.hoverPane)})});b(l.Pointer,"afterGetHoverData",function(h){var b=this.chart;h.hoverPoint&&h.hoverPoint.plotX&&h.hoverPoint.plotY&&b.hoverPane&&!e(h.hoverPoint.plotX,h.hoverPoint.plotY,b.hoverPane.center)&&(h.hoverPoint=void 0)});l.Pane=a;return l.Pane});E(f,"parts-more/RadialAxis.js",[f["parts/Globals.js"],f["parts/Tick.js"],f["parts/Utilities.js"]],function(l,a,e){var b=e.addEvent,r=e.correctFloat,q=e.defined,y=e.extend,f=e.fireEvent,B=e.merge,h=e.pick,u=e.pInt,w=e.relativeLength;
e=e.wrap;var m=l.Axis;l=l.noop;var k=m.prototype,A=a.prototype;var v={getOffset:l,redraw:function(){this.isDirty=!1},render:function(){this.isDirty=!1},createLabelCollector:function(){return!1},setScale:l,setCategories:l,setTitle:l};var t={defaultRadialGaugeOptions:{labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2},defaultCircularOptions:{gridLineWidth:1,
labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0},defaultRadialOptions:{gridLineInterpolation:"circle",gridLineWidth:1,labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}},setOptions:function(d){d=this.options=B(m.defaultOptions,this.defaultPolarOptions,d);d.plotBands||(d.plotBands=[]);f(this,"afterSetOptions")},getOffset:function(){k.getOffset.call(this);this.chart.axisOffset[this.side]=
0},getLinePath:function(d,c,g){d=this.pane.center;var p=this.chart,z=h(c,d[2]/2-this.offset);"undefined"===typeof g&&(g=this.horiz?0:this.center&&-this.center[3]/2);g&&(z+=g);this.isCircular||"undefined"!==typeof c?(c=this.chart.renderer.symbols.arc(this.left+d[0],this.top+d[1],z,z,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0}),c.xBounds=[this.left+d[0]],c.yBounds=[this.top+d[1]-z]):(c=this.postTranslate(this.angleRad,z),c=["M",this.center[0]+p.plotLeft,this.center[1]+p.plotTop,
"L",c.x,c.y]);return c},setAxisTranslation:function(){k.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):(this.center[2]-this.center[3])/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)},beforeSetTickPositions:function(){this.autoConnect=this.isCircular&&"undefined"===typeof h(this.userMax,this.options.max)&&r(this.endAngleRad-this.startAngleRad)===r(2*Math.PI);!this.isCircular&&
this.chart.inverted&&this.max++;this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)},setAxisSize:function(){k.setAxisSize.call(this);if(this.isRadial){this.pane.updateCenter(this);var d=this.center=y([],this.pane.center);if(this.isCircular)this.sector=this.endAngleRad-this.startAngleRad;else{var c=this.postTranslate(this.angleRad,d[3]/2);d[0]=c.x-this.chart.plotLeft;d[1]=c.y-this.chart.plotTop}this.len=this.width=this.height=(d[2]-d[3])*h(this.sector,1)/2}},
getPosition:function(d,c){d=this.translate(d);return this.postTranslate(this.isCircular?d:this.angleRad,h(this.isCircular?c:0>d?0:d,this.center[2]/2)-this.offset)},postTranslate:function(d,c){var g=this.chart,p=this.center;d=this.startAngleRad+d;return{x:g.plotLeft+p[0]+Math.cos(d)*c,y:g.plotTop+p[1]+Math.sin(d)*c}},getPlotBandPath:function(d,c,g){var p=this.center,z=this.startAngleRad,x=p[2]/2,n=[h(g.outerRadius,"100%"),g.innerRadius,h(g.thickness,10)],b=Math.min(this.offset,0),a=/%$/;var k=this.isCircular;
if("polygon"===this.options.gridLineInterpolation)n=this.getPlotLinePath({value:d}).concat(this.getPlotLinePath({value:c,reverse:!0}));else{d=Math.max(d,this.min);c=Math.min(c,this.max);k||(n[0]=this.translate(d),n[1]=this.translate(c));n=n.map(function(g){a.test(g)&&(g=u(g,10)*x/100);return g});if("circle"!==g.shape&&k)d=z+this.translate(d),c=z+this.translate(c);else{d=-Math.PI/2;c=1.5*Math.PI;var e=!0}n[0]-=b;n[2]-=b;n=this.chart.renderer.symbols.arc(this.left+p[0],this.top+p[1],n[0],n[0],{start:Math.min(d,
c),end:Math.max(d,c),innerR:h(n[1],n[0]-n[2]),open:e});k&&(k=(c+d)/2,b=this.left+p[0]+p[2]/2*Math.cos(k),n.xBounds=k>-Math.PI/2&&k<Math.PI/2?[b,this.chart.plotWidth]:[0,b],n.yBounds=[this.top+p[1]+p[2]/2*Math.sin(k)],n.yBounds[0]+=k>-Math.PI&&0>k||k>Math.PI?-10:10)}return n},getCrosshairPosition:function(d,c,g){var p=d.value,z=this.pane.center;if(this.isCircular){if(q(p))d.point&&(x=d.point.shapeArgs||{},x.start&&(p=this.chart.inverted?this.translate(d.point.rectPlotY,!0):d.point.x));else{var x=d.chartX||
0;var n=d.chartY||0;p=this.translate(Math.atan2(n-g,x-c)-this.startAngleRad,!0)}d=this.getPosition(p);x=d.x;n=d.y}else q(p)||(x=d.chartX,n=d.chartY),q(x)&&q(n)&&(g=z[1]+this.chart.plotTop,p=this.translate(Math.min(Math.sqrt(Math.pow(x-c,2)+Math.pow(n-g,2)),z[2]/2)-z[3]/2,!0));return[p,x||0,n||0]},getPlotLinePath:function(d){var c=this,g=c.pane.center,p=c.chart,z=p.inverted,x=d.value,n=d.reverse,h=c.getPosition(x),b=c.pane.options.background?c.pane.options.background[0]||c.pane.options.background:
{},a=b.innerRadius||"0%",k=b.outerRadius||"100%";b=g[0]+p.plotLeft;var e=g[1]+p.plotTop,t=h.x,m=h.y,v=c.height;h=g[3]/2;var u,r;d.isCrosshair&&(m=this.getCrosshairPosition(d,b,e),x=m[0],t=m[1],m=m[2]);if(c.isCircular){n=Math.sqrt(Math.pow(t-b,2)+Math.pow(m-e,2));a="string"===typeof a?w(a,1):a/n;k="string"===typeof k?w(k,1):k/n;g&&h&&(g=h/n,a<g&&(a=g),k<g&&(k=g));var q=["M",b+a*(t-b),e-a*(e-m),"L",t-(1-k)*(t-b),m+(1-k)*(e-m)]}else(x=c.translate(x))&&(0>x||x>v)&&(x=0),"circle"===c.options.gridLineInterpolation?
q=c.getLinePath(0,x,h):(p[z?"yAxis":"xAxis"].forEach(function(g){g.pane===c.pane&&(u=g)}),q=[],g=u.tickPositions,u.autoConnect&&(g=g.concat([g[0]])),n&&(g=[].concat(g).reverse()),x&&(x+=h),g.forEach(function(g,c){r=u.getPosition(g,x);q.push(c?"L":"M",r.x,r.y)}));return q},getTitlePosition:function(){var d=this.center,c=this.chart,g=this.options.title;return{x:c.plotLeft+d[0]+(g.x||0),y:c.plotTop+d[1]-{high:.5,middle:.25,low:0}[g.align]*d[2]+(g.y||0)}},createLabelCollector:function(){var d=this;return function(){if(d.isRadial&&
d.tickPositions&&!0!==d.options.labels.allowOverlap)return d.tickPositions.map(function(c){return d.ticks[c]&&d.ticks[c].label}).filter(function(c){return!!c})}}};b(m,"init",function(d){var c=this.chart,g=c.inverted,p=c.angular,z=c.polar,h=this.isXAxis,n=this.coll,b=p&&h,a,k=c.options;d=d.userOptions.pane||0;d=this.pane=c.pane&&c.pane[d];if("colorAxis"===n)this.isRadial=!1;else{if(p){if(y(this,b?v:t),a=!h)this.defaultPolarOptions=this.defaultRadialGaugeOptions}else z&&(y(this,t),this.defaultPolarOptions=
(a=this.horiz)?this.defaultCircularOptions:B("xAxis"===n?m.defaultOptions:m.defaultYAxisOptions,this.defaultRadialOptions),g&&"yAxis"===n&&(this.defaultPolarOptions.stackLabels=m.defaultYAxisOptions.stackLabels));p||z?(this.isRadial=!0,k.chart.zoomType=null,this.labelCollector||(this.labelCollector=this.createLabelCollector()),this.labelCollector&&c.labelCollectors.push(this.labelCollector)):this.isRadial=!1;d&&a&&(d.axis=this);this.isCircular=a}});b(m,"afterInit",function(){var d=this.chart,c=this.options,
g=this.pane,p=g&&g.options;d.angular&&this.isXAxis||!g||!d.angular&&!d.polar||(this.angleRad=(c.angle||0)*Math.PI/180,this.startAngleRad=(p.startAngle-90)*Math.PI/180,this.endAngleRad=(h(p.endAngle,p.startAngle+360)-90)*Math.PI/180,this.offset=c.offset||0)});b(m,"autoLabelAlign",function(d){this.isRadial&&(d.align=void 0,d.preventDefault())});b(m,"destroy",function(){if(this.chart&&this.chart.labelCollectors){var d=this.chart.labelCollectors.indexOf(this.labelCollector);0<=d&&this.chart.labelCollectors.splice(d,
1)}});b(a,"afterGetPosition",function(d){this.axis.getPosition&&y(d.pos,this.axis.getPosition(this.pos))});b(a,"afterGetLabelPosition",function(d){var c=this.axis,g=this.label,p=g.getBBox(),z=c.options.labels,x=z.y,n=20,b=z.align,a=(c.translate(this.pos)+c.startAngleRad+Math.PI/2)/Math.PI*180%360,k=Math.round(a),e="end",m=0>k?k+360:k,t=m,v=0,u=0,r=null===z.y?.3*-p.height:0;if(c.isRadial){var q=c.getPosition(this.pos,c.center[2]/2+w(h(z.distance,-25),c.center[2]/2,-c.center[2]/2));"auto"===z.rotation?
g.attr({rotation:a}):null===x&&(x=c.chart.renderer.fontMetrics(g.styles&&g.styles.fontSize).b-p.height/2);null===b&&(c.isCircular?(p.width>c.len*c.tickInterval/(c.max-c.min)&&(n=0),b=a>n&&a<180-n?"left":a>180+n&&a<360-n?"right":"center"):b="center",g.attr({align:b}));if("auto"===b&&2===c.tickPositions.length&&c.isCircular){90<m&&180>m?m=180-m:270<m&&360>=m&&(m=540-m);180<t&&360>=t&&(t=360-t);if(c.pane.options.startAngle===k||c.pane.options.startAngle===k+360||c.pane.options.startAngle===k-360)e="start";
b=-90<=k&&90>=k||-360<=k&&-270>=k||270<=k&&360>=k?"start"===e?"right":"left":"start"===e?"left":"right";70<t&&110>t&&(b="center");15>m||180<=m&&195>m?v=.3*p.height:15<=m&&35>=m?v="start"===e?0:.75*p.height:195<=m&&215>=m?v="start"===e?.75*p.height:0:35<m&&90>=m?v="start"===e?.25*-p.height:p.height:215<m&&270>=m&&(v="start"===e?p.height:.25*-p.height);15>t?u="start"===e?.15*-p.height:.15*p.height:165<t&&180>=t&&(u="start"===e?.15*p.height:.15*-p.height);g.attr({align:b});g.translate(u,v+r)}d.pos.x=
q.x+z.x;d.pos.y=q.y+x}});e(A,"getMarkPath",function(d,c,g,p,z,h,n){var x=this.axis;x.isRadial?(d=x.getPosition(this.pos,x.center[2]/2+p),c=["M",c,g,"L",d.x,d.y]):c=d.call(this,c,g,p,z,h,n);return c})});E(f,"parts-more/AreaRangeSeries.js",[f["parts/Globals.js"],f["parts/Point.js"],f["parts/Utilities.js"]],function(l,a,e){var b=e.defined,r=e.extend,q=e.isArray,y=e.isNumber,f=e.pick;e=e.seriesType;var B=l.seriesTypes,h=l.Series.prototype,u=a.prototype;e("arearange","area",{lineWidth:1,threshold:null,
tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:null,verticalAlign:null,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low","high"],pointValKey:"low",deferTranslatePolar:!0,toYData:function(h){return[h.low,h.high]},highToXY:function(h){var b=this.chart,a=this.xAxis.postTranslate(h.rectPlotX,this.yAxis.len-h.plotHigh);h.plotHighX=a.x-b.plotLeft;h.plotHigh=a.y-b.plotTop;h.plotLowX=
h.plotX},translate:function(){var h=this,b=h.yAxis,a=!!h.modifyValue;B.area.prototype.translate.apply(h);h.points.forEach(function(k){var m=k.high,e=k.plotY;k.isNull?k.plotY=null:(k.plotLow=e,k.plotHigh=b.translate(a?h.modifyValue(m,k):m,0,1,0,1),a&&(k.yBottom=k.plotHigh))});this.chart.polar&&this.points.forEach(function(b){h.highToXY(b);b.tooltipPos=[(b.plotHighX+b.plotLowX)/2,(b.plotHigh+b.plotLow)/2]})},getGraphPath:function(h){var b=[],a=[],e,v=B.area.prototype.getGraphPath;var t=this.options;
var d=this.chart.polar&&!1!==t.connectEnds,c=t.connectNulls,g=t.step;h=h||this.points;for(e=h.length;e--;){var p=h[e];p.isNull||d||c||h[e+1]&&!h[e+1].isNull||a.push({plotX:p.plotX,plotY:p.plotY,doCurve:!1});var z={polarPlotY:p.polarPlotY,rectPlotX:p.rectPlotX,yBottom:p.yBottom,plotX:f(p.plotHighX,p.plotX),plotY:p.plotHigh,isNull:p.isNull};a.push(z);b.push(z);p.isNull||d||c||h[e-1]&&!h[e-1].isNull||a.push({plotX:p.plotX,plotY:p.plotY,doCurve:!1})}h=v.call(this,h);g&&(!0===g&&(g="left"),t.step={left:"right",
center:"center",right:"left"}[g]);b=v.call(this,b);a=v.call(this,a);t.step=g;t=[].concat(h,b);this.chart.polar||"M"!==a[0]||(a[0]="L");this.graphPath=t;this.areaPath=h.concat(a);t.isArea=!0;t.xMap=h.xMap;this.areaPath.xMap=h.xMap;return t},drawDataLabels:function(){var b=this.points,a=b.length,k,e=[],v=this.options.dataLabels,t,d=this.chart.inverted;if(q(v))if(1<v.length){var c=v[0];var g=v[1]}else c=v[0],g={enabled:!1};else c=r({},v),c.x=v.xHigh,c.y=v.yHigh,g=r({},v),g.x=v.xLow,g.y=v.yLow;if(c.enabled||
this._hasPointLabels){for(k=a;k--;)if(t=b[k]){var p=c.inside?t.plotHigh<t.plotLow:t.plotHigh>t.plotLow;t.y=t.high;t._plotY=t.plotY;t.plotY=t.plotHigh;e[k]=t.dataLabel;t.dataLabel=t.dataLabelUpper;t.below=p;d?c.align||(c.align=p?"right":"left"):c.verticalAlign||(c.verticalAlign=p?"top":"bottom")}this.options.dataLabels=c;h.drawDataLabels&&h.drawDataLabels.apply(this,arguments);for(k=a;k--;)if(t=b[k])t.dataLabelUpper=t.dataLabel,t.dataLabel=e[k],delete t.dataLabels,t.y=t.low,t.plotY=t._plotY}if(g.enabled||
this._hasPointLabels){for(k=a;k--;)if(t=b[k])p=g.inside?t.plotHigh<t.plotLow:t.plotHigh>t.plotLow,t.below=!p,d?g.align||(g.align=p?"left":"right"):g.verticalAlign||(g.verticalAlign=p?"bottom":"top");this.options.dataLabels=g;h.drawDataLabels&&h.drawDataLabels.apply(this,arguments)}if(c.enabled)for(k=a;k--;)if(t=b[k])t.dataLabels=[t.dataLabelUpper,t.dataLabel].filter(function(g){return!!g});this.options.dataLabels=v},alignDataLabel:function(){B.column.prototype.alignDataLabel.apply(this,arguments)},
drawPoints:function(){var a=this.points.length,e;h.drawPoints.apply(this,arguments);for(e=0;e<a;){var k=this.points[e];k.origProps={plotY:k.plotY,plotX:k.plotX,isInside:k.isInside,negative:k.negative,zone:k.zone,y:k.y};k.lowerGraphic=k.graphic;k.graphic=k.upperGraphic;k.plotY=k.plotHigh;b(k.plotHighX)&&(k.plotX=k.plotHighX);k.y=k.high;k.negative=k.high<(this.options.threshold||0);k.zone=this.zones.length&&k.getZone();this.chart.polar||(k.isInside=k.isTopInside="undefined"!==typeof k.plotY&&0<=k.plotY&&
k.plotY<=this.yAxis.len&&0<=k.plotX&&k.plotX<=this.xAxis.len);e++}h.drawPoints.apply(this,arguments);for(e=0;e<a;)k=this.points[e],k.upperGraphic=k.graphic,k.graphic=k.lowerGraphic,r(k,k.origProps),delete k.origProps,e++},setStackedPoints:l.noop},{setState:function(){var h=this.state,a=this.series,k=a.chart.polar;b(this.plotHigh)||(this.plotHigh=a.yAxis.toPixels(this.high,!0));b(this.plotLow)||(this.plotLow=this.plotY=a.yAxis.toPixels(this.low,!0));a.stateMarkerGraphic&&(a.lowerStateMarkerGraphic=
a.stateMarkerGraphic,a.stateMarkerGraphic=a.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;k&&(this.plotX=this.plotHighX);u.setState.apply(this,arguments);this.state=h;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;k&&(this.plotX=this.plotLowX);a.stateMarkerGraphic&&(a.upperStateMarkerGraphic=a.stateMarkerGraphic,a.stateMarkerGraphic=a.lowerStateMarkerGraphic,a.lowerStateMarkerGraphic=void 0);u.setState.apply(this,arguments)},haloPath:function(){var h=this.series.chart.polar,
b=[];this.plotY=this.plotLow;h&&(this.plotX=this.plotLowX);this.isInside&&(b=u.haloPath.apply(this,arguments));this.plotY=this.plotHigh;h&&(this.plotX=this.plotHighX);this.isTopInside&&(b=b.concat(u.haloPath.apply(this,arguments)));return b},destroyElements:function(){["lowerGraphic","upperGraphic"].forEach(function(h){this[h]&&(this[h]=this[h].destroy())},this);this.graphic=null;return u.destroyElements.apply(this,arguments)},isValid:function(){return y(this.low)&&y(this.high)}});""});E(f,"parts-more/AreaSplineRangeSeries.js",
[f["parts/Globals.js"],f["parts/Utilities.js"]],function(l,a){a=a.seriesType;a("areasplinerange","arearange",null,{getPointSpline:l.seriesTypes.spline.prototype.getPointSpline});""});E(f,"parts-more/ColumnRangeSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(l,a){var e=a.clamp,b=a.merge,r=a.pick;a=a.seriesType;var q=l.defaultPlotOptions,y=l.noop,f=l.seriesTypes.column.prototype;a("columnrange","arearange",b(q.column,q.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),
{translate:function(){var b=this,h=b.yAxis,a=b.xAxis,q=a.startAngleRad,m,k=b.chart,l=b.xAxis.isRadial,v=Math.max(k.chartWidth,k.chartHeight)+999,t;f.translate.apply(b);b.points.forEach(function(d){var c=d.shapeArgs,g=b.options.minPointLength;d.plotHigh=t=e(h.translate(d.high,0,1,0,1),-v,v);d.plotLow=e(d.plotY,-v,v);var p=t;var z=r(d.rectPlotY,d.plotY)-t;Math.abs(z)<g?(g-=z,z+=g,p-=g/2):0>z&&(z*=-1,p-=z);l?(m=d.barX+q,d.shapeType="arc",d.shapeArgs=b.polarArc(p+z,p,m,m+d.pointWidth)):(c.height=z,c.y=
p,d.tooltipPos=k.inverted?[h.len+h.pos-k.plotLeft-p-z/2,a.len+a.pos-k.plotTop-c.x-c.width/2,z]:[a.left-k.plotLeft+c.x+c.width/2,h.pos-k.plotTop+p+z/2,z])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:y,getSymbol:y,crispCol:function(){return f.crispCol.apply(this,arguments)},drawPoints:function(){return f.drawPoints.apply(this,arguments)},drawTracker:function(){return f.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return f.getColumnMetrics.apply(this,arguments)},
pointAttribs:function(){return f.pointAttribs.apply(this,arguments)},animate:function(){return f.animate.apply(this,arguments)},polarArc:function(){return f.polarArc.apply(this,arguments)},translate3dPoints:function(){return f.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return f.translate3dShapes.apply(this,arguments)}},{setState:f.pointClass.prototype.setState});""});E(f,"parts-more/ColumnPyramidSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(l,a){var e=
a.clamp,b=a.pick;a=a.seriesType;var r=l.seriesTypes.column.prototype;a("columnpyramid","column",{},{translate:function(){var a=this,l=a.chart,f=a.options,B=a.dense=2>a.closestPointRange*a.xAxis.transA;B=a.borderWidth=b(f.borderWidth,B?0:1);var h=a.yAxis,u=f.threshold,w=a.translatedThreshold=h.getThreshold(u),m=b(f.minPointLength,5),k=a.getColumnMetrics(),A=k.width,v=a.barW=Math.max(A,1+2*B),t=a.pointXOffset=k.offset;l.inverted&&(w-=.5);f.pointPadding&&(v=Math.ceil(v));r.translate.apply(a);a.points.forEach(function(d){var c=
b(d.yBottom,w),g=999+Math.abs(c),p=e(d.plotY,-g,h.len+g);g=d.plotX+t;var z=v/2,x=Math.min(p,c);c=Math.max(p,c)-x;var n;d.barX=g;d.pointWidth=A;d.tooltipPos=l.inverted?[h.len+h.pos-l.plotLeft-p,a.xAxis.len-g-z,c]:[g+z,p+h.pos-l.plotTop,c];p=u+(d.total||d.y);"percent"===f.stacking&&(p=u+(0>d.y)?-100:100);p=h.toPixels(p,!0);var k=(n=l.plotHeight-p-(l.plotHeight-w))?z*(x-p)/n:0;var F=n?z*(x+c-p)/n:0;n=g-k+z;k=g+k+z;var r=g+F+z;F=g-F+z;var q=x-m;var G=x+c;0>d.y&&(q=x,G=x+c+m);l.inverted&&(r=l.plotWidth-
x,n=p-(l.plotWidth-w),k=z*(p-r)/n,F=z*(p-(r-c))/n,n=g+z+k,k=n-2*k,r=g-F+z,F=g+F+z,q=x,G=x+c-m,0>d.y&&(G=x+c+m));d.shapeType="path";d.shapeArgs={x:n,y:q,width:k-n,height:c,d:["M",n,q,"L",k,q,r,G,F,G,"Z"]}})}});""});E(f,"parts-more/GaugeSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(l,a){var e=a.clamp,b=a.isNumber,r=a.merge,q=a.pick,f=a.pInt;a=a.seriesType;var C=l.Series,B=l.TrackerMixin;a("gauge","line",{dataLabels:{borderColor:"#cccccc",borderRadius:3,borderWidth:1,crop:!1,defer:!1,
enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1},{angular:!0,directTouch:!0,drawGraph:l.noop,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,trackerGroups:["group","dataLabelsGroup"],translate:function(){var h=this.yAxis,a=this.options,l=h.center;this.generatePoints();this.points.forEach(function(m){var k=r(a.dial,m.dial),u=f(q(k.radius,"80%"))*l[2]/200,v=f(q(k.baseLength,"70%"))*u/100,t=f(q(k.rearLength,"10%"))*u/100,d=k.baseWidth||3,c=k.topWidth||
1,g=a.overshoot,p=h.startAngleRad+h.translate(m.y,null,null,null,!0);if(b(g)||!1===a.wrap)g=b(g)?g/180*Math.PI:0,p=e(p,h.startAngleRad-g,h.endAngleRad+g);p=180*p/Math.PI;m.shapeType="path";m.shapeArgs={d:k.path||["M",-t,-d/2,"L",v,-d/2,u,-c/2,u,c/2,v,d/2,-t,d/2,"z"],translateX:l[0],translateY:l[1],rotation:p};m.plotX=l[0];m.plotY=l[1]})},drawPoints:function(){var h=this,a=h.chart,b=h.yAxis.center,e=h.pivot,k=h.options,l=k.pivot,v=a.renderer;h.points.forEach(function(b){var d=b.graphic,c=b.shapeArgs,
g=c.d,p=r(k.dial,b.dial);d?(d.animate(c),c.d=g):b.graphic=v[b.shapeType](c).attr({rotation:c.rotation,zIndex:1}).addClass("highcharts-dial").add(h.group);if(!a.styledMode)b.graphic[d?"animate":"attr"]({stroke:p.borderColor||"none","stroke-width":p.borderWidth||0,fill:p.backgroundColor||"#000000"})});e?e.animate({translateX:b[0],translateY:b[1]}):(h.pivot=v.circle(0,0,q(l.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(b[0],b[1]).add(h.group),a.styledMode||h.pivot.attr({"stroke-width":l.borderWidth||
0,stroke:l.borderColor||"#cccccc",fill:l.backgroundColor||"#000000"}))},animate:function(h){var b=this;h||b.points.forEach(function(h){var a=h.graphic;a&&(a.attr({rotation:180*b.yAxis.startAngleRad/Math.PI}),a.animate({rotation:h.shapeArgs.rotation},b.options.animation))})},render:function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);C.prototype.render.call(this);this.group.clip(this.chart.clipRect)},setData:function(h,b){C.prototype.setData.call(this,
h,!1);this.processData();this.generatePoints();q(b,!0)&&this.chart.redraw()},hasData:function(){return!!this.points.length},drawTracker:B&&B.drawTrackerPoint},{setState:function(h){this.state=h}});""});E(f,"parts-more/BoxPlotSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(l,a){var e=a.pick;a=a.seriesType;var b=l.noop,r=l.seriesTypes;a("boxplot","column",{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},
whiskerLength:"50%",fillColor:"#ffffff",lineWidth:1,medianWidth:2,whiskerWidth:2},{pointArrayMap:["low","q1","median","q3","high"],toYData:function(b){return[b.low,b.q1,b.median,b.q3,b.high]},pointValKey:"high",pointAttribs:function(){return{}},drawDataLabels:b,translate:function(){var b=this.yAxis,a=this.pointArrayMap;r.column.prototype.translate.apply(this);this.points.forEach(function(e){a.forEach(function(a){null!==e[a]&&(e[a+"Plot"]=b.translate(e[a],0,1,0,1))});e.plotHigh=e.highPlot})},drawPoints:function(){var b=
this,a=b.options,r=b.chart,l=r.renderer,h,u,f,m,k,A,v=0,t,d,c,g,p=!1!==b.doQuartiles,z,x=b.options.whiskerLength;b.points.forEach(function(n){var H=n.graphic,F=H?"animate":"attr",K=n.shapeArgs,q={},G={},I={},J={},w=n.color||b.color;"undefined"!==typeof n.plotY&&(t=K.width,d=Math.floor(K.x),c=d+t,g=Math.round(t/2),h=Math.floor(p?n.q1Plot:n.lowPlot),u=Math.floor(p?n.q3Plot:n.lowPlot),f=Math.floor(n.highPlot),m=Math.floor(n.lowPlot),H||(n.graphic=H=l.g("point").add(b.group),n.stem=l.path().addClass("highcharts-boxplot-stem").add(H),
x&&(n.whiskers=l.path().addClass("highcharts-boxplot-whisker").add(H)),p&&(n.box=l.path(void 0).addClass("highcharts-boxplot-box").add(H)),n.medianShape=l.path(void 0).addClass("highcharts-boxplot-median").add(H)),r.styledMode||(G.stroke=n.stemColor||a.stemColor||w,G["stroke-width"]=e(n.stemWidth,a.stemWidth,a.lineWidth),G.dashstyle=n.stemDashStyle||a.stemDashStyle,n.stem.attr(G),x&&(I.stroke=n.whiskerColor||a.whiskerColor||w,I["stroke-width"]=e(n.whiskerWidth,a.whiskerWidth,a.lineWidth),n.whiskers.attr(I)),
p&&(q.fill=n.fillColor||a.fillColor||w,q.stroke=a.lineColor||w,q["stroke-width"]=a.lineWidth||0,n.box.attr(q)),J.stroke=n.medianColor||a.medianColor||w,J["stroke-width"]=e(n.medianWidth,a.medianWidth,a.lineWidth),n.medianShape.attr(J)),A=n.stem.strokeWidth()%2/2,v=d+g+A,n.stem[F]({d:["M",v,u,"L",v,f,"M",v,h,"L",v,m]}),p&&(A=n.box.strokeWidth()%2/2,h=Math.floor(h)+A,u=Math.floor(u)+A,d+=A,c+=A,n.box[F]({d:["M",d,u,"L",d,h,"L",c,h,"L",c,u,"L",d,u,"z"]})),x&&(A=n.whiskers.strokeWidth()%2/2,f+=A,m+=A,
z=/%$/.test(x)?g*parseFloat(x)/100:x/2,n.whiskers[F]({d:["M",v-z,f,"L",v+z,f,"M",v-z,m,"L",v+z,m]})),k=Math.round(n.medianPlot),A=n.medianShape.strokeWidth()%2/2,k+=A,n.medianShape[F]({d:["M",d,k,"L",c,k]}))})},setStackedPoints:b});""});E(f,"parts-more/ErrorBarSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(l,a){a=a.seriesType;var e=l.noop,b=l.seriesTypes;a("errorbar","boxplot",{color:"#000000",grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},
whiskerWidth:null},{type:"errorbar",pointArrayMap:["low","high"],toYData:function(b){return[b.low,b.high]},pointValKey:"high",doQuartiles:!1,drawDataLabels:b.arearange?function(){var a=this.pointValKey;b.arearange.prototype.drawDataLabels.call(this);this.data.forEach(function(b){b.y=b[a]})}:e,getColumnMetrics:function(){return this.linkedParent&&this.linkedParent.columnMetrics||b.column.prototype.getColumnMetrics.call(this)}});""});E(f,"parts-more/WaterfallSeries.js",[f["parts/Globals.js"],f["parts/Point.js"],
f["parts/Utilities.js"],f["parts/Stacking.js"]],function(l,a,e,b){var r=e.addEvent,f=e.arrayMax,y=e.arrayMin,C=e.correctFloat,B=e.isNumber,h=e.objectEach,u=e.pick;e=e.seriesType;var w=l.Axis,m=l.Chart,k=l.Series,A=l.seriesTypes;r(w,"afterInit",function(){this.isXAxis||(this.waterfallStacks={changed:!1})});r(w,"afterBuildStacks",function(){this.waterfallStacks.changed=!1;delete this.waterfallStacks.alreadyChanged});r(m,"beforeRedraw",function(){for(var b=this.axes,a=this.series,d=a.length;d--;)a[d].options.stacking&&
(b.forEach(function(c){c.isXAxis||(c.waterfallStacks.changed=!0)}),d=0)});r(w,"afterRender",function(){var b=this.options.stackLabels;b&&b.enabled&&this.waterfallStacks&&this.renderWaterfallStackTotals()});w.prototype.renderWaterfallStackTotals=function(){var a=this.waterfallStacks,k=this.stackTotalGroup,d=new b(this,this.options.stackLabels,!1,0,void 0);this.dummyStackItem=d;h(a,function(c){h(c,function(g){d.total=g.stackTotal;g.label&&(d.label=g.label);b.prototype.render.call(d,k);g.label=d.label;
delete d.label})});d.total=null};e("waterfall","column",{dataLabels:{inside:!0},lineWidth:1,lineColor:"#333333",dashStyle:"Dot",borderColor:"#333333",states:{hover:{lineWidthPlus:0}}},{pointValKey:"y",showLine:!0,generatePoints:function(){var b;A.column.prototype.generatePoints.apply(this);var a=0;for(b=this.points.length;a<b;a++){var d=this.points[a];var c=this.processedYData[a];if(d.isIntermediateSum||d.isSum)d.y=C(c)}},translate:function(){var b=this.options,a=this.yAxis,d,c=u(b.minPointLength,
5),g=c/2,p=b.threshold,h=b.stacking,x=a.waterfallStacks[this.stackKey];A.column.prototype.translate.apply(this);var n=d=p;var k=this.points;var e=0;for(b=k.length;e<b;e++){var r=k[e];var l=this.processedYData[e];var m=r.shapeArgs;var f=[0,l];var q=r.y;if(h){if(x){f=x[e];if("overlap"===h){var w=f.stackState[f.stateIndex--];w=0<=q?w:w-q;Object.hasOwnProperty.call(f,"absolutePos")&&delete f.absolutePos;Object.hasOwnProperty.call(f,"absoluteNeg")&&delete f.absoluteNeg}else 0<=q?(w=f.threshold+f.posTotal,
f.posTotal-=q):(w=f.threshold+f.negTotal,f.negTotal-=q,w-=q),!f.posTotal&&Object.hasOwnProperty.call(f,"absolutePos")&&(f.posTotal=f.absolutePos,delete f.absolutePos),!f.negTotal&&Object.hasOwnProperty.call(f,"absoluteNeg")&&(f.negTotal=f.absoluteNeg,delete f.absoluteNeg);r.isSum||(f.connectorThreshold=f.threshold+f.stackTotal);a.reversed?(l=0<=q?w-q:w+q,q=w):(l=w,q=w-q);r.below=l<=u(p,0);m.y=a.translate(l,0,1,0,1);m.height=Math.abs(m.y-a.translate(q,0,1,0,1))}if(q=a.dummyStackItem)q.x=e,q.label=
x[e].label,q.setOffset(this.pointXOffset||0,this.barW||0,this.stackedYNeg[e],this.stackedYPos[e])}else w=Math.max(n,n+q)+f[0],m.y=a.translate(w,0,1,0,1),r.isSum?(m.y=a.translate(f[1],0,1,0,1),m.height=Math.min(a.translate(f[0],0,1,0,1),a.len)-m.y):r.isIntermediateSum?(0<=q?(l=f[1]+d,q=d):(l=d,q=f[1]+d),a.reversed&&(l^=q,q^=l,l^=q),m.y=a.translate(l,0,1,0,1),m.height=Math.abs(m.y-Math.min(a.translate(q,0,1,0,1),a.len)),d+=f[1]):(m.height=0<l?a.translate(n,0,1,0,1)-m.y:a.translate(n,0,1,0,1)-a.translate(n-
l,0,1,0,1),n+=l,r.below=n<u(p,0)),0>m.height&&(m.y+=m.height,m.height*=-1);r.plotY=m.y=Math.round(m.y)-this.borderWidth%2/2;m.height=Math.max(Math.round(m.height),.001);r.yBottom=m.y+m.height;m.height<=c&&!r.isNull?(m.height=c,m.y-=g,r.plotY=m.y,r.minPointLengthOffset=0>r.y?-g:g):(r.isNull&&(m.width=0),r.minPointLengthOffset=0);m=r.plotY+(r.negative?m.height:0);this.chart.inverted?r.tooltipPos[0]=a.len-m:r.tooltipPos[1]=m}},processData:function(a){var b=this.options,d=this.yData,c=b.data,g=d.length,
p=b.threshold||0,h,x,n,e,m;for(m=x=h=n=e=0;m<g;m++){var r=d[m];var f=c&&c[m]?c[m]:{};"sum"===r||f.isSum?d[m]=C(x):"intermediateSum"===r||f.isIntermediateSum?(d[m]=C(h),h=0):(x+=r,h+=r);n=Math.min(x,n);e=Math.max(x,e)}k.prototype.processData.call(this,a);b.stacking||(this.dataMin=n+p,this.dataMax=e)},toYData:function(a){return a.isSum?"sum":a.isIntermediateSum?"intermediateSum":a.y},updateParallelArrays:function(a,b){k.prototype.updateParallelArrays.call(this,a,b);if("sum"===this.yData[0]||"intermediateSum"===
this.yData[0])this.yData[0]=null},pointAttribs:function(a,b){var d=this.options.upColor;d&&!a.options.color&&(a.color=0<a.y?d:null);a=A.column.prototype.pointAttribs.call(this,a,b);delete a.dashstyle;return a},getGraphPath:function(){return["M",0,0]},getCrispPath:function(){var a=this.data,b=this.yAxis,d=a.length,c=Math.round(this.graph.strokeWidth())%2/2,g=Math.round(this.borderWidth)%2/2,p=this.xAxis.reversed,h=this.yAxis.reversed,x=this.options.stacking,n=[],e;for(e=1;e<d;e++){var k=a[e].shapeArgs;
var m=a[e-1];var r=a[e-1].shapeArgs;var f=b.waterfallStacks[this.stackKey];var l=0<m.y?-r.height:0;if(f){f=f[e-1];x?(f=f.connectorThreshold,l=Math.round(b.translate(f,0,1,0,1)+(h?l:0))-c):l=r.y+m.minPointLengthOffset+g-c;var u=["M",r.x+(p?0:r.width),l,"L",k.x+(p?k.width:0),l]}if(!x&&u&&0>m.y&&!h||0<m.y&&h)u[2]+=r.height,u[5]+=r.height;n=n.concat(u)}return n},drawGraph:function(){k.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})},setStackedPoints:function(){function a(g,c,d,
p){if(B)for(d;d<B;d++)q.stackState[d]+=p;else q.stackState[0]=g,B=q.stackState.length;q.stackState.push(q.stackState[B-1]+c)}var b=this.options,d=this.yAxis.waterfallStacks,c=b.threshold,g=c||0,p=g,h=this.stackKey,x=this.xData,n=x.length,e,k,m;this.yAxis.usePercentage=!1;var r=k=m=g;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){var f=d.changed;(e=d.alreadyChanged)&&0>e.indexOf(h)&&(f=!0);d[h]||(d[h]={});e=d[h];for(var l=0;l<n;l++){var u=x[l];if(!e[u]||f)e[u]={negTotal:0,posTotal:0,
stackTotal:0,threshold:0,stateIndex:0,stackState:[],label:f&&e[u]?e[u].label:void 0};var q=e[u];var w=this.yData[l];0<=w?q.posTotal+=w:q.negTotal+=w;var y=b.data[l];u=q.absolutePos=q.posTotal;var A=q.absoluteNeg=q.negTotal;q.stackTotal=u+A;var B=q.stackState.length;y&&y.isIntermediateSum?(a(m,k,0,m),m=k,k=c,g^=p,p^=g,g^=p):y&&y.isSum?(a(c,r,B),g=c):(a(g,w,0,r),y&&(r+=w,k+=w));q.stateIndex++;q.threshold=g;g+=q.stackTotal}d.changed=!1;d.alreadyChanged||(d.alreadyChanged=[]);d.alreadyChanged.push(h)}},
getExtremes:function(){var a=this.options.stacking;if(a){var b=this.yAxis;b=b.waterfallStacks;var d=this.stackedYNeg=[];var c=this.stackedYPos=[];"overlap"===a?h(b[this.stackKey],function(g){d.push(y(g.stackState));c.push(f(g.stackState))}):h(b[this.stackKey],function(g){d.push(g.negTotal+g.threshold);c.push(g.posTotal+g.threshold)});this.dataMin=y(d);this.dataMax=f(c)}}},{getClassName:function(){var b=a.prototype.getClassName.call(this);this.isSum?b+=" highcharts-sum":this.isIntermediateSum&&(b+=
" highcharts-intermediate-sum");return b},isValid:function(){return B(this.y)||this.isSum||this.isIntermediateSum}});""});E(f,"parts-more/PolygonSeries.js",[f["parts/Globals.js"],f["mixins/legend-symbol.js"],f["parts/Utilities.js"]],function(f,a,e){e=e.seriesType;var b=f.Series,r=f.seriesTypes;e("polygon","scatter",{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},trackByArea:!0},{type:"polygon",getGraphPath:function(){for(var a=b.prototype.getGraphPath.call(this),
e=a.length+1;e--;)(e===a.length||"M"===a[e])&&0<e&&a.splice(e,0,"z");return this.areaPath=a},drawGraph:function(){this.options.fillColor=this.color;r.area.prototype.drawGraph.call(this)},drawLegendSymbol:a.drawRectangle,drawTracker:b.prototype.drawTracker,setStackedPoints:f.noop});""});E(f,"parts-more/BubbleLegend.js",[f["parts/Globals.js"],f["parts/Color.js"],f["parts/Legend.js"],f["parts/Utilities.js"]],function(f,a,e,b){"";var r=a.parse;a=b.addEvent;var l=b.arrayMax,y=b.arrayMin,C=b.isNumber,B=
b.merge,h=b.objectEach,u=b.pick,w=b.stableSort,m=b.wrap,k=f.Series,A=f.Chart,v=f.noop,t=f.setOptions;t({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},
sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});t=function(){function d(c,g){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=v;this.init(c,g)}d.prototype.init=function(c,g){this.options=c;this.visible=!0;this.chart=g.chart;this.legend=g};d.prototype.addToLegend=function(c){c.splice(this.options.legendIndex,
0,this)};d.prototype.drawLegendSymbol=function(c){var g=this.chart,d=this.options,a=u(c.options.itemDistance,20),b=d.ranges;var h=d.connectorDistance;this.fontMetrics=g.renderer.fontMetrics(d.labels.style.fontSize.toString()+"px");b&&b.length&&C(b[0].value)?(w(b,function(g,c){return c.value-g.value}),this.ranges=b,this.setOptions(),this.render(),g=this.getMaxLabelSize(),b=this.ranges[0].radius,c=2*b,h=h-b+g.width,h=0<h?h:0,this.maxLabel=g,this.movementX="left"===d.labels.align?h:0,this.legendItemWidth=
c+h+a,this.legendItemHeight=c+this.fontMetrics.h/2):c.options.bubbleLegend.autoRanges=!0};d.prototype.setOptions=function(){var c=this.ranges,g=this.options,d=this.chart.series[g.seriesIndex],a=this.legend.baseline,b={"z-index":g.zIndex,"stroke-width":g.borderWidth},h={"z-index":g.zIndex,"stroke-width":g.connectorWidth},e=this.getLabelStyles(),k=d.options.marker.fillOpacity,m=this.chart.styledMode;c.forEach(function(p,n){m||(b.stroke=u(p.borderColor,g.borderColor,d.color),b.fill=u(p.color,g.color,
1!==k?r(d.color).setOpacity(k).get("rgba"):d.color),h.stroke=u(p.connectorColor,g.connectorColor,d.color));c[n].radius=this.getRangeRadius(p.value);c[n]=B(c[n],{center:c[0].radius-c[n].radius+a});m||B(!0,c[n],{bubbleStyle:B(!1,b),connectorStyle:B(!1,h),labelStyle:e})},this)};d.prototype.getLabelStyles=function(){var c=this.options,g={},d="left"===c.labels.align,a=this.legend.options.rtl;h(c.labels.style,function(c,d){"color"!==d&&"fontSize"!==d&&"z-index"!==d&&(g[d]=c)});return B(!1,g,{"font-size":c.labels.style.fontSize,
fill:u(c.labels.style.color,"#000000"),"z-index":c.zIndex,align:a||d?"right":"left"})};d.prototype.getRangeRadius=function(c){var g=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,g.ranges[g.ranges.length-1].value,g.ranges[0].value,g.minSize,g.maxSize,c)};d.prototype.render=function(){var c=this.chart.renderer,g=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=c.g("bubble-legend");this.legendItem=c.g("bubble-legend-item");
this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(c){c.value>=g&&this.renderRange(c)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};d.prototype.renderRange=function(c){var g=this.options,d=g.labels,a=this.chart.renderer,b=this.symbols,h=b.labels,e=c.center,k=Math.abs(c.radius),m=g.connectorDistance,f=d.align,r=d.style.fontSize;m=this.legend.options.rtl||"left"===f?-m:m;d=g.connectorWidth;var l=
this.ranges[0].radius,u=e-k-g.borderWidth/2+d/2;r=r/2-(this.fontMetrics.h-r)/2;var q=a.styledMode;"center"===f&&(m=0,g.connectorDistance=0,c.labelStyle.align="center");f=u+g.labels.y;var t=l+m+g.labels.x;b.bubbleItems.push(a.circle(l,e+((u%1?1:.5)-(d%2?0:.5)),k).attr(q?{}:c.bubbleStyle).addClass((q?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(g.className||"")).add(this.legendSymbol));b.connectors.push(a.path(a.crispLine(["M",l,u,"L",l+m,u],g.connectorWidth)).attr(q?
{}:c.connectorStyle).addClass((q?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(g.connectorClassName||"")).add(this.legendSymbol));c=a.text(this.formatLabel(c),t,f+r).attr(q?{}:c.labelStyle).addClass("highcharts-bubble-legend-labels "+(g.labels.className||"")).add(this.legendSymbol);h.push(c);c.placed=!0;c.alignAttr={x:t,y:f+r}};d.prototype.getMaxLabelSize=function(){var c,g;this.symbols.labels.forEach(function(d){g=d.getBBox(!0);c=c?g.width>c.width?g:
c:g});return c||{}};d.prototype.formatLabel=function(c){var g=this.options,d=g.labels.formatter;g=g.labels.format;var a=this.chart.numberFormatter;return g?b.format(g,c):d?d.call(c):a(c.value,1)};d.prototype.hideOverlappingLabels=function(){var d=this.chart,g=this.symbols;!this.options.labels.allowOverlap&&g&&(d.hideOverlappingLabels(g.labels),g.labels.forEach(function(d,c){d.newOpacity?d.newOpacity!==d.oldOpacity&&g.connectors[c].show():g.connectors[c].hide()}))};d.prototype.getRanges=function(){var d=
this.legend.bubbleLegend,g=d.options.ranges,a,b=Number.MAX_VALUE,h=-Number.MAX_VALUE;d.chart.series.forEach(function(g){g.isBubble&&!g.ignoreSeries&&(a=g.zData.filter(C),a.length&&(b=u(g.options.zMin,Math.min(b,Math.max(y(a),!1===g.options.displayNegative?g.options.zThreshold:-Number.MAX_VALUE))),h=u(g.options.zMax,Math.max(h,l(a)))))});var n=b===h?[{value:h}]:[{value:b},{value:(b+h)/2},{value:h,autoRanges:!0}];g.length&&g[0].radius&&n.reverse();n.forEach(function(d,c){g&&g[c]&&(n[c]=B(!1,g[c],d))});
return n};d.prototype.predictBubbleSizes=function(){var d=this.chart,g=this.fontMetrics,a=d.legend.options,b="horizontal"===a.layout,h=b?d.legend.lastLineHeight:0,n=d.plotSizeX,e=d.plotSizeY,k=d.series[this.options.seriesIndex];d=Math.ceil(k.minPxSize);var m=Math.ceil(k.maxPxSize);k=k.options.maxSize;var f=Math.min(e,n);if(a.floating||!/%$/.test(k))g=m;else if(k=parseFloat(k),g=(f+h-g.h/2)*k/100/(k/100+1),b&&e-g>=n||!b&&n-g>=e)g=m;return[d,Math.ceil(g)]};d.prototype.updateRanges=function(d,g){var c=
this.legend.options.bubbleLegend;c.minSize=d;c.maxSize=g;c.ranges=this.getRanges()};d.prototype.correctSizes=function(){var d=this.legend,g=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(g.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,g.maxPxSize),d.render())};return d}();a(e,"afterGetAllItems",function(d){var c=this.bubbleLegend,g=this.options,a=g.bubbleLegend,b=this.chart.getVisibleBubbleSeriesIndex();c&&c.ranges&&c.ranges.length&&(a.ranges.length&&
(a.autoRanges=!!a.ranges[0].autoRanges),this.destroyItem(c));0<=b&&g.enabled&&a.enabled&&(a.seriesIndex=b,this.bubbleLegend=new f.BubbleLegend(a,this),this.bubbleLegend.addToLegend(d.allItems))});A.prototype.getVisibleBubbleSeriesIndex=function(){for(var d=this.series,c=0;c<d.length;){if(d[c]&&d[c].isBubble&&d[c].visible&&d[c].zData.length)return c;c++}return-1};e.prototype.getLinesHeights=function(){var d=this.allItems,c=[],g=d.length,a,b=0;for(a=0;a<g;a++)if(d[a].legendItemHeight&&(d[a].itemHeight=
d[a].legendItemHeight),d[a]===d[g-1]||d[a+1]&&d[a]._legendItemPos[1]!==d[a+1]._legendItemPos[1]){c.push({height:0});var h=c[c.length-1];for(b;b<=a;b++)d[b].itemHeight>h.height&&(h.height=d[b].itemHeight);h.step=a}return c};e.prototype.retranslateItems=function(d){var a,g,b,h=this.options.rtl,e=0;this.allItems.forEach(function(c,p){a=c.legendGroup.translateX;g=c._legendItemPos[1];if((b=c.movementX)||h&&c.ranges)b=h?a-c.options.maxSize/2:a+b,c.legendGroup.attr({translateX:b});p>d[e].step&&e++;c.legendGroup.attr({translateY:Math.round(g+
d[e].height/2)});c._legendItemPos[1]=g+d[e].height/2})};a(k,"legendItemClick",function(){var d=this.chart,a=this.visible,g=this.chart.legend;g&&g.bubbleLegend&&(this.visible=!a,this.ignoreSeries=a,d=0<=d.getVisibleBubbleSeriesIndex(),g.bubbleLegend.visible!==d&&(g.update({bubbleLegend:{enabled:d}}),g.bubbleLegend.visible=d),this.visible=a)});m(A.prototype,"drawChartBox",function(d,a,g){var c=this.legend,b=0<=this.getVisibleBubbleSeriesIndex();if(c&&c.options.enabled&&c.bubbleLegend&&c.options.bubbleLegend.autoRanges&&
b){var e=c.bubbleLegend.options;b=c.bubbleLegend.predictBubbleSizes();c.bubbleLegend.updateRanges(b[0],b[1]);e.placed||(c.group.placed=!1,c.allItems.forEach(function(g){g.legendGroup.translateY=null}));c.render();this.getMargins();this.axes.forEach(function(g){g.visible&&g.render();e.placed||(g.setScale(),g.updateNames(),h(g.ticks,function(g){g.isNew=!0;g.isNewLabel=!0}))});e.placed=!0;this.getMargins();d.call(this,a,g);c.bubbleLegend.correctSizes();c.retranslateItems(c.getLinesHeights())}else d.call(this,
a,g),c&&c.options.enabled&&c.bubbleLegend&&(c.render(),c.retranslateItems(c.getLinesHeights()))});f.BubbleLegend=t;return f.BubbleLegend});E(f,"parts-more/BubbleSeries.js",[f["parts/Globals.js"],f["parts/Color.js"],f["parts/Point.js"],f["parts/Utilities.js"]],function(f,a,e,b){var r=a.parse,l=b.arrayMax,y=b.arrayMin,C=b.clamp,B=b.extend,h=b.isNumber,u=b.pick,w=b.pInt;a=b.seriesType;b=f.Axis;var m=f.noop,k=f.Series,A=f.seriesTypes;a("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},
inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,
isBubble:!0,pointAttribs:function(a,b){var d=this.options.marker.fillOpacity;a=k.prototype.pointAttribs.call(this,a,b);1!==d&&(a.fill=r(a.fill).setOpacity(d).get("rgba"));return a},getRadii:function(a,b,d){var c=this.zData,g=this.yData,h=d.minPxSize,e=d.maxPxSize,k=[];var n=0;for(d=c.length;n<d;n++){var m=c[n];k.push(this.getRadius(a,b,h,e,m,g[n]))}this.radii=k},getRadius:function(a,b,d,c,g,p){var e=this.options,k="width"!==e.sizeBy,n=e.zThreshold,m=b-a,f=.5;if(null===p||null===g)return null;if(h(g)){e.sizeByAbsoluteValue&&
(g=Math.abs(g-n),m=Math.max(b-n,Math.abs(a-n)),a=0);if(g<a)return d/2-1;0<m&&(f=(g-a)/m)}k&&0<=f&&(f=Math.sqrt(f));return Math.ceil(d+f*(c-d))/2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&this.points.forEach(function(a){var d=a.graphic;if(d&&d.width){var c={x:d.x,y:d.y,width:d.width,height:d.height};d.attr({x:a.plotX,y:a.plotY,width:1,height:1});d.animate(c,this.options.animation)}},this)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,
b=this.data,d=this.radii;A.scatter.prototype.translate.call(this);for(a=b.length;a--;){var c=b[a];var g=d?d[a]:0;h(g)&&g>=this.minPxSize/2?(c.marker=B(c.marker,{radius:g,width:2*g,height:2*g}),c.dlBox={x:c.plotX-g,y:c.plotY-g,width:2*g,height:2*g}):c.shapeArgs=c.plotY=c.dlBox=void 0}},alignDataLabel:A.column.prototype.alignDataLabel,buildKDTree:m,applyZones:m},{haloPath:function(a){return e.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});b.prototype.beforePadding=
function(){var a=this,b=this.len,d=this.chart,c=0,g=b,p=this.isXAxis,e=p?"xData":"yData",k=this.min,n={},m=Math.min(d.plotWidth,d.plotHeight),f=Number.MAX_VALUE,r=-Number.MAX_VALUE,q=this.max-k,A=b/q,B=[];this.series.forEach(function(g){var c=g.options;!g.bubblePadding||!g.visible&&d.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,B.push(g),p&&(["minSize","maxSize"].forEach(function(g){var a=c[g],d=/%$/.test(a);a=w(a);n[g]=d?m*a/100:a}),g.minPxSize=n.minSize,g.maxPxSize=Math.max(n.maxSize,
n.minSize),g=g.zData.filter(h),g.length&&(f=u(c.zMin,C(y(g),!1===c.displayNegative?c.zThreshold:-Number.MAX_VALUE,f)),r=u(c.zMax,Math.max(r,l(g))))))});B.forEach(function(d){var b=d[e],n=b.length;p&&d.getRadii(f,r,d);if(0<q)for(;n--;)if(h(b[n])&&a.dataMin<=b[n]&&b[n]<=a.max){var x=d.radii?d.radii[n]:0;c=Math.min((b[n]-k)*A-x,c);g=Math.max((b[n]-k)*A+x,g)}});B.length&&0<q&&!this.isLog&&(g-=b,A*=(b+Math.max(0,c)-Math.min(g,b))/b,[["min","userMin",c],["max","userMax",g]].forEach(function(g){"undefined"===
typeof u(a.options[g[0]],a[g[1]])&&(a[g[0]]+=g[2]/A)}))};""});E(f,"modules/networkgraph/integrations.js",[f["parts/Globals.js"]],function(f){f.networkgraphIntegrations={verlet:{attractiveForceFunction:function(a,e){return(e-a)/a},repulsiveForceFunction:function(a,e){return(e-a)/a*(e>a?1:0)},barycenter:function(){var a=this.options.gravitationalConstant,e=this.barycenter.xFactor,b=this.barycenter.yFactor;e=(e-(this.box.left+this.box.width)/2)*a;b=(b-(this.box.top+this.box.height)/2)*a;this.nodes.forEach(function(a){a.fixedPosition||
(a.plotX-=e/a.mass/a.degree,a.plotY-=b/a.mass/a.degree)})},repulsive:function(a,e,b){e=e*this.diffTemperature/a.mass/a.degree;a.fixedPosition||(a.plotX+=b.x*e,a.plotY+=b.y*e)},attractive:function(a,e,b){var f=a.getMass(),l=-b.x*e*this.diffTemperature;e=-b.y*e*this.diffTemperature;a.fromNode.fixedPosition||(a.fromNode.plotX-=l*f.fromNode/a.fromNode.degree,a.fromNode.plotY-=e*f.fromNode/a.fromNode.degree);a.toNode.fixedPosition||(a.toNode.plotX+=l*f.toNode/a.toNode.degree,a.toNode.plotY+=e*f.toNode/
a.toNode.degree)},integrate:function(a,e){var b=-a.options.friction,f=a.options.maxSpeed,l=(e.plotX+e.dispX-e.prevX)*b;b*=e.plotY+e.dispY-e.prevY;var y=Math.abs,C=y(l)/(l||1);y=y(b)/(b||1);l=C*Math.min(f,Math.abs(l));b=y*Math.min(f,Math.abs(b));e.prevX=e.plotX+e.dispX;e.prevY=e.plotY+e.dispY;e.plotX+=l;e.plotY+=b;e.temperature=a.vectorLength({x:l,y:b})},getK:function(a){return Math.pow(a.box.width*a.box.height/a.nodes.length,.5)}},euler:{attractiveForceFunction:function(a,e){return a*a/e},repulsiveForceFunction:function(a,
e){return e*e/a},barycenter:function(){var a=this.options.gravitationalConstant,e=this.barycenter.xFactor,b=this.barycenter.yFactor;this.nodes.forEach(function(f){if(!f.fixedPosition){var l=f.getDegree();l*=1+l/2;f.dispX+=(e-f.plotX)*a*l/f.degree;f.dispY+=(b-f.plotY)*a*l/f.degree}})},repulsive:function(a,e,b,f){a.dispX+=b.x/f*e/a.degree;a.dispY+=b.y/f*e/a.degree},attractive:function(a,e,b,f){var l=a.getMass(),r=b.x/f*e;e*=b.y/f;a.fromNode.fixedPosition||(a.fromNode.dispX-=r*l.fromNode/a.fromNode.degree,
a.fromNode.dispY-=e*l.fromNode/a.fromNode.degree);a.toNode.fixedPosition||(a.toNode.dispX+=r*l.toNode/a.toNode.degree,a.toNode.dispY+=e*l.toNode/a.toNode.degree)},integrate:function(a,e){e.dispX+=e.dispX*a.options.friction;e.dispY+=e.dispY*a.options.friction;var b=e.temperature=a.vectorLength({x:e.dispX,y:e.dispY});0!==b&&(e.plotX+=e.dispX/b*Math.min(Math.abs(e.dispX),a.temperature),e.plotY+=e.dispY/b*Math.min(Math.abs(e.dispY),a.temperature))},getK:function(a){return Math.pow(a.box.width*a.box.height/
a.nodes.length,.3)}}}});E(f,"modules/networkgraph/QuadTree.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(f,a){a=a.extend;var e=f.QuadTreeNode=function(a){this.box=a;this.boxSize=Math.min(a.width,a.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};a(e.prototype,{insert:function(a,f){this.isInternal?this.nodes[this.getBoxPosition(a)].insert(a,f-1):(this.isEmpty=!1,this.body?f?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,
f-1),this.body=!0),this.nodes[this.getBoxPosition(a)].insert(a,f-1)):(f=new e({top:a.plotX,left:a.plotY,width:.1,height:.1}),f.body=a,f.isInternal=!1,this.nodes.push(f)):(this.isInternal=!1,this.body=a))},updateMassAndCenter:function(){var a=0,e=0,f=0;this.isInternal?(this.nodes.forEach(function(b){b.isEmpty||(a+=b.mass,e+=b.plotX*b.mass,f+=b.plotY*b.mass)}),e/=a,f/=a):this.body&&(a=this.body.mass,e=this.body.plotX,f=this.body.plotY);this.mass=a;this.plotX=e;this.plotY=f},divideBox:function(){var a=
this.box.width/2,f=this.box.height/2;this.nodes[0]=new e({left:this.box.left,top:this.box.top,width:a,height:f});this.nodes[1]=new e({left:this.box.left+a,top:this.box.top,width:a,height:f});this.nodes[2]=new e({left:this.box.left+a,top:this.box.top+f,width:a,height:f});this.nodes[3]=new e({left:this.box.left,top:this.box.top+f,width:a,height:f})},getBoxPosition:function(a){var b=a.plotY<this.box.top+this.box.height/2;return a.plotX<this.box.left+this.box.width/2?b?0:3:b?1:2}});f=f.QuadTree=function(a,
f,l,y){this.box={left:a,top:f,width:l,height:y};this.maxDepth=25;this.root=new e(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};a(f.prototype,{insertNodes:function(a){a.forEach(function(a){this.root.insert(a,this.maxDepth)},this)},visitNodeRecursive:function(a,e,f){var b;a||(a=this.root);a===this.root&&e&&(b=e(a));!1!==b&&(a.nodes.forEach(function(a){if(a.isInternal){e&&(b=e(a));if(!1===b)return;this.visitNodeRecursive(a,e,f)}else a.body&&e&&e(a.body);f&&f(a)},this),
a===this.root&&f&&f(a))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(a){a.updateMassAndCenter()})}})});E(f,"modules/networkgraph/layouts.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(f,a){var e=a.addEvent,b=a.clamp,l=a.defined,q=a.extend,y=a.isFunction,C=a.pick,B=a.setAnimation;a=f.Chart;f.layouts={"reingold-fruchterman":function(){}};q(f.layouts["reingold-fruchterman"].prototype,{init:function(a){this.options=a;this.nodes=[];this.links=[];this.series=
[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=f.networkgraphIntegrations[a.integration];this.attractiveForce=C(a.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=C(a.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=a.approximation},start:function(){var a=this.series,b=this.options;this.currentStep=0;this.forces=a[0]&&a[0].forces||[];this.initialRendering&&(this.initPositions(),a.forEach(function(a){a.render()}));
this.setK();this.resetSimulation(b);b.enableSimulation&&this.step()},step:function(){var a=this,b=this.series,e=this.options;a.currentStep++;"barnes-hut"===a.approximation&&(a.createQuadTree(),a.quadTree.calculateMassAndCenter());a.forces.forEach(function(b){a[b+"Forces"](a.temperature)});a.applyLimits(a.temperature);a.temperature=a.coolDown(a.startTemperature,a.diffTemperature,a.currentStep);a.prevSystemTemperature=a.systemTemperature;a.systemTemperature=a.getSystemTemperature();e.enableSimulation&&
(b.forEach(function(a){a.chart&&a.render()}),a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()?(a.simulation&&f.win.cancelAnimationFrame(a.simulation),a.simulation=f.win.requestAnimationFrame(function(){a.step()})):a.simulation=!1)},stop:function(){this.simulation&&f.win.cancelAnimationFrame(this.simulation)},setArea:function(a,b,e,f){this.box={left:a,top:b,width:e,height:f}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addElementsToCollection:function(a,b){a.forEach(function(a){-1===
b.indexOf(a)&&b.push(a)})},removeElementFromCollection:function(a,b){a=b.indexOf(a);-1!==a&&b.splice(a,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},setMaxIterations:function(a){this.maxIterations=C(a,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=Math.sqrt(this.nodes.length)},
setDiffTemperature:function(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(a){this.initialRendering=a},createQuadTree:function(){this.quadTree=new f.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var a=this.options.initialPositions;y(a)?(a.call(this),this.nodes.forEach(function(a){l(a.prevX)||(a.prevX=a.plotX);l(a.prevY)||(a.prevY=a.plotY);a.dispX=0;a.dispY=
0})):"circle"===a?this.setCircularPositions():this.setRandomPositions()},setCircularPositions:function(){function a(d){d.linksFrom.forEach(function(d){r[d.toNode.id]||(r[d.toNode.id]=!0,l.push(d.toNode),a(d.toNode))})}var b=this.box,e=this.nodes,f=2*Math.PI/(e.length+1),k=e.filter(function(a){return 0===a.linksTo.length}),l=[],r={},q=this.options.initialPositionRadius;k.forEach(function(d){l.push(d);a(d)});l.length?e.forEach(function(a){-1===l.indexOf(a)&&l.push(a)}):l=e;l.forEach(function(a,c){a.plotX=
a.prevX=C(a.plotX,b.width/2+q*Math.cos(c*f));a.plotY=a.prevY=C(a.plotY,b.height/2+q*Math.sin(c*f));a.dispX=0;a.dispY=0})},setRandomPositions:function(){function a(a){a=a*a/Math.PI;return a-=Math.floor(a)}var b=this.box,e=this.nodes,f=e.length+1;e.forEach(function(h,e){h.plotX=h.prevX=C(h.plotX,b.width*a(e));h.plotY=h.prevY=C(h.plotY,b.height*a(f+e));h.dispX=0;h.dispY=0})},force:function(a){this.integration[a].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();
this.force("barycenter")},getBarycenter:function(){var a=0,b=0,e=0;this.nodes.forEach(function(h){b+=h.plotX*h.mass;e+=h.plotY*h.mass;a+=h.mass});return this.barycenter={x:b,y:e,xFactor:b/a,yFactor:e/a}},barnesHutApproximation:function(a,b){var h=this.getDistXY(a,b),e=this.vectorLength(h);if(a!==b&&0!==e)if(b.isInternal)if(b.boxSize/e<this.options.theta&&0!==e){var f=this.repulsiveForce(e,this.k);this.force("repulsive",a,f*b.mass,h,e);var l=!1}else l=!0;else f=this.repulsiveForce(e,this.k),this.force("repulsive",
a,f*b.mass,h,e);return l},repulsiveForces:function(){var a=this;"barnes-hut"===a.approximation?a.nodes.forEach(function(b){a.quadTree.visitNodeRecursive(null,function(e){return a.barnesHutApproximation(b,e)})}):a.nodes.forEach(function(b){a.nodes.forEach(function(e){if(b!==e&&!b.fixedPosition){var h=a.getDistXY(b,e);var f=a.vectorLength(h);if(0!==f){var l=a.repulsiveForce(f,a.k);a.force("repulsive",b,l*e.mass,h,f)}}})})},attractiveForces:function(){var a=this,b,e,f;a.links.forEach(function(h){h.fromNode&&
h.toNode&&(b=a.getDistXY(h.fromNode,h.toNode),e=a.vectorLength(b),0!==e&&(f=a.attractiveForce(e,a.k),a.force("attractive",h,f,b,e)))})},applyLimits:function(){var a=this;a.nodes.forEach(function(b){b.fixedPosition||(a.integration.integrate(a,b),a.applyLimitBox(b,a.box),b.dispX=0,b.dispY=0)})},applyLimitBox:function(a,e){var h=a.radius;a.plotX=b(a.plotX,e.left+h,e.width-h);a.plotY=b(a.plotY,e.top+h,e.height-h)},coolDown:function(a,b,e){return a-b*e},isStable:function(){return.00001>Math.abs(this.systemTemperature-
this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(a,b){return a+b.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+a.y*a.y)},getDistR:function(a,b){a=this.getDistXY(a,b);return this.vectorLength(a)},getDistXY:function(a,b){var e=a.plotX-b.plotX;a=a.plotY-b.plotY;return{x:e,y:a,absX:Math.abs(e),absY:Math.abs(a)}}});e(a,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});
e(a,"render",function(){function a(a){a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()&&!a.options.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),e=!1,b=!0)}var b=!1;if(this.graphLayoutsLookup){B(!1,this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!e;){var e=!0;this.graphLayoutsLookup.forEach(a)}b&&this.series.forEach(function(a){a&&a.layout&&a.render()})}})});E(f,"modules/networkgraph/draggable-nodes.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(f,
a){var e=a.addEvent;a=f.Chart;f.dragNodesMixin={onMouseDown:function(a,e){e=this.chart.pointer.normalize(e);a.fixedPosition={chartX:e.chartX,chartY:e.chartY,plotX:a.plotX,plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,e){if(a.fixedPosition&&a.inDragMode){var b=this.chart,f=b.pointer.normalize(e);e=a.fixedPosition.chartX-f.chartX;f=a.fixedPosition.chartY-f.chartY;if(5<Math.abs(e)||5<Math.abs(f))e=a.fixedPosition.plotX-e,f=a.fixedPosition.plotY-f,b.isInsidePlot(e,f)&&(a.plotX=e,a.plotY=f,a.hasDragged=
!0,this.redrawHalo(a),this.layout.simulation?this.layout.resetSimulation():(this.layout.setInitialRendering(!1),this.layout.enableSimulation?this.layout.start():this.layout.setMaxIterations(1),this.chart.redraw(),this.layout.setInitialRendering(!0)))}},onMouseUp:function(a,e){a.fixedPosition&&a.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw(),a.inDragMode=a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}};
e(a,"load",function(){var a=this,f,l,y;a.container&&(f=e(a.container,"mousedown",function(b){var f=a.hoverPoint;f&&f.series&&f.series.hasDraggableNodes&&f.series.options.draggable&&(f.series.onMouseDown(f,b),l=e(a.container,"mousemove",function(a){return f&&f.series&&f.series.onMouseMove(f,a)}),y=e(a.container.ownerDocument,"mouseup",function(a){l();y();return f&&f.series&&f.series.onMouseUp(f,a)}))}));e(a,"destroy",function(){f()})})});E(f,"parts-more/PackedBubbleSeries.js",[f["parts/Globals.js"],
f["parts/Color.js"],f["parts/Point.js"],f["parts/Utilities.js"]],function(f,a,e,b){var l=a.parse,q=b.addEvent,y=b.clamp,C=b.defined,B=b.extend;a=b.extendClass;var h=b.fireEvent,u=b.isArray,w=b.isNumber,m=b.merge,k=b.pick;b=b.seriesType;var A=f.Series,v=f.Chart,t=f.layouts["reingold-fruchterman"],d=f.seriesTypes.bubble.prototype.pointClass,c=f.dragNodesMixin;f.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(a,d,b,c){return Math.min(a,(b.marker.radius+c.marker.radius)/2)},barycenter:function(){var a=
this,d=a.options.gravitationalConstant,b=a.box,c=a.nodes,e,f;c.forEach(function(g){a.options.splitSeries&&!g.isParentNode?(e=g.series.parentNode.plotX,f=g.series.parentNode.plotY):(e=b.width/2,f=b.height/2);g.fixedPosition||(g.plotX-=(g.plotX-e)*d/(g.mass*Math.sqrt(c.length)),g.plotY-=(g.plotY-f)*d/(g.mass*Math.sqrt(c.length)))})},repulsive:function(a,d,b,c){var g=d*this.diffTemperature/a.mass/a.degree;d=b.x*g;b=b.y*g;a.fixedPosition||(a.plotX+=d,a.plotY+=b);c.fixedPosition||(c.plotX-=d,c.plotY-=
b)},integrate:f.networkgraphIntegrations.verlet.integrate,getK:f.noop};f.layouts.packedbubble=a(t,{beforeStep:function(){this.options.marker&&this.series.forEach(function(a){a&&a.calculateParentRadius()})},setCircularPositions:function(){var a=this,d=a.box,b=a.nodes,c=2*Math.PI/(b.length+1),e,f,h=a.options.initialPositionRadius;b.forEach(function(g,b){a.options.splitSeries&&!g.isParentNode?(e=g.series.parentNode.plotX,f=g.series.parentNode.plotY):(e=d.width/2,f=d.height/2);g.plotX=g.prevX=k(g.plotX,
e+h*Math.cos(g.index||b*c));g.plotY=g.prevY=k(g.plotY,f+h*Math.sin(g.index||b*c));g.dispX=0;g.dispY=0})},repulsiveForces:function(){var a=this,d,b,c,e=a.options.bubblePadding;a.nodes.forEach(function(g){g.degree=g.mass;g.neighbours=0;a.nodes.forEach(function(f){d=0;g===f||g.fixedPosition||!a.options.seriesInteraction&&g.series!==f.series||(c=a.getDistXY(g,f),b=a.vectorLength(c)-(g.marker.radius+f.marker.radius+e),0>b&&(g.degree+=.01,g.neighbours++,d=a.repulsiveForce(-b/Math.sqrt(g.neighbours),a.k,
g,f)),a.force("repulsive",g,d*f.mass,c,f,b))})})},applyLimitBox:function(a){if(this.options.splitSeries&&!a.isParentNode&&this.options.parentNodeLimit){var g=this.getDistXY(a,a.series.parentNode);var b=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(g);0>b&&b>-2*a.marker.radius&&(a.plotX-=.01*g.x,a.plotY-=.01*g.y)}t.prototype.applyLimitBox.apply(this,arguments)},isStable:function(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature||0<this.systemTemperature&&
.02>this.systemTemperature/this.nodes.length&&this.enableSimulation}});b("packedbubble","bubble",{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",tooltip:{pointFormat:"Value: {point.value}"},draggable:!0,useSimulation:!0,dataLabels:{formatter:function(){return this.point.value},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},padding:0},layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,
dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,fillOpacity:1,lineWidth:1,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}},{hasDraggableNodes:!0,forces:["barycenter","repulsive"],pointArrayMap:["value"],pointValKey:"value",isCartesian:!1,requireSorting:!1,
directTouch:!0,axisTypes:[],noSharedTooltip:!0,searchPoint:f.noop,accumulateAllPoints:function(a){var g=a.chart,b=[],d,c;for(d=0;d<g.series.length;d++)if(a=g.series[d],a.visible||!g.options.chart.ignoreHiddenSeries)for(c=0;c<a.yData.length;c++)b.push([null,null,a.yData[c],a.index,c,{id:c,marker:{radius:0}}]);return b},init:function(){A.prototype.init.apply(this,arguments);q(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===this.type&&(a.isDirty=!0)},this)});return this},
render:function(){var a=[];A.prototype.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(function(g){u(g.dataLabels)&&g.dataLabels.forEach(function(g){a.push(g)})}),this.options.useSimulation&&this.chart.hideOverlappingLabels(a))},setVisible:function(){var a=this;A.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeElementFromCollection(a.parentNode,
a.parentNodeLayout.nodes),a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(function(g){a.layout.removeElementFromCollection(g,a.layout.nodes)}))},drawDataLabels:function(){var a=this.options.dataLabels.textPath,b=this.points;A.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix="parentNode",this.points=[this.parentNode],this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,
A.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)},seriesBox:function(){var a=this.chart,b=Math.max,d=Math.min,c,e=[a.plotLeft,a.plotLeft+a.plotWidth,a.plotTop,a.plotTop+a.plotHeight];this.data.forEach(function(a){C(a.plotX)&&C(a.plotY)&&a.marker.radius&&(c=a.marker.radius,e[0]=d(e[0],a.plotX-c),e[1]=b(e[1],a.plotX+c),e[2]=d(e[2],a.plotY-c),e[3]=b(e[3],a.plotY+c))});return w(e.width/e.height)?e:null},calculateParentRadius:function(){var a=this.seriesBox();
this.parentNodeRadius=y(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)},drawGraph:function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart,b=this.layout.options.parentNodeOptions.marker;b={fill:b.fillColor||l(this.color).brighten(.4).get(),opacity:b.fillOpacity,stroke:b.lineColor||
this.color,"stroke-width":b.lineWidth};var d=this.visible?"inherit":"hidden";this.parentNodesGroup||(this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",d,.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();d=m({x:this.parentNode.plotX-this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},b);this.parentNode.graphic||(this.graph=this.parentNode.graphic=a.renderer.symbol(b.symbol).add(this.parentNodesGroup));
this.parentNode.graphic.attr(d)}},createParentNodes:function(){var a=this,b=a.chart,c=a.parentNodeLayout,e,f=a.parentNode;a.parentNodeMass=0;a.points.forEach(function(g){a.parentNodeMass+=Math.PI*Math.pow(g.marker.radius,2)});a.calculateParentRadius();c.nodes.forEach(function(g){g.seriesIndex===a.index&&(e=!0)});c.setArea(0,0,b.plotWidth,b.plotHeight);e||(f||(f=(new d).init(this,{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},dataLabelOnNull:!0,degree:a.parentNodeRadius,
isParentNode:!0,seriesIndex:a.index})),a.parentNode&&(f.plotX=a.parentNode.plotX,f.plotY=a.parentNode.plotY),a.parentNode=f,c.addElementsToCollection([a],c.series),c.addElementsToCollection([f],c.nodes))},addSeriesLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,c=this.chart.graphLayoutsLookup,d=m(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});var e=b[a.type+"-series"];e||(b[a.type+"-series"]=e=new f.layouts[a.type],e.init(d),c.splice(e.index,
0,e));this.parentNodeLayout=e;this.createParentNodes()},addLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,c=this.chart.graphLayoutsLookup,d=this.chart.options.chart;b||(this.chart.graphLayoutsStorage=b={},this.chart.graphLayoutsLookup=c=[]);var e=b[a.type];e||(a.enableSimulation=C(d.forExport)?!d.forExport:a.enableSimulation,b[a.type]=e=new f.layouts[a.type],e.init(a),c.splice(e.index,0,e));this.layout=e;this.points.forEach(function(a){a.mass=2;a.degree=1;a.collisionNmb=
1});e.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);e.addElementsToCollection([this],e.series);e.addElementsToCollection(this.points,e.nodes)},deferLayout:function(){var a=this.options.layoutAlgorithm;this.visible&&(this.addLayout(),a.splitSeries&&this.addSeriesLayout())},translate:function(){var a=this.chart,b=this.data,c=this.index,d,e=this.options.useSimulation;this.processedXData=this.xData;this.generatePoints();C(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),this.getPointRadius());
if(e)var f=a.allDataPoints;else f=this.placeBubbles(a.allDataPoints),this.options.draggable=!1;for(d=0;d<f.length;d++)if(f[d][3]===c){var k=b[f[d][4]];var l=f[d][2];e||(k.plotX=f[d][0]-a.plotLeft+a.diffX,k.plotY=f[d][1]-a.plotTop+a.diffY);k.marker=B(k.marker,{radius:l,width:2*l,height:2*l});k.radius=l}e&&this.deferLayout();h(this,"afterTranslate")},checkOverlap:function(a,b){var d=a[0]-b[0],g=a[1]-b[1];return-.001>Math.sqrt(d*d+g*g)-Math.abs(a[2]+b[2])},positionBubble:function(a,b,d){var c=Math.sqrt,
g=Math.asin,e=Math.acos,f=Math.pow,h=Math.abs;c=c(f(a[0]-b[0],2)+f(a[1]-b[1],2));e=e((f(c,2)+f(d[2]+b[2],2)-f(d[2]+a[2],2))/(2*(d[2]+b[2])*c));g=g(h(a[0]-b[0])/c);a=(0>a[1]-b[1]?0:Math.PI)+e+g*(0>(a[0]-b[0])*(a[1]-b[1])?1:-1);return[b[0]+(b[2]+d[2])*Math.sin(a),b[1]-(b[2]+d[2])*Math.cos(a),d[2],d[3],d[4]]},placeBubbles:function(a){var b=this.checkOverlap,d=this.positionBubble,c=[],g=1,e=0,f=0;var h=[];var k;a=a.sort(function(a,b){return b[2]-a[2]});if(a.length){c.push([[0,0,a[0][2],a[0][3],a[0][4]]]);
if(1<a.length)for(c.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),k=2;k<a.length;k++)a[k][2]=a[k][2]||1,h=d(c[g][e],c[g-1][f],a[k]),b(h,c[g][0])?(c.push([]),f=0,c[g+1].push(d(c[g][e],c[g][0],a[k])),g++,e=0):1<g&&c[g-1][f+1]&&b(h,c[g-1][f+1])?(f++,c[g].push(d(c[g][e],c[g-1][f],a[k])),e++):(e++,c[g].push(h));this.chart.stages=c;this.chart.rawPositions=[].concat.apply([],c);this.resizeRadius();h=this.chart.rawPositions}return h},resizeRadius:function(){var a=this.chart,b=a.rawPositions,c=Math.min,
d=Math.max,e=a.plotLeft,f=a.plotTop,h=a.plotHeight,k=a.plotWidth,l,m,q;var r=l=Number.POSITIVE_INFINITY;var t=m=Number.NEGATIVE_INFINITY;for(q=0;q<b.length;q++){var u=b[q][2];r=c(r,b[q][0]-u);t=d(t,b[q][0]+u);l=c(l,b[q][1]-u);m=d(m,b[q][1]+u)}q=[t-r,m-l];c=c.apply([],[(k-e)/q[0],(h-f)/q[1]]);if(1e-10<Math.abs(c-1)){for(q=0;q<b.length;q++)b[q][2]*=c;this.placeBubbles(b)}else a.diffY=h/2+f-l-(m-l)/2,a.diffX=k/2+e-r-(t-r)/2},calculateZExtremes:function(){var a=this.options.zMin,b=this.options.zMax,c=
Infinity,d=-Infinity;if(a&&b)return[a,b];this.chart.series.forEach(function(a){a.yData.forEach(function(a){C(a)&&(a>d&&(d=a),a<c&&(c=a))})});a=k(a,c);b=k(b,d);return[a,b]},getPointRadius:function(){var a=this,b=a.chart,c=a.options,d=c.useSimulation,e=Math.min(b.plotWidth,b.plotHeight),f={},h=[],k=b.allDataPoints,l,m,q,r;["minSize","maxSize"].forEach(function(a){var b=parseInt(c[a],10),d=/%$/.test(c[a]);f[a]=d?e*b/100:b*Math.sqrt(k.length)});b.minRadius=l=f.minSize/Math.sqrt(k.length);b.maxRadius=
m=f.maxSize/Math.sqrt(k.length);var t=d?a.calculateZExtremes():[l,m];(k||[]).forEach(function(b,c){q=d?y(b[2],t[0],t[1]):b[2];r=a.getRadius(t[0],t[1],l,m,q);0===r&&(r=null);k[c][2]=r;h.push(r)});a.radii=h},redrawHalo:c.redrawHalo,onMouseDown:c.onMouseDown,onMouseMove:c.onMouseMove,onMouseUp:function(a){if(a.fixedPosition&&!a.removed){var b,d,g=this.layout,e=this.parentNodeLayout;e&&g.options.dragBetweenSeries&&e.nodes.forEach(function(c){a&&a.marker&&c!==a.series.parentNode&&(b=g.getDistXY(a,c),d=
g.vectorLength(b)-c.marker.radius-a.marker.radius,0>d&&(c.series.addPoint(m(a.options,{plotX:a.plotX,plotY:a.plotY}),!1),g.removeElementFromCollection(a,g.nodes),a.remove()))});c.onMouseUp.apply(this,arguments)}},destroy:function(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(function(a){a.removeElementFromCollection(this,a.series)},this);this.parentNode&&(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),this.parentNode.dataLabel&&
(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));f.Series.prototype.destroy.apply(this,arguments)},alignDataLabel:f.Series.prototype.alignDataLabel},{destroy:function(){this.series.layout&&this.series.layout.removeElementFromCollection(this,this.series.layout.nodes);return e.prototype.destroy.apply(this,arguments)}});q(v,"beforeRedraw",function(){this.allDataPoints&&delete this.allDataPoints});""});E(f,"parts-more/Polar.js",[f["parts/Globals.js"],f["parts/Utilities.js"],f["parts-more/Pane.js"]],
function(f,a,e){var b=a.addEvent,l=a.animObject,q=a.defined,y=a.find,C=a.isNumber,B=a.pick,h=a.splat,u=a.uniqueKey,w=a.wrap,m=f.Series,k=f.seriesTypes,A=m.prototype,v=f.Pointer.prototype;A.searchPointByAngle=function(a){var b=this.chart,d=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-d[0]-b.plotLeft,a.chartY-d[1]-b.plotTop)})};A.getConnectors=function(a,b,g,e){var c=e?1:0;var d=0<=b&&b<=a.length-1?b:0>b?a.length-1+b:0;b=0>d-1?a.length-(1+c):d-1;c=d+
1>a.length-1?c:d+1;var f=a[b];c=a[c];var h=f.plotX;f=f.plotY;var k=c.plotX;var p=c.plotY;c=a[d].plotX;d=a[d].plotY;h=(1.5*c+h)/2.5;f=(1.5*d+f)/2.5;k=(1.5*c+k)/2.5;var l=(1.5*d+p)/2.5;p=Math.sqrt(Math.pow(h-c,2)+Math.pow(f-d,2));var m=Math.sqrt(Math.pow(k-c,2)+Math.pow(l-d,2));h=Math.atan2(f-d,h-c);l=Math.PI/2+(h+Math.atan2(l-d,k-c))/2;Math.abs(h-l)>Math.PI/2&&(l-=Math.PI);h=c+Math.cos(l)*p;f=d+Math.sin(l)*p;k=c+Math.cos(Math.PI+l)*m;l=d+Math.sin(Math.PI+l)*m;c={rightContX:k,rightContY:l,leftContX:h,
leftContY:f,plotX:c,plotY:d};g&&(c.prevPointCont=this.getConnectors(a,b,!1,e));return c};A.toXY=function(a){var b=this.chart,d=this.xAxis;var e=this.yAxis;var f=a.plotX,h=a.plotY,k=a.series,l=b.inverted,m=a.y,q=l?f:e.len-h;l&&k&&!k.isRadialBar&&(a.plotY=h="number"===typeof m?e.translate(m)||0:0);a.rectPlotX=f;a.rectPlotY=h;e.center&&(q+=e.center[3]/2);e=l?e.postTranslate(h,q):d.postTranslate(f,q);a.plotX=a.polarPlotX=e.x-b.plotLeft;a.plotY=a.polarPlotY=e.y-b.plotTop;this.kdByAngle?(b=(f/Math.PI*180+
d.pane.options.startAngle)%360,0>b&&(b+=360),a.clientX=b):a.clientX=a.plotX};k.spline&&(w(k.spline.prototype,"getPointSpline",function(a,b,g,e){this.chart.polar?e?(a=this.getConnectors(b,e,!0,this.connectEnds),a=["C",a.prevPointCont.rightContX,a.prevPointCont.rightContY,a.leftContX,a.leftContY,a.plotX,a.plotY]):a=["M",g.plotX,g.plotY]:a=a.call(this,b,g,e);return a}),k.areasplinerange&&(k.areasplinerange.prototype.getPointSpline=k.spline.prototype.getPointSpline));b(m,"afterTranslate",function(){var a=
this.chart;if(a.polar&&this.xAxis){(this.kdByAngle=a.tooltip&&a.tooltip.shared)?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy="xy";if(!this.preventPostTranslate)for(var c=this.points,g=c.length;g--;)this.toXY(c[g]),!a.hasParallelCoordinates&&!this.yAxis.reversed&&c[g].y<this.yAxis.min&&(c[g].isNull=!0);this.hasClipCircleSetter||(this.hasClipCircleSetter=!!this.eventsToUnbind.push(b(this,"afterRender",function(){if(a.polar){var b=this.yAxis.pane.center;this.clipCircle?this.clipCircle.animate({x:b[0],
y:b[1],r:b[2]/2,innerR:b[3]/2}):this.clipCircle=a.renderer.clipCircle(b[0],b[1],b[2]/2,b[3]/2);this.group.clip(this.clipCircle);this.setClip=f.noop}})))}},{order:2});w(A,"getGraphPath",function(a,b){var c=this,d;if(this.chart.polar){b=b||this.points;for(d=0;d<b.length;d++)if(!b[d].isNull){var e=d;break}if(!1!==this.options.connectEnds&&"undefined"!==typeof e){this.connectEnds=!0;b.splice(b.length,0,b[e]);var f=!0}b.forEach(function(a){"undefined"===typeof a.polarPlotY&&c.toXY(a)})}d=a.apply(this,
[].slice.call(arguments,1));f&&b.pop();return d});var t=function(a,b){var c=this,d=this.chart,e=this.options.animation,h=this.group,k=this.markerGroup,m=this.xAxis.center,q=d.plotLeft,r=d.plotTop,t,u,w,v;if(d.polar)if(c.isRadialBar)b||(c.startAngleRad=B(c.translatedThreshold,c.xAxis.startAngleRad),f.seriesTypes.pie.prototype.animate.call(c,b));else{if(d.renderer.isSVG)if(e=l(e),c.is("column")){if(!b){var A=m[3]/2;c.points.forEach(function(a){t=a.graphic;w=(u=a.shapeArgs)&&u.r;v=u&&u.innerR;t&&u&&
(t.attr({r:A,innerR:A}),t.animate({r:w,innerR:v},c.options.animation))})}}else b?(a={translateX:m[0]+q,translateY:m[1]+r,scaleX:.001,scaleY:.001},h.attr(a),k&&k.attr(a)):(a={translateX:q,translateY:r,scaleX:1,scaleY:1},h.animate(a,e),k&&k.animate(a,e))}else a.call(this,b)};w(A,"animate",t);k.column&&(m=k.arearange.prototype,k=k.column.prototype,k.polarArc=function(a,b,e,f){var c=this.xAxis.center,d=this.yAxis.len,g=c[3]/2;b=d-b+g;a=d-B(a,d)+g;this.yAxis.reversed&&(0>b&&(b=g),0>a&&(a=g));return{x:c[0],
y:c[1],r:b,innerR:a,start:e,end:f}},w(k,"animate",t),w(k,"translate",function(b){var c=this.options,d=c.stacking,e=this.chart,f=this.xAxis,h=this.yAxis,k=h.reversed,l=h.center,m=f.startAngleRad,r=f.endAngleRad-m;this.preventPostTranslate=!0;b.call(this);if(f.isRadial){b=this.points;f=b.length;var t=h.translate(h.min);var u=h.translate(h.max);c=c.threshold||0;if(e.inverted&&C(c)){var w=h.translate(c);q(w)&&(0>w?w=0:w>r&&(w=r),this.translatedThreshold=w+m)}for(;f--;){c=b[f];var v=c.barX;var A=c.x;var B=
c.y;c.shapeType="arc";if(e.inverted){c.plotY=h.translate(B);if(d){if(B=h.stacks[(0>B?"-":"")+this.stackKey],this.visible&&B&&B[A]&&!c.isNull){var y=B[A].points[this.getStackIndicator(void 0,A,this.index).key];var D=h.translate(y[0]);y=h.translate(y[1]);q(D)&&(D=a.clamp(D,0,r))}}else D=w,y=c.plotY;D>y&&(y=[D,D=y][0]);if(!k)if(D<t)D=t;else if(y>u)y=u;else{if(y<t||D>u)D=y=0}else if(y>t)y=t;else if(D<u)D=u;else if(D>t||y<u)D=y=r;h.min>h.max&&(D=y=k?r:0);D+=m;y+=m;l&&(c.barX=v+=l[3]/2);A=Math.max(v,0);
B=Math.max(v+c.pointWidth,0);c.shapeArgs={x:l&&l[0],y:l&&l[1],r:B,innerR:A,start:D,end:y};c.opacity=D===y?0:void 0;c.plotY=(q(this.translatedThreshold)&&(D<this.translatedThreshold?D:y))-m}else D=v+m,c.shapeArgs=this.polarArc(c.yBottom,c.plotY,D,D+c.pointWidth);this.toXY(c);e.inverted?(v=h.postTranslate(c.rectPlotY,v+c.pointWidth/2),c.tooltipPos=[v.x-e.plotLeft,v.y-e.plotTop]):c.tooltipPos=[c.plotX,c.plotY];l&&(c.ttBelow=c.plotY>l[1])}}}),k.findAlignments=function(a,b){null===b.align&&(b.align=20<
a&&160>a?"left":200<a&&340>a?"right":"center");null===b.verticalAlign&&(b.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle");return b},m&&(m.findAlignments=k.findAlignments),w(k,"alignDataLabel",function(a,b,e,f,h,k){var c=this.chart,d=B(f.inside,!!this.options.stacking);c.polar?(a=b.rectPlotX/Math.PI*180,c.inverted?(this.forceDL=c.isInsidePlot(b.plotX,Math.round(b.plotY),!1),d&&b.shapeArgs?(h=b.shapeArgs,h=this.yAxis.postTranslate((h.start+h.end)/2-this.xAxis.startAngleRad,b.barX+b.pointWidth/
2),h={x:h.x-c.plotLeft,y:h.y-c.plotTop}):b.tooltipPos&&(h={x:b.tooltipPos[0],y:b.tooltipPos[1]}),f.align=B(f.align,"center"),f.verticalAlign=B(f.verticalAlign,"middle")):this.findAlignments&&(f=this.findAlignments(a,f)),A.alignDataLabel.call(this,b,e,f,h,k),this.isRadialBar&&b.shapeArgs&&b.shapeArgs.start===b.shapeArgs.end&&e.hide(!0)):a.call(this,b,e,f,h,k)}));w(v,"getCoordinates",function(a,b){var c=this.chart,d={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(function(a){var e=a.isXAxis,f=a.center;if("colorAxis"!==
a.coll){var g=b.chartX-f[0]-c.plotLeft;f=b.chartY-f[1]-c.plotTop;d[e?"xAxis":"yAxis"].push({axis:a,value:a.translate(e?Math.PI-Math.atan2(g,f):Math.sqrt(Math.pow(g,2)+Math.pow(f,2)),!0)})}}):d=a.call(this,b);return d});f.SVGRenderer.prototype.clipCircle=function(a,b,e,f){var c=u(),d=this.createElement("clipPath").attr({id:c}).add(this.defs);a=f?this.arc(a,b,e,f,0,2*Math.PI).add(d):this.circle(a,b,e).add(d);a.id=c;a.clipPath=d;return a};b(f.Chart,"getAxes",function(){this.pane||(this.pane=[]);h(this.options.pane).forEach(function(a){new e(a,
this)},this)});b(f.Chart,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});b(f.Series,"afterInit",function(){var a=this.chart;a.inverted&&a.polar&&(this.isRadialSeries=!0,this.is("column")&&(this.isRadialBar=!0))});w(f.Chart.prototype,"get",function(a,b){return y(this.pane,function(a){return a.options.id===b})||a.call(this,b)})});E(f,"masters/highcharts-more.src.js",[],function(){})});
//# sourceMappingURL=highcharts-more.js.map